name: extract-artifacts
author: manuel-rw
description: extract-artifacts
branding:
  icon: copy
  name: Extract Artifacts
  description: Extracts artifacts from an existing Docker image to be used in Proxmox
inputs:
  digest:
    description: Digest of Docker image to use
    required: true
  architecture:
    description: Name of architecture, will be used to create directories (e.g. x64, arm64)
runs:
  using: "composite"
  steps:
    - name: Start docker container for ${{ inputs.architecture }}
      run: "docker run --name homarr-extraction-${{ inputs.architecture }} --pull always -e \"SECRET_ENCRYPTION_KEY=ccfb0bb973a17b16972b42e715b3c805d4a82cf424643f9e554b3cd234da7bf6\" --detach --rm ${{ inputs.digest }}" # TODO: add --detach
    - name: Sleep
      run: sleep 5s
      shell: bash
    - run: mkdir -p ${{ runner.temp }}/extraction/${{ inputs.architecture }}/
    - run: docker exec -it homarr-extraction-${{ inputs.architecture }} "ls" "-lha"
    - name: Extract from ${{ inputs.architecture }} container
      run: |
        docker exec homarr-extraction-${{ inputs.architecture }} tar -cf extraction.tar /app && \
        docker cp homarr-extraction-${{ inputs.architecture }}:/app/extraction.tar ${{ runner.temp }}/extraction/${{ inputs.architecture }}/extraction.tar
    - run: ls -lha
    - run: pwd
    - name: Stop ${{ inputs.architecture }} container
      if: always()
      run: docker container remove --force --volumes homarr-extraction-${{ inputs.architecture }}
    - name: Public Artifact
      uses: actions/upload-artifact@v4
      with:
        path: ${{ runner.temp }}/extraction/
        if-no-files-found: error
        name: extraction-${{ inputs.architecture }}
