name: extract-artifacts
author: manuel
description: extract-artifacts
inputs:
  digest:
    description: Digest of Docker image to use
    required: true
  architecture:
    description: Name of architecture, will be used to create directories (e.g. x64, arm64)
runs:
  using: "composite"
  steps:
    - name: Start docker container for ${{ inputs.architecture }}
      run: docker run --name homarr-extraction-${{ inputs.architecture }} --rm ${{ inputs.digest }}
    - name: Extract from ${{ inputs.architecture }} container
      run: |
        docker cp homarr-extraction-${{ inputs.architecture }}:/app/apps/* ./extraction/${{ inputs.architecture }}/apps \ # Copy apps (e.g. nextjs, tasks, ...)
        docker cp homarr-extraction-${{ inputs.architecture }}:/app/build/* ./extraction/${{ inputs.architecture }}/build \ # Copy compiled driver for database
        docker cp homarr-extraction-${{ inputs.architecture }}:/app/node_modules/* ./extraction/${{ inputs.architecture }}/node_modules # Copy dependencies, they can be architecture-specific for compiled
    - name: Copy non-compiled files from host for ${{ inputs.architecture }}
      run: |
        cp /scripts/entrypoint.sh ./extraction/${{ inputs.architecture }}/entrypoint.sh \
        cp /scripts/next.config.ts ./extraction/${{ inputs.architecture }}/next.config.ts \
        cp /scripts/run.sh ./extraction/${{ inputs.architecture }}/run.sh \
        cp /scripts/package.json ./extraction/${{ inputs.architecture }}/package.json
    - name: Stop ${{ inputs.architecture }} container
      run: docker container remove --force --volumes homarr-extraction-${{ inputs.architecture }}
