export type CustomJsxComponentPackage = "@mantine/core" | "@mantine/charts" | "@mantine/dates" | "@homarr/widgets";

export type CustomJsxComponentSafety = "allowed" | "wrapped" | "denied";

export type CustomJsxComponentCategory =
  | "layout"
  | "content"
  | "feedback"
  | "navigation"
  | "charts"
  | "dates"
  | "interaction"
  | "network"
  | "blocked";

export interface CustomJsxComponentDescriptor {
  name: string;
  package: CustomJsxComponentPackage;
  category: CustomJsxComponentCategory;
  safety: CustomJsxComponentSafety;
  supportedProps: readonly string[];
  subcomponents: readonly string[];
  accessibilityRequirements: readonly string[];
  documentationUrl: string;
  reason?: string;
}

const commonSafeProps = [
  "key",
  "id",
  "style",
  "title",
  "role",
  "aria-label",
  "aria-describedby",
  "aria-hidden",
  "tabIndex",
  "w",
  "h",
  "miw",
  "maw",
  "mih",
  "mah",
  "m",
  "mx",
  "my",
  "mt",
  "mr",
  "mb",
  "ml",
  "p",
  "px",
  "py",
  "pt",
  "pr",
  "pb",
  "pl",
  "bg",
  "c",
  "opacity",
  "display",
  "hiddenFrom",
  "visibleFrom",
  "bd",
  "bdrs",
  "flex",
  "fz",
  "fw",
  "lh",
  "lts",
  "ta",
  "td",
  "tt",
  "radius",
  "shadow",
  "variant",
  "color",
  "size",
  "withBorder",
] as const;

const categorySafeProps: Record<CustomJsxComponentCategory, readonly string[]> = {
  layout: [
    "gap",
    "align",
    "justify",
    "wrap",
    "direction",
    "grow",
    "cols",
    "spacing",
    "verticalSpacing",
    "gutter",
    "span",
    "offset",
    "order",
    "type",
    "orientation",
    "withBorder",
    "shadow",
    "radius",
  ],
  content: [
    "alt",
    "src",
    "href",
    "target",
    "rel",
    "size",
    "fw",
    "fs",
    "td",
    "tt",
    "ta",
    "lts",
    "lh",
    "lineClamp",
    "truncate",
    "inherit",
    "gradient",
    "variant",
    "color",
    "value",
    "prefix",
    "suffix",
    "decimalScale",
    "thousandSeparator",
    "striped",
    "highlightOnHover",
    "withTableBorder",
    "withColumnBorders",
    "type",
    "icon",
    "image",
    "order",
    "fit",
    "fallbackSrc",
    "loading",
    "referrerPolicy",
    "crossOrigin",
    "decoding",
    "draggable",
    "center",
    "spacing",
    "listStyleType",
  ],
  feedback: ["color", "variant", "radius", "size", "value", "sections", "label", "animated", "striped"],
  navigation: [
    "value",
    "defaultValue",
    "active",
    "label",
    "description",
    "leftSection",
    "rightSection",
    "opened",
    "disabled",
    "multiple",
    "chevronPosition",
    "orientation",
    "keepMounted",
    "transitionDuration",
  ],
  charts: [
    "data",
    "dataKey",
    "series",
    "type",
    "curveType",
    "color",
    "colors",
    "withLegend",
    "withTooltip",
    "withXAxis",
    "withYAxis",
    "withDots",
    "gridAxis",
    "unit",
    "valueFormatter",
    "strokeWidth",
    "fillOpacity",
    "connectNulls",
    "tooltipAnimationDuration",
  ],
  dates: [
    "date",
    "defaultDate",
    "value",
    "minDate",
    "maxDate",
    "locale",
    "firstDayOfWeek",
    "weekendDays",
    "hideOutsideDates",
    "hideWeekdays",
    "showWeekNumbers",
    "numberOfColumns",
    "level",
    "size",
  ],
  interaction: [
    "label",
    "value",
    "values",
    "data",
    "checked",
    "defaultChecked",
    "disabled",
    "readOnly",
    "color",
    "variant",
    "size",
    "radius",
    "leftSection",
    "rightSection",
    "loading",
    "min",
    "max",
    "step",
    "total",
    "page",
    "pageSize",
    "defaultTab",
    "title",
    "defaultOpen",
    "type",
    "fullWidth",
  ],
  network: [
    "requestId",
    "params",
    "onParams",
    "offParams",
    "initialValue",
    "label",
    "loadingLabel",
    "successMessage",
    "errorMessage",
    "confirmMessage",
    "invalidate",
    "refreshInterval",
    "trigger",
    "render",
    "path",
    "as",
    "fallback",
    "icon",
    "color",
    "variant",
    "size",
    "radius",
    "disabled",
  ],
  blocked: [],
};

const subcomponentsByName: Readonly<Record<string, readonly string[]>> = {
  Accordion: ["Accordion.Item", "Accordion.Control", "Accordion.Panel"],
  Avatar: ["Avatar.Group"],
  Card: ["Card.Section"],
  Chip: ["Chip.Group"],
  DataList: ["DataList.Item", "DataList.ItemLabel", "DataList.ItemValue"],
  EmptyState: ["EmptyState.Indicator", "EmptyState.Title", "EmptyState.Description", "EmptyState.Actions"],
  Grid: ["Grid.Col"],
  List: ["List.Item"],
  Menu: ["Menu.Target", "Menu.Dropdown", "Menu.Item", "Menu.Label", "Menu.Divider"],
  Progress: ["Progress.Section"],
  Table: ["Table.Thead", "Table.Tbody", "Table.Tfoot", "Table.Caption", "Table.Tr", "Table.Th", "Table.Td"],
  Tabs: ["Tabs.List", "Tabs.Tab", "Tabs.Panel"],
  Timeline: ["Timeline.Item"],
};

const accessibilityByCategory: Record<CustomJsxComponentCategory, readonly string[]> = {
  layout: ["Keep visual order consistent with reading order."],
  content: ["Provide meaningful text alternatives for non-text content."],
  feedback: ["Do not rely on color alone to communicate status."],
  navigation: ["Provide an accessible label for controls without visible text."],
  charts: ["Include a nearby text summary of the chart data."],
  dates: ["Include a textual date when the visual calendar carries meaning."],
  interaction: ["Provide a visible label or aria-label."],
  network: ["Action labels must describe their effect; destructive actions require confirmation."],
  blocked: [],
};

const componentSafeProps: Readonly<Record<string, readonly string[]>> = {
  "Tabs.List": ["grow"],
  ScrollArea: ["offsetScrollbars"],
  SubData: ["alt", "fit"],
};

function documentationUrl(packageName: CustomJsxComponentPackage, name: string): string {
  if (packageName === "@homarr/widgets") return "https://homarr.dev/docs/management/custom-widgets/";
  const section = packageName === "@mantine/core" ? "core" : packageName === "@mantine/charts" ? "charts" : "dates";
  return `https://mantine.dev/${section}/${name.split(".")[0]?.toLowerCase() ?? ""}/`;
}

const describe = (
  packageName: CustomJsxComponentPackage,
  category: CustomJsxComponentCategory,
  safety: CustomJsxComponentSafety,
  names: readonly string[],
  reason?: string,
): CustomJsxComponentDescriptor[] =>
  names.map((name) => ({
    name,
    package: packageName,
    category,
    safety,
    supportedProps:
      safety === "denied"
        ? []
        : [
            ...new Set<string>([
              ...commonSafeProps,
              ...categorySafeProps[category],
              ...(componentSafeProps[name] ?? []),
            ]),
          ],
    subcomponents: subcomponentsByName[name] ?? [],
    accessibilityRequirements: accessibilityByCategory[category],
    documentationUrl: documentationUrl(packageName, name),
    reason,
  }));

/**
 * The source of truth for the Custom JSX public component surface.
 *
 * Components marked `wrapped` require a runtime wrapper that removes unsafe props
 * or supplies inert/read-only behavior. `denied` entries are deliberately kept in
 * the registry so Mantine upgrades cannot silently expand the template surface.
 */
export const customJsxComponentRegistry: readonly CustomJsxComponentDescriptor[] = [
  ...describe("@mantine/core", "layout", "allowed", [
    "Box",
    "Stack",
    "Group",
    "Flex",
    "Grid",
    "Grid.Col",
    "SimpleGrid",
    "Center",
    "Space",
    "Container",
    "AspectRatio",
    "ScrollArea",
    "Paper",
    "Card",
    "Card.Section",
    "Divider",
    "Fieldset",
    "VisuallyHidden",
    "Typography",
    "FloatingIndicator",
  ]),
  ...describe("@mantine/core", "content", "allowed", [
    "Text",
    "Title",
    "Code",
    "Highlight",
    "Mark",
    "Kbd",
    "Blockquote",
    "NumberFormatter",
    "Badge",
    "ThemeIcon",
    "ColorSwatch",
    "Table",
    "Table.Thead",
    "Table.Tbody",
    "Table.Tfoot",
    "Table.Caption",
    "Table.Tr",
    "Table.Th",
    "Table.Td",
    "List",
    "List.Item",
    "Timeline",
    "Timeline.Item",
    "Indicator",
    "Pill",
    "Image",
    "Avatar",
    "Avatar.Group",
    "BackgroundImage",
    "DataList",
    "DataList.Item",
    "DataList.ItemLabel",
    "DataList.ItemValue",
    "EmptyState",
    "EmptyState.Indicator",
    "EmptyState.Title",
    "EmptyState.Description",
    "EmptyState.Actions",
    "Marquee",
    "RollingNumber",
  ]),
  ...describe("@mantine/core", "feedback", "allowed", [
    "Alert",
    "Progress",
    "Progress.Section",
    "RingProgress",
    "SemiCircleProgress",
    "Skeleton",
    "Loader",
  ]),
  ...describe("@mantine/core", "feedback", "wrapped", ["Notification", "LoadingOverlay", "Overlay"]),
  ...describe("@mantine/core", "navigation", "allowed", [
    "Accordion",
    "Accordion.Item",
    "Accordion.Control",
    "Accordion.Panel",
    "Tabs",
    "Tabs.List",
    "Tabs.Tab",
    "Tabs.Panel",
    "Stepper.Step",
    "HoverCard",
    "HoverCard.Target",
    "HoverCard.Dropdown",
    "Menu",
    "Menu.Target",
    "Menu.Dropdown",
    "Menu.Item",
    "Menu.Label",
    "Menu.Divider",
    "Tooltip",
    "Spoiler",
    "Collapse",
    "Transition",
  ]),
  ...describe("@mantine/core", "navigation", "wrapped", ["Anchor", "NavLink", "Breadcrumbs", "Stepper", "Tree"]),
  ...describe("@mantine/core", "interaction", "wrapped", [
    "Button",
    "ActionIcon",
    "Burger",
    "CloseButton",
    "Chip",
    "Chip.Group",
    "CopyButton",
    "Pagination",
    "Rating",
    "SegmentedControl",
    "Slider",
    "Switch",
  ]),
  ...describe("@mantine/charts", "charts", "allowed", [
    "AreaChart",
    "BarChart",
    "BarsList",
    "BubbleChart",
    "ChartLegend",
    "ChartTooltip",
    "CompositeChart",
    "DonutChart",
    "FunnelChart",
    "Heatmap",
    "LineChart",
    "PieChart",
    "RadarChart",
    "RadialBarChart",
    "SankeyChart",
    "ScatterChart",
    "Sparkline",
    "Treemap",
  ]),
  ...describe("@mantine/dates", "dates", "wrapped", [
    "Calendar",
    "MiniCalendar",
    "DatePicker",
    "Day",
    "WeekdaysRow",
    "Month",
    "CalendarHeader",
    "YearPicker",
    "MonthPicker",
    "TimeGrid",
    "PickerControl",
    "YearsList",
    "MonthsList",
    "DecadeLevel",
    "YearLevel",
    "MonthLevel",
    "LevelsGroup",
    "DecadeLevelGroup",
    "YearLevelGroup",
    "MonthLevelGroup",
  ]),
  ...describe("@mantine/dates", "dates", "allowed", ["TimeValue"]),
  ...describe("@homarr/widgets", "interaction", "allowed", [
    "PaginatedList",
    "TabsContainer",
    "TabPanel",
    "Collapsible",
    "StatBar",
    "TypeBadge",
  ]),
  ...describe("@homarr/widgets", "network", "wrapped", [
    "SubFetch",
    "SubData",
    "ActionButton",
    "ToggleSwitch",
    "RefreshButton",
  ]),
  {
    name: "TablerIcon",
    package: "@homarr/widgets",
    category: "content",
    safety: "wrapped",
    supportedProps: ["name", "size", "color", "stroke"],
    subcomponents: [],
    accessibilityRequirements: accessibilityByCategory.content,
    documentationUrl: documentationUrl("@homarr/widgets", "TablerIcon"),
  },
  ...describe(
    "@mantine/core",
    "blocked",
    "denied",
    [
      "AppShell",
      "Affix",
      "ComboboxPopover",
      "Dialog",
      "Drawer",
      "FloatingWindow",
      "FocusTrap",
      "Menubar",
      "Modal",
      "ModalBase",
      "Portal",
      "Popover",
      "RemoveScroll",
    ],
    "Escapes the widget layout or focus boundary",
  ),
  ...describe(
    "@mantine/core",
    "blocked",
    "denied",
    [
      "AngleSlider",
      "Autocomplete",
      "Checkbox",
      "ColorInput",
      "ColorPicker",
      "Combobox",
      "FileButton",
      "FileInput",
      "Input",
      "InputBase",
      "JsonInput",
      "MaskInput",
      "MultiSelect",
      "NativeSelect",
      "NumberInput",
      "PasswordInput",
      "PillsInput",
      "PinInput",
      "Radio",
      "Select",
      "TagsInput",
      "Textarea",
      "TextInput",
      "TreeSelect",
      "UnstyledButton",
    ],
    "Arbitrary form controls are not connected to the declarative action model",
  ),
  ...describe(
    "@mantine/core",
    "blocked",
    "denied",
    ["OverflowList", "Scroller", "Splitter", "TableOfContents"],
    "Requires callback, document, or layout capabilities that are not exposed to templates",
  ),
  ...describe(
    "@mantine/core",
    "blocked",
    "denied",
    [
      "AccordionChevron",
      "ActionIconGroup",
      "ActionIconGroupSection",
      "AlphaSlider",
      "AppShellAside",
      "AppShellFooter",
      "AppShellHeader",
      "AppShellMain",
      "AppShellNavbar",
      "AppShellSection",
      "ButtonGroup",
      "ButtonGroupSection",
      "CheckIcon",
      "CheckboxCard",
      "CheckboxGroup",
      "CheckboxIndicator",
      "CloseIcon",
      "ColorSchemeScript",
      "ComboboxChevron",
      "ComboboxClearButton",
      "ComboboxDropdown",
      "ComboboxDropdownTarget",
      "ComboboxEmpty",
      "ComboboxEventsTarget",
      "ComboboxFooter",
      "ComboboxGroup",
      "ComboboxHeader",
      "ComboboxHiddenInput",
      "ComboboxOption",
      "ComboboxOptions",
      "ComboboxPopoverTarget",
      "ComboboxSearch",
      "ComboboxTarget",
      "DirectionProvider",
      "DrawerBody",
      "DrawerCloseButton",
      "DrawerContent",
      "DrawerHeader",
      "DrawerOverlay",
      "DrawerRoot",
      "DrawerStack",
      "DrawerTitle",
      "FlatTreeNode",
      "FloatingArrow",
      "FocusTrapInitialFocus",
      "HeadlessMantineProvider",
      "HoverCardGroup",
      "HueSlider",
      "InlineStyles",
      "InputClearButton",
      "InputClearSection",
      "InputDescription",
      "InputError",
      "InputLabel",
      "InputPlaceholder",
      "InputSuccess",
      "InputWrapper",
      "MantineProvider",
      "MantineThemeProvider",
      "MenuCheckboxGroup",
      "MenuCheckboxItem",
      "MenuContextMenu",
      "MenuRadioGroup",
      "MenuRadioItem",
      "MenuSearch",
      "MenuSub",
      "MenuSubDropdown",
      "MenuSubItem",
      "MenuSubTarget",
      "MenubarDropdown",
      "MenubarMenu",
      "MenubarTarget",
      "ModalBaseBody",
      "ModalBaseCloseButton",
      "ModalBaseContent",
      "ModalBaseHeader",
      "ModalBaseOverlay",
      "ModalBaseTitle",
      "ModalBody",
      "ModalCloseButton",
      "ModalContent",
      "ModalHeader",
      "ModalOverlay",
      "ModalRoot",
      "ModalStack",
      "ModalTitle",
      "NativeScrollArea",
      "OptionalPortal",
      "OptionsDropdown",
      "PaginationControl",
      "PaginationDots",
      "PaginationFirst",
      "PaginationItems",
      "PaginationLabel",
      "PaginationLast",
      "PaginationNext",
      "PaginationPrevious",
      "PaginationRoot",
      "PillGroup",
      "PillsInputField",
      "PopoverContextMenu",
      "PopoverDropdown",
      "PopoverTarget",
      "ProgressLabel",
      "ProgressRoot",
      "RadioCard",
      "RadioGroup",
      "RadioIcon",
      "RadioIndicator",
      "RangeSlider",
      "ScrollAreaAutosize",
      "SplitterPane",
      "StepperCompleted",
      "SwitchGroup",
      "TableScrollContainer",
      "TooltipFloating",
      "TooltipGroup",
      "TreeSelectOption",
    ],
    "Internal, provider, compound-control, form, portal, or document-level export outside the safe declarative surface",
  ),
  ...describe(
    "@mantine/charts",
    "blocked",
    "denied",
    ["AreaGradient"],
    "Low-level chart implementation helper that is not a standalone declarative display component",
  ),
  ...describe(
    "@mantine/dates",
    "blocked",
    "denied",
    [
      "DatesProvider",
      "HiddenDatesInput",
      "TimeInput",
      "TimePicker",
      "PickerInputBase",
      "DateInput",
      "DateTimePicker",
      "InlineDateTimePicker",
      "YearPickerInput",
      "MonthPickerInput",
      "DatePickerInput",
    ],
    "Input and provider components are outside the read-only template surface",
  ),
];

export const enabledCustomJsxComponents = customJsxComponentRegistry.filter(({ safety }) => safety !== "denied");

export const customJsxComponentByName = new Map(customJsxComponentRegistry.map((entry) => [entry.name, entry]));

export const customJsxSupportedPropsByName = new Map(
  enabledCustomJsxComponents.map((component) => [component.name, new Set(component.supportedProps)]),
);
