export const hotkeys = {
  toggleBoardEdit: "mod+e",
  toggleColorScheme: "mod+j",
  saveNotebook: "mod+s",
  openSpotlight: "mod+k",
  nextBoard: "mod+shift+ArrowRight",
  previousBoard: "mod+shift+ArrowLeft",
  switchBoard1: "mod+shift+1",
  switchBoard2: "mod+shift+2",
  switchBoard3: "mod+shift+3",
  switchBoard4: "mod+shift+4",
  switchBoard5: "mod+shift+5",
  switchBoard6: "mod+shift+6",
  switchBoard7: "mod+shift+7",
  switchBoard8: "mod+shift+8",
  switchBoard9: "mod+shift+9",
};
