export const widgetKinds = [
  "clock",
  "weather",
  "app",
  "iframe",
  "video",
  "notebook",
  "dnsHoleSummary",
  "dnsHoleControls",
  "smartHome-entityState",
  "smartHome-executeAutomation",
  "mediaServer",
  "calendar",
  "downloads",
  "mediaRequests-requestList",
  "mediaRequests-requestStats",
  "mediaTranscoding",
  "minecraftServerStatus",
  "rssFeed",
  "bookmarks",
  "indexerManager",
  "healthMonitoring",
  "docker",
] as const;
export type WidgetKind = (typeof widgetKinds)[number];
