import { randomUUID } from "node:crypto";
import { command, positional, string } from "@drizzle-team/brocli";

import { customWidgetPackageSchema } from "@homarr/custom-widgets/package";
import { widgetReferencePackages } from "@homarr/widget-sdk/examples";

export const widgetInitCommand = command({
  name: "init",
  aliases: ["scaffold"],
  desc: "Create an editable local widget project from a reference package",
  options: {
    directory: positional("directory").required().desc("New project directory (must not already exist)"),
    example: string("example")
      .default("clock")
      .desc(`Reference package: ${Object.keys(widgetReferencePackages).join(", ")}`),
    id: string("id").desc("Package identity; a unique local identity is generated by default"),
    name: string("name").desc("Widget display name"),
  },
  handler: async ({ directory, example, id, name }) => {
    const reference = widgetReferencePackages[example as keyof typeof widgetReferencePackages];
    if (!reference)
      throw new Error(`Unknown example '${example}'. Choose ${Object.keys(widgetReferencePackages).join(", ")}`);
    const source = customWidgetPackageSchema.parse({
      ...reference,
      manifest: {
        ...reference.manifest,
        id: id ?? `local.${randomUUID()}`,
        name: name ?? reference.manifest.name,
        version: "1.0.0",
      },
    });
    const { writeCustomWidgetProject } = await import("@homarr/custom-widgets/package/server");
    const path = await writeCustomWidgetProject(source, directory);
    console.log(`Created ${source.manifest.id}: ${path}`);
    console.log(`Edit homarr-widget.json and the source files, then run: homarr widgets validate ${directory}`);
  },
});
