packages:
  - apps/*
  - packages/*
  - tooling/*

onlyBuiltDependencies:
  - "@tree-sitter-grammars/tree-sitter-yaml"
  - "bcrypt"
  - "better-sqlite3"
  - "cpu-features"
  - "esbuild"
  - "sharp"
  - "ssh2"
  - "tree-sitter"
  - "tree-sitter-json"

overrides:
  "@babel/helpers@<7.26.10": ">=7.28.4"
  "@babel/runtime@<7.26.10": ">=7.28.4"
  "axios@>=1.0.0 <1.8.2": ">=1.13.1"
  "brace-expansion@>=2.0.0 <=2.0.1": ">=4.0.1"
  "brace-expansion@>=1.0.0 <=1.1.11": ">=4.0.1"
  "esbuild@<=0.24.2": ">=0.25.11"
  "form-data@>=4.0.0 <4.0.4": ">=4.0.4"
  "hono@<4.6.5": ">=4.10.4"
  "linkifyjs@<4.3.2": ">=4.3.2"
  "nanoid@>=4.0.0 <5.0.9": ">=5.1.6"
  "prismjs@<1.30.0": ">=1.30.0"
  "proxmox-api>undici": "7.16.0"
  "react-is": "^19.2.0"
  "rollup@>=4.0.0 <4.22.4": ">=4.52.5"
  "sha.js@<=2.4.11": ">=2.4.12"
  "tar-fs@>=3.0.0 <3.0.9": ">=3.1.1"
  "tar-fs@>=2.0.0 <2.1.3": ">=3.1.1"
  "tmp@<=0.2.3": ">=0.2.5"
  "vite@>=5.0.0 <=5.4.18": ">=7.1.12"

patchedDependencies:
  "@types/node-unifi": "patches/@types__node-unifi.patch"
  "trpc-to-openapi": "patches/trpc-to-openapi.patch"

allowUnusedPatches: true

ignoredBuiltDependencies:
  - "@scarf/scarf"
  - "core-js-pure"
  - "protobufjs"
