import type { OpenApiMeta } from "trpc-to-openapi";
import type { AnyProcedure } from "@trpc/server";
import type { RestRoute } from "./procedure";
import { restSources } from "./sources";

// Existing route definitions remain owned by their native procedure. Project them through
// the same transport adapter without changing their public paths or operation identifiers.
function existingRoute(source: AnyProcedure, operationId: string): RestRoute {
  const openapi = (source["_def"].meta as OpenApiMeta | undefined)?.openapi;
  if (!openapi) throw new Error(`Missing native REST metadata for ${operationId}`);
  if (!openapi.path.startsWith("/api/")) throw new Error(`Invalid native REST path for ${operationId}`);
  return {
    ...openapi,
    path: openapi.path as `/api/${string}`,
    operationId: openapi.operationId ?? operationId,
    tags: openapi.tags ?? [],
    summary: openapi.summary ?? operationId,
    public: openapi.protect === false,
  };
}

export const restRoutes = {
  "user.getPreferences": existingRoute(restSources["user.getPreferences"], "user-getPreferences"),
  "user.updatePreferences": existingRoute(restSources["user.updatePreferences"], "user-updatePreferences"),
  "apiKeys.create": existingRoute(restSources["apiKeys.create"], "apiKeysRouter-create"),
  "apiKeys.delete": existingRoute(restSources["apiKeys.delete"], "apiKeysRouter-delete"),
  "apiKeys.getAll": existingRoute(restSources["apiKeys.getAll"], "apiKeysRouter-getAll"),
  "app.all": existingRoute(restSources["app.all"], "appRouter-all"),
  "app.byId": existingRoute(restSources["app.byId"], "appRouter-byId"),
  "app.create": existingRoute(restSources["app.create"], "appRouter-create"),
  "app.delete": existingRoute(restSources["app.delete"], "appRouter-delete"),
  "app.getPaginated": existingRoute(restSources["app.getPaginated"], "appRouter-getPaginated"),
  "app.search": existingRoute(restSources["app.search"], "appRouter-search"),
  "app.selectable": existingRoute(restSources["app.selectable"], "appRouter-selectable"),
  "app.update": existingRoute(restSources["app.update"], "appRouter-update"),
  "board.catalog": {
    method: "GET",
    path: "/api/boards/catalog",
    tags: ["boards"],
    summary: "List accessible board picker metadata",
    public: true,
  },
  "board.exists": {
    method: "GET",
    path: "/api/boards/name-exists",
    tags: ["boards"],
    summary: "Check whether a board name is taken",
    inputKey: "name",
  },
  "info.isDemoMode": { method: "GET", path: "/api/info/demo", tags: ["info"], summary: "Get demo mode", public: true },
  "info.isDemoReadOnly": {
    method: "GET",
    path: "/api/info/read-only",
    tags: ["info"],
    summary: "Get demo read-only mode",
    public: true,
  },
  "user.completeTour": {
    method: "POST",
    path: "/api/users/me/tours/complete",
    tags: ["users"],
    summary: "Mark a tour complete",
  },
  "user.getTourStatus": {
    method: "GET",
    path: "/api/users/me/tours",
    tags: ["users"],
    summary: "Get the current user's tour preferences",
  },
  "user.resetTours": {
    method: "DELETE",
    path: "/api/users/me/tours",
    tags: ["users"],
    summary: "Reset the current user's tours",
  },
  "board.addItem": existingRoute(restSources["board.addItem"], "boardRouter-addItem"),
  "board.addSection": existingRoute(restSources["board.addSection"], "boardRouter-addSection"),
  "board.changeBoardVisibility": existingRoute(
    restSources["board.changeBoardVisibility"],
    "boardRouter-changeBoardVisibility",
  ),
  "board.createBoard": existingRoute(restSources["board.createBoard"], "boardRouter-createBoard"),
  "board.deleteBoard": existingRoute(restSources["board.deleteBoard"], "boardRouter-deleteBoard"),
  "board.duplicateBoard": existingRoute(restSources["board.duplicateBoard"], "boardRouter-duplicateBoard"),
  "board.exportBoard": existingRoute(restSources["board.exportBoard"], "boardRouter-exportBoard"),
  "board.getAllBoards": existingRoute(restSources["board.getAllBoards"], "boardRouter-getAllBoards"),
  "board.getBoardById": existingRoute(restSources["board.getBoardById"], "boardRouter-getBoardById"),
  "board.getBoardPermissions": existingRoute(
    restSources["board.getBoardPermissions"],
    "boardRouter-getBoardPermissions",
  ),
  "board.getItems": existingRoute(restSources["board.getItems"], "boardRouter-getItems"),
  "board.getLayouts": existingRoute(restSources["board.getLayouts"], "boardRouter-getLayouts"),
  "board.getSections": existingRoute(restSources["board.getSections"], "boardRouter-getSections"),
  "board.importBoard": existingRoute(restSources["board.importBoard"], "boardRouter-importBoard"),
  "board.removeItem": existingRoute(restSources["board.removeItem"], "boardRouter-removeItem"),
  "board.removeSection": existingRoute(restSources["board.removeSection"], "boardRouter-removeSection"),
  "board.renameBoard": existingRoute(restSources["board.renameBoard"], "boardRouter-renameBoard"),
  "board.saveGroupBoardPermissions": existingRoute(
    restSources["board.saveGroupBoardPermissions"],
    "boardRouter-saveGroupBoardPermissions",
  ),
  "board.saveLayouts": existingRoute(restSources["board.saveLayouts"], "boardRouter-saveLayouts"),
  "board.savePartialBoardSettings": existingRoute(
    restSources["board.savePartialBoardSettings"],
    "boardRouter-savePartialBoardSettings",
  ),
  "board.saveUserBoardPermissions": existingRoute(
    restSources["board.saveUserBoardPermissions"],
    "boardRouter-saveUserBoardPermissions",
  ),
  "board.setHomeBoard": existingRoute(restSources["board.setHomeBoard"], "boardRouter-setHomeBoard"),
  "board.setMobileHomeBoard": existingRoute(restSources["board.setMobileHomeBoard"], "boardRouter-setMobileHomeBoard"),
  "board.updateItem": existingRoute(restSources["board.updateItem"], "boardRouter-updateItem"),
  "board.updateItemLayout": existingRoute(restSources["board.updateItemLayout"], "boardRouter-updateItemLayout"),
  "board.updateSection": existingRoute(restSources["board.updateSection"], "boardRouter-updateSection"),
  "certificates.ensureRootCertificate": existingRoute(
    restSources["certificates.ensureRootCertificate"],
    "certificates-ensureRootCertificate",
  ),
  "certificates.getCertificate": existingRoute(
    restSources["certificates.getCertificate"],
    "certificates-getCertificate",
  ),
  "config.export": existingRoute(restSources["config.export"], "configRouter-export"),
  "config.import": existingRoute(restSources["config.import"], "configRouter-import"),
  "group.addMember": existingRoute(restSources["group.addMember"], "groupRouter-addMember"),
  "group.createGroup": existingRoute(restSources["group.createGroup"], "groupRouter-createGroup"),
  "group.deleteGroup": existingRoute(restSources["group.deleteGroup"], "groupRouter-deleteGroup"),
  "group.getAll": existingRoute(restSources["group.getAll"], "groupRouter-getAll"),
  "group.getById": existingRoute(restSources["group.getById"], "groupRouter-getById"),
  "group.removeMember": existingRoute(restSources["group.removeMember"], "groupRouter-removeMember"),
  "group.savePermissions": existingRoute(restSources["group.savePermissions"], "groupRouter-savePermissions"),
  "group.updateGroup": existingRoute(restSources["group.updateGroup"], "groupRouter-updateGroup"),
  "info.getInfo": existingRoute(restSources["info.getInfo"], "infoRouter-getInfo"),
  "integration.all": existingRoute(restSources["integration.all"], "integrationRouter-all"),
  "integration.byId": existingRoute(restSources["integration.byId"], "integrationRouter-byId"),
  "integration.create": existingRoute(restSources["integration.create"], "integrationRouter-create"),
  "integration.delete": existingRoute(restSources["integration.delete"], "integrationRouter-delete"),
  "integration.getKinds": existingRoute(restSources["integration.getKinds"], "integrationRouter-getKinds"),
  "integration.request": existingRoute(restSources["integration.request"], "integrationRouter-request"),
  "integration.testConnection": existingRoute(
    restSources["integration.testConnection"],
    "integrationRouter-testConnection",
  ),
  "integration.update": existingRoute(restSources["integration.update"], "integrationRouter-update"),
  "invite.createInvite": existingRoute(restSources["invite.createInvite"], "inviteRouter-createInvite"),
  "invite.deleteInvite": existingRoute(restSources["invite.deleteInvite"], "inviteRouter-deleteInvite"),
  "invite.getAll": existingRoute(restSources["invite.getAll"], "inviteRouter-getAll"),
  "searchEngine.byId": existingRoute(restSources["searchEngine.byId"], "searchEngineRouter-byId"),
  "searchEngine.create": existingRoute(restSources["searchEngine.create"], "searchEngineRouter-create"),
  "searchEngine.delete": existingRoute(restSources["searchEngine.delete"], "searchEngineRouter-delete"),
  "searchEngine.getPaginated": existingRoute(
    restSources["searchEngine.getPaginated"],
    "searchEngineRouter-getPaginated",
  ),
  "searchEngine.update": existingRoute(restSources["searchEngine.update"], "searchEngineRouter-update"),
  "serverSettings.getAll": existingRoute(restSources["serverSettings.getAll"], "serverSettingsRouter-getAll"),
  "serverSettings.getBoardSettings": existingRoute(
    restSources["serverSettings.getBoardSettings"],
    "serverSettingsRouter-getBoardSettings",
  ),
  "serverSettings.saveSettings": existingRoute(
    restSources["serverSettings.saveSettings"],
    "serverSettingsRouter-saveSettings",
  ),
  "serverSettings.updateBoardSettings": existingRoute(
    restSources["serverSettings.updateBoardSettings"],
    "serverSettingsRouter-updateBoardSettings",
  ),
  "user.changeColorScheme": existingRoute(restSources["user.changeColorScheme"], "userRouter-changeColorScheme"),
  "user.changeDdgBangs": existingRoute(restSources["user.changeDdgBangs"], "userRouter-changeDdgBangs"),
  "user.changeDefaultSearchEngine": existingRoute(
    restSources["user.changeDefaultSearchEngine"],
    "userRouter-changeDefaultSearchEngine",
  ),
  "user.changeEnableRightClickOnWidgets": existingRoute(
    restSources["user.changeEnableRightClickOnWidgets"],
    "userRouter-changeEnableRightClickOnWidgets",
  ),
  "user.changeFirstDayOfWeek": existingRoute(
    restSources["user.changeFirstDayOfWeek"],
    "userRouter-changeFirstDayOfWeek",
  ),
  "user.changeHeaderPreferences": existingRoute(
    restSources["user.changeHeaderPreferences"],
    "userRouter-changeHeaderPreferences",
  ),
  "user.changeHomeBoards": existingRoute(restSources["user.changeHomeBoards"], "userRouter-changeHomeBoards"),
  "user.changePassword": existingRoute(restSources["user.changePassword"], "userRouter-changePassword"),
  "user.changeSearchPreferences": existingRoute(
    restSources["user.changeSearchPreferences"],
    "userRouter-changeSearchPreferences",
  ),
  "user.create": existingRoute(restSources["user.create"], "userRouter-create"),
  "user.delete": existingRoute(restSources["user.delete"], "userRouter-delete"),
  "user.editProfile": existingRoute(restSources["user.editProfile"], "userRouter-editProfile"),
  "user.getAll": existingRoute(restSources["user.getAll"], "userRouter-getAll"),
  "user.getById": existingRoute(restSources["user.getById"], "userRouter-getById"),
  "user.search": existingRoute(restSources["user.search"], "userRouter-search"),
  "user.selectable": existingRoute(restSources["user.selectable"], "userRouter-selectable"),
  "user.setProfileImage": existingRoute(restSources["user.setProfileImage"], "userRouter-setProfileImage"),
  "app.createMany": {
    method: "POST",
    path: "/api/apps/batch",
    tags: ["app"],
    summary: "Create many",
    description: "Create many. Requires app-create permission. All native validation and resource authorization apply.",
    inputKey: "apps",
  },
  "assistant.appendMessage": {
    method: "POST",
    path: "/api/assistant/threads/{threadId}/messages",
    tags: ["assistant"],
    summary: "Append message",
  },
  "assistant.clearCredentials": {
    method: "DELETE",
    path: "/api/assistant/credentials",
    tags: ["assistant"],
    summary: "Clear credentials",
  },
  "assistant.createThread": {
    method: "POST",
    path: "/api/assistant/threads",
    tags: ["assistant"],
    summary: "Create thread",
  },
  "assistant.deleteMessages": {
    method: "DELETE",
    path: "/api/assistant/threads/{threadId}/messages",
    tags: ["assistant"],
    summary: "Delete messages",
  },
  "assistant.deleteThread": {
    method: "DELETE",
    path: "/api/assistant/threads/{threadId}",
    tags: ["assistant"],
    summary: "Delete thread",
  },
  "assistant.discoverModels": {
    method: "GET",
    path: "/api/assistant/models",
    tags: ["assistant"],
    summary: "Discover models",
  },
  "assistant.getAdminConfiguration": {
    method: "GET",
    path: "/api/assistant/configuration",
    tags: ["assistant"],
    summary: "Get admin configuration",
  },
  "assistant.getAvailability": {
    method: "GET",
    path: "/api/assistant/availability",
    tags: ["assistant"],
    summary: "Get availability",
  },
  "assistant.getContextEntities": {
    method: "GET",
    path: "/api/assistant/context-entities",
    tags: ["assistant"],
    summary: "Get context entities",
  },
  "assistant.getGenerationTelemetry": {
    method: "GET",
    path: "/api/assistant/threads/{threadId}/messages/{messageId}/telemetry",
    tags: ["assistant"],
    summary: "Get generation telemetry",
  },
  "assistant.getModelCapabilities": {
    method: "GET",
    path: "/api/assistant/models/capabilities",
    tags: ["assistant"],
    summary: "Get model capabilities",
  },
  "assistant.getRuntimeOptions": {
    method: "GET",
    path: "/api/assistant/runtime-options",
    tags: ["assistant"],
    summary: "Get runtime options",
  },
  "assistant.getThread": {
    method: "GET",
    path: "/api/assistant/threads/{threadId}",
    tags: ["assistant"],
    summary: "Get thread",
  },
  "assistant.listThreads": {
    method: "GET",
    path: "/api/assistant/threads",
    tags: ["assistant"],
    summary: "List threads",
  },
  "assistant.renameThread": {
    method: "PATCH",
    path: "/api/assistant/threads/{threadId}/name",
    tags: ["assistant"],
    summary: "Rename thread",
  },
  "assistant.submitFeedback": {
    method: "POST",
    path: "/api/assistant/feedback",
    tags: ["assistant"],
    summary: "Submit feedback",
  },
  "assistant.updateConfiguration": {
    method: "PATCH",
    path: "/api/assistant/configuration",
    tags: ["assistant"],
    summary: "Update configuration",
  },
  "assistant.updateConnection": {
    method: "PUT",
    path: "/api/assistant/connection",
    tags: ["assistant"],
    summary: "Update connection",
  },
  "assistant.updateThreadModel": {
    method: "PATCH",
    path: "/api/assistant/threads/{threadId}/model",
    tags: ["assistant"],
    summary: "Update thread model",
  },
  "bangs.search": { public: true, method: "GET", path: "/api/search/bangs", tags: ["bangs"], summary: "Search" },
  "board.getBoardByName": {
    public: true,
    method: "GET",
    path: "/api/boards/by-name/{name}",
    tags: ["board"],
    summary: "Get board by name",
  },
  "board.getBoardSettings": {
    method: "GET",
    path: "/api/boards/{id}/settings",
    tags: ["board"],
    summary: "Get board settings",
  },
  "board.getHomeBoard": {
    public: true,
    method: "GET",
    path: "/api/boards/home",
    tags: ["board"],
    summary: "Get home board",
  },
  "board.resetLayout": {
    method: "POST",
    path: "/api/boards/{boardId}/layouts/{layoutId}/reset",
    tags: ["board"],
    summary: "Reset layout",
  },
  "board.saveBoard": { method: "PUT", path: "/api/boards/{id}/composition", tags: ["board"], summary: "Save board" },
  "board.search": { public: true, method: "GET", path: "/api/boards/search", tags: ["board"], summary: "Search" },
  "certificates.removeCertificate": {
    method: "DELETE",
    path: "/api/certificates/{fileName}",
    tags: ["certificates"],
    summary: "Remove certificate",
    description:
      "Remove certificate. Requires admin permission. All native validation and resource authorization apply.",
  },
  "certificates.removeTrustedHostname": {
    method: "DELETE",
    path: "/api/certificates/trusted-hostnames/{hostname}/{thumbprint}",
    tags: ["certificates"],
    summary: "Remove trusted hostname",
    description:
      "Remove trusted hostname. Requires admin permission. All native validation and resource authorization apply.",
  },
  "certificates.trustHostnameMismatch": {
    method: "POST",
    path: "/api/certificates/trusted-hostnames",
    tags: ["certificates"],
    summary: "Trust hostname mismatch",
    description:
      "Trust hostname mismatch. Requires admin permission. All native validation and resource authorization apply.",
  },
  "cronJobs.disableJob": {
    method: "POST",
    path: "/api/cron-jobs/{name}/disable",
    tags: ["cron-jobs"],
    summary: "Disable job",
    description: "Disable job. Requires admin permission. All native validation and resource authorization apply.",
    inputKey: "name",
  },
  "cronJobs.enableJob": {
    method: "POST",
    path: "/api/cron-jobs/{name}/enable",
    tags: ["cron-jobs"],
    summary: "Enable job",
    description: "Enable job. Requires admin permission. All native validation and resource authorization apply.",
    inputKey: "name",
  },
  "cronJobs.getJobs": {
    method: "GET",
    path: "/api/cron-jobs",
    tags: ["cron-jobs"],
    summary: "Get jobs",
    description: "Get jobs. Requires admin permission. All native validation and resource authorization apply.",
  },
  "cronJobs.startJob": {
    method: "POST",
    path: "/api/cron-jobs/{name}/start",
    tags: ["cron-jobs"],
    summary: "Start job",
    description: "Start job. Requires admin permission. All native validation and resource authorization apply.",
    inputKey: "name",
  },
  "cronJobs.stopJob": {
    method: "POST",
    path: "/api/cron-jobs/{name}/stop",
    tags: ["cron-jobs"],
    summary: "Stop job",
    description: "Stop job. Requires admin permission. All native validation and resource authorization apply.",
    inputKey: "name",
  },
  "cronJobs.triggerJob": {
    method: "POST",
    path: "/api/cron-jobs/{name}/trigger",
    tags: ["cron-jobs"],
    summary: "Trigger job",
    description: "Trigger job. Requires admin permission. All native validation and resource authorization apply.",
    inputKey: "name",
  },
  "cronJobs.updateJobInterval": {
    method: "PATCH",
    path: "/api/cron-jobs/{name}/interval",
    tags: ["cron-jobs"],
    summary: "Update job interval",
    description:
      "Update job interval. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.available": {
    method: "GET",
    path: "/api/custom-widgets/actions/available",
    tags: ["custom-widget"],
    summary: "Available",
    description: "Available. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.configurationRequestUser": {
    method: "POST",
    path: "/api/custom-widgets/actions/configuration-request-user",
    tags: ["custom-widget"],
    summary: "Configuration request user",
    description:
      "Configuration request user. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.create": {
    method: "POST",
    path: "/api/custom-widgets/definitions",
    tags: ["custom-widget"],
    summary: "Create",
    description: "Create. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.createFromPreview": {
    method: "POST",
    path: "/api/custom-widgets/actions/create-from-preview",
    tags: ["custom-widget"],
    summary: "Create from preview",
    description:
      "Create from preview. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.delete": {
    method: "DELETE",
    path: "/api/custom-widgets/definitions/{id}",
    tags: ["custom-widget"],
    summary: "Delete",
    description: "Delete. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.duplicate": {
    method: "POST",
    path: "/api/custom-widgets/definitions/{id}/duplicate",
    tags: ["custom-widget"],
    summary: "Duplicate",
    description: "Duplicate. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.export": {
    method: "GET",
    path: "/api/custom-widgets/definitions/{id}/export",
    tags: ["custom-widget"],
    summary: "Export",
    description: "Export. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.exportLegacy": {
    method: "GET",
    path: "/api/custom-widgets/legacy/{id}/export",
    tags: ["custom-widget"],
    summary: "Export legacy",
    description: "Export legacy. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.findComponents": {
    method: "GET",
    path: "/api/custom-widgets/actions/find-components",
    tags: ["custom-widget"],
    summary: "Find components",
    description: "Find components. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.get": {
    method: "GET",
    path: "/api/custom-widgets/definitions/{id}",
    tags: ["custom-widget"],
    summary: "Get",
    description: "Get. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.getAuthoringPrompt": {
    method: "GET",
    path: "/api/custom-widgets/actions/get-authoring-prompt",
    tags: ["custom-widget"],
    summary: "Get authoring prompt",
    description:
      "Get authoring prompt. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.getComponent": {
    method: "GET",
    path: "/api/custom-widgets/actions/get-component",
    tags: ["custom-widget"],
    summary: "Get component",
    description: "Get component. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.getComponentCatalog": {
    method: "GET",
    path: "/api/custom-widgets/actions/get-component-catalog",
    tags: ["custom-widget"],
    summary: "Get component catalog",
    description:
      "Get component catalog. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.getComponents": {
    method: "GET",
    path: "/api/custom-widgets/actions/get-components",
    tags: ["custom-widget"],
    summary: "Get components",
    description: "Get components. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.getExample": {
    method: "GET",
    path: "/api/custom-widgets/actions/get-example",
    tags: ["custom-widget"],
    summary: "Get example",
    description: "Get example. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.getReference": {
    method: "GET",
    path: "/api/custom-widgets/actions/get-reference",
    tags: ["custom-widget"],
    summary: "Get reference",
    description: "Get reference. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.getSharedProps": {
    method: "GET",
    path: "/api/custom-widgets/actions/get-shared-props",
    tags: ["custom-widget"],
    summary: "Get shared props",
    description: "Get shared props. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.getSkill": {
    method: "GET",
    path: "/api/custom-widgets/actions/get-skill",
    tags: ["custom-widget"],
    summary: "Get skill",
    description: "Get skill. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.import": {
    method: "POST",
    path: "/api/custom-widgets/definitions/import",
    tags: ["custom-widget"],
    summary: "Import",
    description: "Import. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.list": {
    method: "GET",
    path: "/api/custom-widgets/definitions",
    tags: ["custom-widget"],
    summary: "List",
    description: "List. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.migrateLegacy": {
    method: "POST",
    path: "/api/custom-widgets/actions/migrate-legacy",
    tags: ["custom-widget"],
    summary: "Migrate legacy",
    description: "Migrate legacy. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.optionRequest": {
    method: "GET",
    path: "/api/custom-widgets/actions/option-request",
    tags: ["custom-widget"],
    summary: "Option request",
    description: "Option request. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.previewAction": {
    method: "POST",
    path: "/api/custom-widgets/actions/preview-action",
    tags: ["custom-widget"],
    summary: "Preview action",
    description: "Preview action. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.previewCreate": {
    method: "POST",
    path: "/api/custom-widgets/actions/preview-create",
    tags: ["custom-widget"],
    summary: "Preview create",
    description: "Preview create. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.previewGet": {
    method: "GET",
    path: "/api/custom-widgets/actions/preview-get",
    tags: ["custom-widget"],
    summary: "Preview get",
    description: "Preview get. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.previewJournal": {
    method: "GET",
    path: "/api/custom-widgets/actions/preview-journal",
    tags: ["custom-widget"],
    summary: "Preview journal",
    description: "Preview journal. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.previewQuery": {
    method: "GET",
    path: "/api/custom-widgets/actions/preview-query",
    tags: ["custom-widget"],
    summary: "Preview query",
    description: "Preview query. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.previewRefresh": {
    method: "POST",
    path: "/api/custom-widgets/actions/preview-refresh",
    tags: ["custom-widget"],
    summary: "Preview refresh",
    description: "Preview refresh. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.previewReviseTemplate": {
    method: "POST",
    path: "/api/custom-widgets/actions/preview-revise-template",
    tags: ["custom-widget"],
    summary: "Preview revise template",
    description:
      "Preview revise template. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.readTemplate": {
    method: "GET",
    path: "/api/custom-widgets/definitions/{id}/template",
    tags: ["custom-widget"],
    summary: "Read template",
    description: "Read template. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.schema": {
    method: "GET",
    path: "/api/custom-widgets/actions/schema",
    tags: ["custom-widget"],
    summary: "Schema",
    description: "Schema. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.secretClear": {
    method: "DELETE",
    path: "/api/custom-widgets/definitions/{definitionId}/secrets/{sourceId}/{kind}",
    tags: ["custom-widget"],
    summary: "Secret clear",
    description: "Secret clear. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.secretSet": {
    method: "PUT",
    path: "/api/custom-widgets/definitions/{definitionId}/secrets",
    tags: ["custom-widget"],
    summary: "Secret set",
    description: "Secret set. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.setPreviewLiveActions": {
    method: "POST",
    path: "/api/custom-widgets/actions/set-preview-live-actions",
    tags: ["custom-widget"],
    summary: "Set preview live actions",
    description:
      "Set preview live actions. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.sourceConfigure": {
    method: "POST",
    path: "/api/custom-widgets/actions/source-configure",
    tags: ["custom-widget"],
    summary: "Source configure",
    description: "Source configure. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.templatePatch": {
    method: "PATCH",
    path: "/api/custom-widgets/definitions/{id}/template",
    tags: ["custom-widget"],
    summary: "Template patch",
    description: "Template patch. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.toggleEnabled": {
    method: "PATCH",
    path: "/api/custom-widgets/definitions/{id}/enabled",
    tags: ["custom-widget"],
    summary: "Toggle enabled",
    description: "Toggle enabled. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.update": {
    method: "PATCH",
    path: "/api/custom-widgets/definitions/{id}",
    tags: ["custom-widget"],
    summary: "Update",
    description: "Update. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.updateFromPreview": {
    method: "POST",
    path: "/api/custom-widgets/actions/update-from-preview",
    tags: ["custom-widget"],
    summary: "Update from preview",
    description:
      "Update from preview. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.validate": {
    method: "GET",
    path: "/api/custom-widgets/actions/validate",
    tags: ["custom-widget"],
    summary: "Validate",
    description: "Validate. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.validateTemplate": {
    method: "GET",
    path: "/api/custom-widgets/actions/validate-template",
    tags: ["custom-widget"],
    summary: "Validate template",
    description:
      "Validate template. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.workshopGet": {
    method: "GET",
    path: "/api/custom-widgets/workshop/{submissionId}",
    tags: ["custom-widget"],
    summary: "Workshop get",
    description: "Workshop get. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.workshopInstall": {
    method: "POST",
    path: "/api/custom-widgets/workshop/{submissionId}/install",
    tags: ["custom-widget"],
    summary: "Workshop install",
    description: "Workshop install. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.workshopSearch": {
    method: "GET",
    path: "/api/custom-widgets/workshop",
    tags: ["custom-widget"],
    summary: "Workshop search",
    description: "Workshop search. Requires admin permission. All native validation and resource authorization apply.",
  },
  "customWidget.writeTemplate": {
    method: "PUT",
    path: "/api/custom-widgets/definitions/{id}/template",
    tags: ["custom-widget"],
    summary: "Write template",
    description: "Write template. Requires admin permission. All native validation and resource authorization apply.",
  },
  "docker.getContainers": {
    method: "GET",
    path: "/api/docker/containers",
    tags: ["docker"],
    summary: "Get containers",
    description: "Get containers. Requires admin permission. All native validation and resource authorization apply.",
  },
  "docker.getEndpoints": {
    method: "GET",
    path: "/api/docker/endpoints",
    tags: ["docker"],
    summary: "Get endpoints",
    description: "Get endpoints. Requires admin permission. All native validation and resource authorization apply.",
  },
  "docker.getServiceHealth": {
    method: "GET",
    path: "/api/docker/health",
    tags: ["docker"],
    summary: "Get service health",
    description:
      "Get service health. Requires admin permission. All native validation and resource authorization apply.",
  },
  "docker.logs": {
    method: "GET",
    path: "/api/docker/endpoints/{endpointId}/containers/{id}/logs",
    tags: ["docker"],
    summary: "Logs",
    description: "Logs. Requires admin permission. All native validation and resource authorization apply.",
  },
  "docker.reconcileServices": {
    method: "GET",
    path: "/api/docker/reconciliation",
    tags: ["docker"],
    summary: "Reconcile services",
    description:
      "Reconcile services. Requires admin permission. All native validation and resource authorization apply.",
  },
  "docker.refreshInventory": {
    method: "POST",
    path: "/api/docker/inventory/refresh",
    tags: ["docker"],
    summary: "Refresh inventory",
    description:
      "Refresh inventory. Requires admin permission. All native validation and resource authorization apply.",
  },
  "docker.removeAll": {
    method: "POST",
    path: "/api/docker/containers/remove",
    tags: ["docker"],
    summary: "Remove all",
    description: "Remove all. Requires admin permission. All native validation and resource authorization apply.",
  },
  "docker.restartAll": {
    method: "POST",
    path: "/api/docker/containers/restart",
    tags: ["docker"],
    summary: "Restart all",
    description: "Restart all. Requires admin permission. All native validation and resource authorization apply.",
  },
  "docker.startAll": {
    method: "POST",
    path: "/api/docker/containers/start",
    tags: ["docker"],
    summary: "Start all",
    description: "Start all. Requires admin permission. All native validation and resource authorization apply.",
  },
  "docker.stopAll": {
    method: "POST",
    path: "/api/docker/containers/stop",
    tags: ["docker"],
    summary: "Stop all",
    description: "Stop all. Requires admin permission. All native validation and resource authorization apply.",
  },
  "group.getPaginated": {
    method: "GET",
    path: "/api/groups/paginated",
    tags: ["group"],
    summary: "Get paginated",
    description: "Get paginated. Requires admin permission. All native validation and resource authorization apply.",
  },
  "group.savePartialSettings": {
    method: "PATCH",
    path: "/api/groups/{id}/settings",
    tags: ["group"],
    summary: "Save partial settings",
    description:
      "Save partial settings. Requires admin permission. All native validation and resource authorization apply.",
  },
  "group.savePositions": {
    method: "PUT",
    path: "/api/groups/positions",
    tags: ["group"],
    summary: "Save positions",
    description: "Save positions. Requires admin permission. All native validation and resource authorization apply.",
  },
  "group.selectable": { method: "GET", path: "/api/groups/selectable", tags: ["group"], summary: "Selectable" },
  "group.transferOwnership": {
    method: "PUT",
    path: "/api/groups/{groupId}/owner",
    tags: ["group"],
    summary: "Transfer ownership",
    description:
      "Transfer ownership. Requires admin permission. All native validation and resource authorization apply.",
  },
  "home.getStats": {
    public: true,
    method: "GET",
    path: "/api/instance/statistics",
    tags: ["home"],
    summary: "Get stats",
  },
  "icon.findIcons": { public: true, method: "GET", path: "/api/icons", tags: ["icon"], summary: "Find icons" },
  "integration.getIntegrationPermissions": {
    method: "GET",
    path: "/api/integrations/{id}/permissions",
    tags: ["integration"],
    summary: "Get integration permissions",
  },
  "integration.getMediaRequestOptions": {
    method: "GET",
    path: "/api/integrations/media-request-options",
    tags: ["integration"],
    summary: "Get media request options",
  },
  "integration.mediaRequestSearchTargets": {
    method: "GET",
    path: "/api/integrations/media-request-targets",
    tags: ["integration"],
    summary: "Media request search targets",
  },
  "integration.requestMedia": {
    method: "POST",
    path: "/api/integrations/media-requests",
    tags: ["integration"],
    summary: "Request media",
  },
  "integration.saveGroupIntegrationPermissions": {
    method: "PUT",
    path: "/api/integrations/{entityId}/permissions/groups",
    tags: ["integration"],
    summary: "Save group integration permissions",
  },
  "integration.saveUserIntegrationPermissions": {
    method: "PUT",
    path: "/api/integrations/{entityId}/permissions/users",
    tags: ["integration"],
    summary: "Save user integration permissions",
  },
  "integration.search": { method: "GET", path: "/api/integrations/search", tags: ["integration"], summary: "Search" },
  "integration.searchInIntegration": {
    method: "GET",
    path: "/api/integrations/{integrationId}/search",
    tags: ["integration"],
    summary: "Search in integration",
  },
  "integration.searchMediaRequests": {
    method: "GET",
    path: "/api/integrations/media-requests/search",
    tags: ["integration"],
    summary: "Search media requests",
  },
  "kubernetes.cluster.getCluster": {
    method: "GET",
    path: "/api/kubernetes/cluster",
    tags: ["kubernetes"],
    summary: "Get cluster",
    description: "Get cluster. Requires admin permission. All native validation and resource authorization apply.",
  },
  "kubernetes.cluster.getClusterResourceCounts": {
    method: "GET",
    path: "/api/kubernetes/cluster/resource-counts",
    tags: ["kubernetes"],
    summary: "Get cluster resource counts",
    description:
      "Get cluster resource counts. Requires admin permission. All native validation and resource authorization apply.",
  },
  "kubernetes.configMaps.getConfigMaps": {
    method: "GET",
    path: "/api/kubernetes/config-maps",
    tags: ["kubernetes"],
    summary: "Get config maps",
    description: "Get config maps. Requires admin permission. All native validation and resource authorization apply.",
  },
  "kubernetes.contexts.getContexts": {
    method: "GET",
    path: "/api/kubernetes/contexts",
    tags: ["kubernetes"],
    summary: "Get contexts",
    description: "Get contexts. Requires admin permission. All native validation and resource authorization apply.",
  },
  "kubernetes.ingresses.getIngresses": {
    method: "GET",
    path: "/api/kubernetes/ingresses",
    tags: ["kubernetes"],
    summary: "Get ingresses",
    description: "Get ingresses. Requires admin permission. All native validation and resource authorization apply.",
  },
  "kubernetes.namespaces.getNamespaces": {
    method: "GET",
    path: "/api/kubernetes/namespaces",
    tags: ["kubernetes"],
    summary: "Get namespaces",
    description: "Get namespaces. Requires admin permission. All native validation and resource authorization apply.",
  },
  "kubernetes.nodes.getNodes": {
    method: "GET",
    path: "/api/kubernetes/nodes",
    tags: ["kubernetes"],
    summary: "Get nodes",
    description: "Get nodes. Requires admin permission. All native validation and resource authorization apply.",
  },
  "kubernetes.pods.getPods": {
    method: "GET",
    path: "/api/kubernetes/pods",
    tags: ["kubernetes"],
    summary: "Get pods",
    description: "Get pods. Requires admin permission. All native validation and resource authorization apply.",
  },
  "kubernetes.secrets.getSecrets": {
    method: "GET",
    path: "/api/kubernetes/secrets",
    tags: ["kubernetes"],
    summary: "Get secrets",
    description: "Get secrets. Requires admin permission. All native validation and resource authorization apply.",
  },
  "kubernetes.services.getServices": {
    method: "GET",
    path: "/api/kubernetes/services",
    tags: ["kubernetes"],
    summary: "Get services",
    description: "Get services. Requires admin permission. All native validation and resource authorization apply.",
  },
  "kubernetes.volumes.getVolumes": {
    method: "GET",
    path: "/api/kubernetes/volumes",
    tags: ["kubernetes"],
    summary: "Get volumes",
    description: "Get volumes. Requires admin permission. All native validation and resource authorization apply.",
  },
  "location.searchCity": {
    public: true,
    method: "GET",
    path: "/api/locations/cities",
    tags: ["location"],
    summary: "Search city",
  },
  "media.deleteMedia": { method: "DELETE", path: "/api/media/{id}", tags: ["media"], summary: "Delete media" },
  "media.getPaginated": { method: "GET", path: "/api/media", tags: ["media"], summary: "Get paginated" },
  "searchEngine.getDefaultSearchEngine": {
    public: true,
    method: "GET",
    path: "/api/search-engines/default",
    tags: ["search-engine"],
    summary: "Get default search engine",
  },
  "searchEngine.search": {
    public: true,
    method: "GET",
    path: "/api/search-engines/search",
    tags: ["search-engine"],
    summary: "Search",
  },
  "section.changeCollapsed": {
    method: "PATCH",
    path: "/api/sections/{sectionId}/collapsed",
    tags: ["section"],
    summary: "Change collapsed",
  },
  "serverSettings.getBranding": {
    public: true,
    method: "GET",
    path: "/api/settings/branding",
    tags: ["server-settings"],
    summary: "Get branding",
  },
  "serverSettings.getCulture": {
    public: true,
    method: "GET",
    path: "/api/settings/culture",
    tags: ["server-settings"],
    summary: "Get culture",
  },
  "updateChecker.getAvailableUpdates": {
    method: "GET",
    path: "/api/updates",
    tags: ["update-checker"],
    summary: "Get available updates",
    description:
      "Get available updates. Requires admin permission. All native validation and resource authorization apply.",
  },
  "user.changeByteUnitSystem": {
    method: "PATCH",
    path: "/api/users/{id}/preferences/byte-unit-system",
    tags: ["user"],
    summary: "Change byte unit system",
  },
  "user.changePingIconsEnabled": {
    method: "PATCH",
    path: "/api/users/{id}/preferences/ping-icons",
    tags: ["user"],
    summary: "Change ping icons enabled",
  },
  "widget.airQuality.atLocation": {
    public: true,
    method: "GET",
    path: "/api/widgets/air-quality/at-location",
    tags: ["widget"],
    summary: "At location",
  },
  "widget.anchorNotes.getNote": {
    public: true,
    method: "GET",
    path: "/api/widgets/anchor-notes/note",
    tags: ["widget"],
    summary: "Get note",
  },
  "widget.anchorNotes.listNotes": {
    public: true,
    method: "GET",
    path: "/api/widgets/anchor-notes/list-notes",
    tags: ["widget"],
    summary: "List notes",
  },
  "widget.anchorNotes.updateNote": {
    method: "POST",
    path: "/api/widgets/anchor-notes/update-note",
    tags: ["widget"],
    summary: "Update note",
  },
  "widget.app.ping": { public: true, method: "GET", path: "/api/widgets/app/ping", tags: ["widget"], summary: "Ping" },
  "widget.archiveTeamWarrior.getStatus": {
    public: true,
    method: "GET",
    path: "/api/widgets/archive-team-warrior/status",
    tags: ["widget"],
    summary: "Get status",
  },
  "widget.audioStats.getStats": {
    public: true,
    method: "GET",
    path: "/api/widgets/audio-stats/stats",
    tags: ["widget"],
    summary: "Get stats",
  },
  "widget.bazarr.getBadges": {
    public: true,
    method: "GET",
    path: "/api/widgets/bazarr/badges",
    tags: ["widget"],
    summary: "Get badges",
  },
  "widget.beszel.getAlerts": {
    public: true,
    method: "GET",
    path: "/api/widgets/beszel/alerts",
    tags: ["widget"],
    summary: "Get alerts",
  },
  "widget.beszel.getSystemStats": {
    public: true,
    method: "GET",
    path: "/api/widgets/beszel/system-stats",
    tags: ["widget"],
    summary: "Get system stats",
  },
  "widget.beszel.getSystems": {
    public: true,
    method: "GET",
    path: "/api/widgets/beszel/systems",
    tags: ["widget"],
    summary: "Get systems",
  },
  "widget.calendar.findAllEvents": {
    public: true,
    method: "GET",
    path: "/api/widgets/calendar/find-all-events",
    tags: ["widget"],
    summary: "Find all events",
  },
  "widget.coolify.getInstancesInfo": {
    public: true,
    method: "GET",
    path: "/api/widgets/coolify/instances-info",
    tags: ["widget"],
    summary: "Get instances info",
  },
  "widget.customApi.executeAction": {
    method: "POST",
    path: "/api/widgets/custom-api/execute-action",
    tags: ["widget"],
    summary: "Execute action",
  },
  "widget.customApi.getData": {
    public: true,
    method: "GET",
    path: "/api/widgets/custom-api/data",
    tags: ["widget"],
    summary: "Get data",
  },
  "widget.customApi.queryRequest": {
    public: true,
    method: "GET",
    path: "/api/widgets/custom-api/query-request",
    tags: ["widget"],
    summary: "Query request",
  },
  "widget.customApi.refresh": {
    public: true,
    method: "POST",
    path: "/api/widgets/custom-api/refresh",
    tags: ["widget"],
    summary: "Refresh",
  },
  "widget.dnsHole.disable": {
    method: "POST",
    path: "/api/widgets/dns-hole/disable",
    tags: ["widget"],
    summary: "Disable",
  },
  "widget.dnsHole.enable": {
    method: "POST",
    path: "/api/widgets/dns-hole/enable",
    tags: ["widget"],
    summary: "Enable",
  },
  "widget.dnsHole.summary": {
    public: true,
    method: "GET",
    path: "/api/widgets/dns-hole/summary",
    tags: ["widget"],
    summary: "Summary",
  },
  "widget.downloads.deleteItem": {
    method: "POST",
    path: "/api/widgets/downloads/delete-item",
    tags: ["widget"],
    summary: "Delete item",
  },
  "widget.downloads.getJobsAndStatuses": {
    public: true,
    method: "GET",
    path: "/api/widgets/downloads/jobs-and-statuses",
    tags: ["widget"],
    summary: "Get jobs and statuses",
  },
  "widget.downloads.pause": {
    method: "POST",
    path: "/api/widgets/downloads/pause",
    tags: ["widget"],
    summary: "Pause",
  },
  "widget.downloads.pauseItem": {
    method: "POST",
    path: "/api/widgets/downloads/pause-item",
    tags: ["widget"],
    summary: "Pause item",
  },
  "widget.downloads.resume": {
    method: "POST",
    path: "/api/widgets/downloads/resume",
    tags: ["widget"],
    summary: "Resume",
  },
  "widget.downloads.resumeItem": {
    method: "POST",
    path: "/api/widgets/downloads/resume-item",
    tags: ["widget"],
    summary: "Resume item",
  },
  "widget.firewall.getFirewallCpuStatus": {
    method: "GET",
    path: "/api/widgets/firewall/firewall-cpu-status",
    tags: ["widget"],
    summary: "Get firewall cpu status",
  },
  "widget.firewall.getFirewallInterfacesStatus": {
    method: "GET",
    path: "/api/widgets/firewall/firewall-interfaces-status",
    tags: ["widget"],
    summary: "Get firewall interfaces status",
  },
  "widget.firewall.getFirewallMemoryStatus": {
    method: "GET",
    path: "/api/widgets/firewall/firewall-memory-status",
    tags: ["widget"],
    summary: "Get firewall memory status",
  },
  "widget.firewall.getFirewallVersionStatus": {
    method: "GET",
    path: "/api/widgets/firewall/firewall-version-status",
    tags: ["widget"],
    summary: "Get firewall version status",
  },
  "widget.healthMonitoring.getClusterHealthStatus": {
    public: true,
    method: "GET",
    path: "/api/widgets/health-monitoring/cluster-health-status",
    tags: ["widget"],
    summary: "Get cluster health status",
  },
  "widget.healthMonitoring.getSystemHealthStatus": {
    public: true,
    method: "GET",
    path: "/api/widgets/health-monitoring/system-health-status",
    tags: ["widget"],
    summary: "Get system health status",
  },
  "widget.healthMonitoring.listStorageVolumes": {
    public: true,
    method: "GET",
    path: "/api/widgets/health-monitoring/list-storage-volumes",
    tags: ["widget"],
    summary: "List storage volumes",
  },
  "widget.immich.getAlbum": {
    public: true,
    method: "GET",
    path: "/api/widgets/immich/album",
    tags: ["widget"],
    summary: "Get album",
  },
  "widget.immich.getAlbumPreview": {
    public: true,
    method: "GET",
    path: "/api/widgets/immich/album-preview",
    tags: ["widget"],
    summary: "Get album preview",
  },
  "widget.immich.getAlbums": {
    public: true,
    method: "GET",
    path: "/api/widgets/immich/albums",
    tags: ["widget"],
    summary: "Get albums",
  },
  "widget.immich.getServerStats": {
    public: true,
    method: "GET",
    path: "/api/widgets/immich/server-stats",
    tags: ["widget"],
    summary: "Get server stats",
  },
  "widget.indexerManager.getIndexersStatus": {
    public: true,
    method: "GET",
    path: "/api/widgets/indexer-manager/indexers-status",
    tags: ["widget"],
    summary: "Get indexers status",
  },
  "widget.indexerManager.testAllIndexers": {
    method: "POST",
    path: "/api/widgets/indexer-manager/test-all-indexers",
    tags: ["widget"],
    summary: "Test all indexers",
  },
  "widget.llamacpp.getStats": {
    public: true,
    method: "GET",
    path: "/api/widgets/llamacpp/stats",
    tags: ["widget"],
    summary: "Get stats",
  },
  "widget.mediaOrganizer.getData": {
    public: true,
    method: "GET",
    path: "/api/widgets/media-organizer/data",
    tags: ["widget"],
    summary: "Get data",
  },
  "widget.mediaRelease.getMediaReleases": {
    public: true,
    method: "GET",
    path: "/api/widgets/media-release/media-releases",
    tags: ["widget"],
    summary: "Get media releases",
  },
  "widget.mediaRequests.answerRequest": {
    method: "POST",
    path: "/api/widgets/media-requests/answer-request",
    tags: ["widget"],
    summary: "Answer request",
  },
  "widget.mediaRequests.getLatestRequests": {
    public: true,
    method: "GET",
    path: "/api/widgets/media-requests/latest-requests",
    tags: ["widget"],
    summary: "Get latest requests",
  },
  "widget.mediaRequests.getStats": {
    public: true,
    method: "GET",
    path: "/api/widgets/media-requests/stats",
    tags: ["widget"],
    summary: "Get stats",
  },
  "widget.mediaServer.getCurrentStreams": {
    public: true,
    method: "GET",
    path: "/api/widgets/media-server/current-streams",
    tags: ["widget"],
    summary: "Get current streams",
  },
  "widget.mediaTranscoding.getDataAsync": {
    public: true,
    method: "GET",
    path: "/api/widgets/media-transcoding/data-async",
    tags: ["widget"],
    summary: "Get data async",
  },
  "widget.minecraft.getServerStatus": {
    public: true,
    method: "GET",
    path: "/api/widgets/minecraft/server-status",
    tags: ["widget"],
    summary: "Get server status",
  },
  "widget.networkController.summary": {
    public: true,
    method: "GET",
    path: "/api/widgets/network-controller/summary",
    tags: ["widget"],
    summary: "Summary",
  },
  "widget.notebook.updateContent": {
    method: "POST",
    path: "/api/widgets/notebook/update-content",
    tags: ["widget"],
    summary: "Update content",
  },
  "widget.notifications.deleteNotification": {
    method: "POST",
    path: "/api/widgets/notifications/delete-notification",
    tags: ["widget"],
    summary: "Delete notification",
  },
  "widget.notifications.getNotifications": {
    public: true,
    method: "GET",
    path: "/api/widgets/notifications/notifications",
    tags: ["widget"],
    summary: "Get notifications",
  },
  "widget.options.getWidgetOptionSettings": {
    public: true,
    method: "GET",
    path: "/api/widgets/options/widget-option-settings",
    tags: ["widget"],
    summary: "Get widget option settings",
  },
  "widget.options.saveItemOptions": {
    method: "POST",
    path: "/api/widgets/options/save-item-options",
    tags: ["widget"],
    summary: "Save item options",
  },
  "widget.paperlessNgx.getStats": {
    public: true,
    method: "GET",
    path: "/api/widgets/paperless-ngx/stats",
    tags: ["widget"],
    summary: "Get stats",
  },
  "widget.patchmon.getStats": {
    method: "GET",
    path: "/api/widgets/patchmon/stats",
    tags: ["widget"],
    summary: "Get stats",
  },
  "widget.releases.getLatest": {
    public: true,
    method: "GET",
    path: "/api/widgets/releases/latest",
    tags: ["widget"],
    summary: "Get latest",
  },
  "widget.rssFeed.getFeeds": {
    public: true,
    method: "GET",
    path: "/api/widgets/rss-feed/feeds",
    tags: ["widget"],
    summary: "Get feeds",
  },
  "widget.secrets.deleteSecret": {
    method: "POST",
    path: "/api/widgets/secrets/delete-secret",
    tags: ["widget"],
    summary: "Delete secret",
  },
  "widget.secrets.getConfiguredKinds": {
    method: "GET",
    path: "/api/widgets/secrets/configured-kinds",
    tags: ["widget"],
    summary: "Get configured kinds",
  },
  "widget.secrets.setSecret": {
    method: "POST",
    path: "/api/widgets/secrets/set-secret",
    tags: ["widget"],
    summary: "Set secret",
  },
  "widget.smartHome.entityDetails": {
    public: true,
    method: "GET",
    path: "/api/widgets/smart-home/entity-details",
    tags: ["widget"],
    summary: "Entity details",
  },
  "widget.smartHome.entityState": {
    public: true,
    method: "GET",
    path: "/api/widgets/smart-home/entity-state",
    tags: ["widget"],
    summary: "Entity state",
  },
  "widget.smartHome.executeAutomation": {
    method: "POST",
    path: "/api/widgets/smart-home/execute-automation",
    tags: ["widget"],
    summary: "Execute automation",
  },
  "widget.smartHome.switchEntity": {
    method: "POST",
    path: "/api/widgets/smart-home/switch-entity",
    tags: ["widget"],
    summary: "Switch entity",
  },
  "widget.speedtestTracker.getDashboard": {
    public: true,
    method: "GET",
    path: "/api/widgets/speedtest-tracker/dashboard",
    tags: ["widget"],
    summary: "Get dashboard",
  },
  "widget.stats.catalog": {
    public: true,
    method: "GET",
    path: "/api/widgets/stats/catalog",
    tags: ["widget"],
    summary: "Catalog",
  },
  "widget.stats.refresh": {
    public: true,
    method: "POST",
    path: "/api/widgets/stats/refresh",
    tags: ["widget"],
    summary: "Refresh",
  },
  "widget.stats.snapshot": {
    public: true,
    method: "GET",
    path: "/api/widgets/stats/snapshot",
    tags: ["widget"],
    summary: "Snapshot",
  },
  "widget.stockPrice.getPriceHistory": {
    public: true,
    method: "GET",
    path: "/api/widgets/stock-price/price-history",
    tags: ["widget"],
    summary: "Get price history",
  },
  "widget.timetable.getTimetable": {
    public: true,
    method: "GET",
    path: "/api/widgets/timetable/timetable",
    tags: ["widget"],
    summary: "Get timetable",
  },
  "widget.timetable.searchStations": {
    public: true,
    method: "GET",
    path: "/api/widgets/timetable/search-stations",
    tags: ["widget"],
    summary: "Search stations",
  },
  "widget.tracearr.getDashboard": {
    public: true,
    method: "GET",
    path: "/api/widgets/tracearr/dashboard",
    tags: ["widget"],
    summary: "Get dashboard",
  },
  "widget.traefik.getDashboard": {
    public: true,
    method: "GET",
    path: "/api/widgets/traefik/dashboard",
    tags: ["widget"],
    summary: "Get dashboard",
  },
  "widget.umami.getActiveVisitors": {
    public: true,
    method: "GET",
    path: "/api/widgets/umami/active-visitors",
    tags: ["widget"],
    summary: "Get active visitors",
  },
  "widget.umami.getEventNames": {
    public: true,
    method: "GET",
    path: "/api/widgets/umami/event-names",
    tags: ["widget"],
    summary: "Get event names",
  },
  "widget.umami.getMultiEventTimeSeries": {
    public: true,
    method: "GET",
    path: "/api/widgets/umami/multi-event-time-series",
    tags: ["widget"],
    summary: "Get multi event time series",
  },
  "widget.umami.getTopPages": {
    public: true,
    method: "GET",
    path: "/api/widgets/umami/top-pages",
    tags: ["widget"],
    summary: "Get top pages",
  },
  "widget.umami.getTopReferrers": {
    public: true,
    method: "GET",
    path: "/api/widgets/umami/top-referrers",
    tags: ["widget"],
    summary: "Get top referrers",
  },
  "widget.umami.getVisitorStats": {
    public: true,
    method: "GET",
    path: "/api/widgets/umami/visitor-stats",
    tags: ["widget"],
    summary: "Get visitor stats",
  },
  "widget.umami.getWebsites": {
    public: true,
    method: "GET",
    path: "/api/widgets/umami/websites",
    tags: ["widget"],
    summary: "Get websites",
  },
  "widget.ups.getSummaries": {
    public: true,
    method: "GET",
    path: "/api/widgets/ups/summaries",
    tags: ["widget"],
    summary: "Get summaries",
  },
  "widget.uptimeKuma.getDashboard": {
    public: true,
    method: "GET",
    path: "/api/widgets/uptime-kuma/dashboard",
    tags: ["widget"],
    summary: "Get dashboard",
  },
  "widget.vpn.getSummaries": {
    public: true,
    method: "GET",
    path: "/api/widgets/vpn/summaries",
    tags: ["widget"],
    summary: "Get summaries",
  },
  "widget.wazuh.getAgents": {
    method: "GET",
    path: "/api/widgets/wazuh/agents",
    tags: ["widget"],
    summary: "Get agents",
  },
  "widget.wazuh.getAlerts": {
    method: "GET",
    path: "/api/widgets/wazuh/alerts",
    tags: ["widget"],
    summary: "Get alerts",
  },
  "widget.wazuh.getAuthFailures": {
    method: "GET",
    path: "/api/widgets/wazuh/auth-failures",
    tags: ["widget"],
    summary: "Get auth failures",
  },
  "widget.wazuh.getFim": { method: "GET", path: "/api/widgets/wazuh/fim", tags: ["widget"], summary: "Get fim" },
  "widget.wazuh.getSummary": {
    method: "GET",
    path: "/api/widgets/wazuh/summary",
    tags: ["widget"],
    summary: "Get summary",
  },
  "widget.wazuh.getTimeline": {
    method: "GET",
    path: "/api/widgets/wazuh/timeline",
    tags: ["widget"],
    summary: "Get timeline",
  },
  "widget.wazuh.getTopList": {
    method: "GET",
    path: "/api/widgets/wazuh/top-list",
    tags: ["widget"],
    summary: "Get top list",
  },
  "widget.wazuh.getVulnerabilities": {
    method: "GET",
    path: "/api/widgets/wazuh/vulnerabilities",
    tags: ["widget"],
    summary: "Get vulnerabilities",
  },
  "widget.weather.atLocation": {
    public: true,
    method: "GET",
    path: "/api/widgets/weather/at-location",
    tags: ["widget"],
    summary: "At location",
  },
  "widget.wud.getStats": {
    public: true,
    method: "GET",
    path: "/api/widgets/wud/stats",
    tags: ["widget"],
    summary: "Get stats",
  },
} satisfies Record<keyof typeof restSources, RestRoute>;
