# This template is heavily inspired by the Next.js's template:
# See here: https://github.com/vercel/next.js/blob/canary/.github/ISSUE_TEMPLATE/3.feature_request.yml

name: 📕 Documentation Request
description: Request something that should be documented or improved in the documentation.
title: "documentation: "
body:
  - type: textarea
    attributes:
      label: Describe what you would like to see documented
      description: Please describe the request as clear and concise as possible. Remember to add context as to why you believe this documentation is needed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Add any other information related to the documentation request here. If your documentation request is related to any issues or discussions, link them here.

