name: 🐞 Documentation Bug Report
description: Report that something is wrong, not working or could be improved in the documentation.
title: "documentation: bug: "
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug, as well as what you expected to happen when encountering it.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Add any other information related to the bug here, screenshots if applicable.
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: If relevant, what browser do you use?
      options:
        - Firefox
        - Edge (Chromium)
        - Edge (Proprietary)
        - Chrome
        - Safari
        - Vivaldi
        - Brave
        - Samsung Internet
        - Other (describe in "additional information")
      default: 0
    validations:
      required: false

