name: "Execute E2E Tests"
description: "Composite action used for execution in workflows/e2e-trigger.yml"
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build
      id: build-docker-image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        context: .
        push: false
        tags: homarr-e2e
        network: host
      env:
        SKIP_ENV_VALIDATION: true

    - name: Run E2E Tests
      shell: bash
      run: |
        echo "Here we would run them with testcontainers"
