const {chromium}=require('/tmp/bunx-1000-@playwright/mcp@0.0.79/node_modules/playwright');const fs=require('fs');
(async()=>{
const b=await chromium.launch({headless:true,executablePath:'/home/habs/.cache/ms-playwright/chromium-1228/chrome-linux64/chrome',args:['--no-sandbox']});
const p=await b.newPage({viewport:{width:1920,height:1080}});p.setDefaultTimeout(15000);console.log('Browser launched');await p.addInitScript(()=>{window.__timelines={}});const errors=[];p.on('pageerror',e=>errors.push(e.message));const base='http://100.111.30.70:3019/impact-direct/';
await p.goto(base+'intro/');await p.waitForFunction(()=>document.fonts.status==='loaded');
const intro=await p.evaluate(()=>{document.getElementById('root').style.cssText='width:1920px;height:1080px';const tl=window.__timelines['workshop-intro'];const seen=new Set();const tiles=[...document.querySelectorAll('.all-item')];for(let t=.65;t<=4.61;t+=.1){tl.seek(t);for(const e of tiles){const r=e.getBoundingClientRect();if(r.x>=0&&r.right<=1920&&r.y>=0&&r.bottom<=1080)seen.add(e.innerText);}}tl.seek(1);const positions=[...document.querySelectorAll('.curtain-content')].map(e=>e.getBoundingClientRect().y);tl.seek(4);const directions=[...document.querySelectorAll('.curtain-content')].map((e,i)=>e.getBoundingClientRect().y-positions[i]);tl.seek(7.2);const left=document.querySelector('.curtain-left').getBoundingClientRect(),right=document.querySelector('.curtain-right').getBoundingClientRect();return{count:tiles.length,seen:[...seen].sort(),directions,leftRight:left.right,rightLeft:right.left,footerY:document.querySelector('.integrations-heading').getBoundingClientRect().y,total:document.querySelector('.integrations-heading').innerText,hasBottomMarquee:!!document.querySelector('.marquees'),hasSlogan:document.body.innerText.includes('Missing a widget'),missing:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)};});
const expected=JSON.parse(fs.readFileSync(__dirname+'/opening-integrations.json')).map(i=>i.name).sort();
if(intro.count!==87||JSON.stringify(intro.seen)!==JSON.stringify(expected)||intro.directions.some((d,i)=>i%2?d<=0:d>=0)||intro.leftRight>0||intro.rightLeft<1920||intro.footerY<990||!intro.total.startsWith('87 INTEGRATIONS')||intro.hasBottomMarquee||intro.hasSlogan||intro.missing.length)throw Error(JSON.stringify(intro));
console.log('Verified all 87 integrations, left-up/right-down scroll and completed center reveal.');
for(const t of [0,2,5.9,7.2]){await p.evaluate(t=>{window.__timelines['workshop-intro'].seek(t)},t);}
const sourceChecks=[];
for(const scene of ['workshop','integrations','custom','assistant','statistics','header','ending']){console.log('Source:',scene);await p.goto(base+scene+'/');await p.waitForFunction(()=>document.fonts.status==='loaded');const r=await p.evaluate(()=>({text:document.body.innerText,duration:Number(document.getElementById('root').dataset.duration),missing:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)}));if(/Missing a widget|What would you build|social experiment|Put your header to work|super-fast|ultimate (homarr )?update/i.test(r.text)||r.missing.length)throw Error(scene+JSON.stringify(r));if(scene==='ending'&&r.duration!==7)throw Error('Outro is not 7 seconds');sourceChecks.push({scene,duration:r.duration});}
await p.goto(base+'custom/');await p.evaluate(()=>{document.getElementById('root').style.cssText='width:1920px;height:1080px';window.__timelines.custom.seek(2)});const crop=await p.locator('.custom-running').evaluate(e=>{const panel=e.getBoundingClientRect(),im=e.querySelector('img'),r=im.getBoundingClientRect();return{panelWidth:panel.width,panelHeight:panel.height,sourceWidth:im.naturalWidth,imageWidth:r.width,overflow:getComputedStyle(e).overflow}});if(crop.panelWidth!==760||crop.imageWidth<2000||crop.overflow!=='hidden')throw Error(JSON.stringify(crop));
fs.writeFileSync(__dirname+'/source-verification.json',JSON.stringify({intro,crop,sourceChecks,errors},null,2));console.log({crop,errors});await b.close();})().catch(e=>{console.error(e);process.exit(1)});