"""Workshop-first release cut, with real header/Statistics captures and labeled concepts."""
from pathlib import Path
import json,re,shutil,html
R=Path(__file__).parent;O=R/'impact-ultimate'
css='''
@font-face{font-family:Inter;src:url(assets/inter.woff2)}*{box-sizing:border-box}body{margin:0;background:#141418;color:#fff;font-family:Inter,sans-serif}#root{width:100%;height:100%;position:relative;overflow:hidden;background:radial-gradient(ellipse at 68% 40%,#3d2433,#141418 75%)}
.clip{position:absolute;inset:0;overflow:hidden}.grid{position:absolute;inset:0;background-image:linear-gradient(#ffffff07 1px,transparent 1px),linear-gradient(90deg,#ffffff07 1px,transparent 1px);background-size:80px 80px}.brand{position:absolute;right:65px;top:20px;width:125px;height:92px;object-fit:contain;z-index:9}.kicker{position:absolute;left:70px;top:48px;color:#ff9eae;font-size:23px;letter-spacing:3px}.heading{position:absolute;left:70px;top:126px;font-size:79px;line-height:1.08;font-weight:780;letter-spacing:-3px;width:1760px}.sub{position:absolute;left:75px;top:235px;width:1760px;font-size:32px;line-height:1.4;color:#e4d7e1}.panel{position:absolute;background:#24242b;border:2px solid #8d6b84;border-radius:24px;overflow:hidden;box-shadow:0 25px 75px #0008}.panel img{width:100%;height:100%;object-fit:contain}.pill{color:#ff9eae;border:1px solid #7b586e;padding:12px 20px;border-radius:12px;background:#302330;font-size:24px}.note{position:absolute;font-size:26px;line-height:1.5;color:#e2d0dd}.progress{position:absolute;bottom:0;height:4px;width:100%;background:#ff779d;transform-origin:left}
.workshop-shot{left:70px;top:380px;width:1200px;height:666px}.workshop-copy{position:absolute;left:1330px;top:395px;width:490px}.workshop-copy h2{font-size:52px;line-height:1.2;margin:0 0 30px;letter-spacing:-1px}.workshop-copy p{font-size:29px;line-height:1.5;color:#e7d2df;margin:18px 0}.category{display:block;font-size:36px;padding:21px 0;border-bottom:1px solid #77576c}
.custom-quote{font-size:33px;max-width:1700px}.custom-editor{left:75px;top:390px;width:980px;height:590px}.custom-running{left:1020px;top:505px;width:825px;height:410px;border-color:#ff779d}.custom-chip{position:absolute;right:92px;top:944px}.custom-ideas{position:absolute;inset:0;background:radial-gradient(ellipse at 65% 45%,#402739,#141418 75%)}
.ideas{position:absolute;left:75px;top:390px;display:flex;gap:28px}.idea{width:570px;height:525px;background:#24242b;border:1px solid #8d6b84;border-radius:22px;padding:29px;box-shadow:0 25px 65px #0005}.idea .tag{color:#ff9eae;font-size:17px;letter-spacing:2px}.idea h2{font-size:34px;letter-spacing:-1px;margin:18px 0}.idea .value{font-size:75px;font-weight:750;color:#a1ffcc;margin-top:30px}.idea .detail{font-size:23px;color:#e3ccda;line-height:1.6}.bars{height:110px;display:flex;align-items:flex-end;gap:12px;margin-top:24px}.bars i{display:block;background:#ff779d;width:34px;border-radius:6px 6px 0 0}.meter{height:12px;background:#534050;border-radius:10px;overflow:hidden;margin:32px 0}.meter i{display:block;height:100%;width:68%;background:#8ce9ff}.release{font-size:23px;padding:15px 0;border-bottom:1px solid #534050;display:flex;justify-content:space-between}.release b{color:#a1ffcc}.idea-foot{position:absolute;left:80px;top:956px;font-size:26px;color:#d9c4d4}
.stats-main{left:75px;top:370px;width:1100px;height:520px}.stats-rows{left:1210px;top:465px;width:630px;height:315px;border-color:#ff779d}.stats-note{left:90px;top:935px}.preview-tag{position:absolute;right:90px;top:930px}
.integration-grid{position:absolute;left:75px;top:398px;display:grid;grid-template-columns:repeat(8,207px);gap:16px}.integration-cell{height:137px;background:#26232b;border:1px solid #695264;border-radius:16px;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:12px}.integration-cell img{width:56px;height:56px;object-fit:contain}.integration-cell:nth-child(5) img,.integration-cell:nth-child(8) img,.integration-cell:nth-child(25) img{filter:invert(1)}.integration-cell span{font-size:20px;text-align:center}.integration-foot{left:75px;top:1010px;font-size:21px}
.agent-shot{left:75px;top:368px;width:970px;height:590px;opacity:.65}.agent-actions{left:160px;top:416px;width:885px;height:212px}.agent-prompt{left:100px;top:724px;width:945px;height:154px;border-color:#ff779d}.provider{position:absolute;left:1120px;top:375px;width:700px;padding:32px;border:2px solid #a87a9c;border-radius:24px;background:#28222c}.provider h2{font-size:43px;margin:0 0 22px;letter-spacing:-1px}.provider blockquote{font-size:38px;color:#ff9eae;margin:0 0 24px;line-height:1.25}.provider p{font-size:25px;line-height:1.5;color:#e8d5e2}.allowance{font-size:25px;border-top:1px solid #77576c;padding-top:21px;margin-top:20px;color:#a1ffcc}.provider small{font-size:19px;line-height:1.4;display:block;color:#d6bbce;margin-top:12px}
.header-full{left:75px;top:405px;width:1770px;height:130px;border-color:#ff779d}.header-groups{position:absolute;left:75px;top:620px;display:flex;gap:35px}.header-group{width:566px;background:#26232b;border:1px solid #795d72;border-radius:22px;overflow:hidden;padding:25px}.header-group img{width:510px;height:104px;object-fit:contain;background:#242424;border-radius:12px}.header-group h2{font-size:34px;margin:29px 0 15px}.header-group p{font-size:25px;line-height:1.4;color:#e8d5e2}.header-note{left:80px;top:987px;font-size:25px}
.ending-logo{position:absolute;left:605px;top:90px;width:710px;height:510px;object-fit:contain;z-index:5;filter:drop-shadow(0 8px 40px #0008)}.ending-title{position:absolute;left:0;top:655px;width:100%;text-align:center;font-size:88px;font-weight:800;letter-spacing:-3px;z-index:8;text-shadow:0 3px 25px #141418}.ending-sub{position:absolute;left:0;top:782px;width:100%;text-align:center;font-size:37px;color:#e6cfdf;z-index:8}.halo{position:absolute;left:590px;top:95px;width:740px;height:740px;border:2px solid #ff779d;border-radius:50%;opacity:.2}.confetti{position:absolute;inset:0;width:1920px;height:1080px;z-index:7;pointer-events:none}
'''
def project(name,duration,content,extra='',base=True):
 p=O/name;p.mkdir(parents=True,exist_ok=True)
 for f in ['package.json','hyperframes.json']:shutil.copy(R/'impact-intro/composition'/f,p/f)
 if not(p/'assets').exists():(p/'assets').symlink_to('../../composition/assets',target_is_directory=True)
 decorations='<div class="grid"></div><img class="brand" src="assets/homarr-wordmark-light.svg">'
 if not base:decorations='<div class="grid"></div>'
 js="const tl=gsap.timeline({paused:true});"
 if base:
  js+="tl.fromTo('.heading',{y:25,opacity:0},{y:0,opacity:1,duration:.4,ease:'power3.out'},0);tl.fromTo('.sub',{y:15,opacity:0},{y:0,opacity:1,duration:.3},.15);"
  if 'class="panel ' in content:js+="tl.fromTo('.panel',{y:35,opacity:0},{y:0,opacity:1,duration:.45,stagger:.07,ease:'power3.out'},.15);"
 js+=extra+f"tl.fromTo('.progress',{{scaleX:0}},{{scaleX:1,duration:{duration},ease:'none'}},0);window.__timelines['{name}']=tl;"
 doc=f'<!doctype html><html><head><meta charset="utf-8"><title>{name}</title><script src="assets/gsap.min.js"></script><style>{css}</style></head><body><div id="root" data-composition-id="{name}" data-width="1920" data-height="1080" data-duration="{duration}"><section id="{name}-scene" class="clip" data-start="0" data-duration="{duration}" data-track-index="0">{decorations}{content}<div class="progress"></div></section></div><script>{js}</script></body></html>'
 (p/'index.html').write_text(doc)
def title(k,t,sub):return f'<div class="kicker">{k}</div><div class="heading">{t}</div><div class="sub">{sub}</div>'
def image(asset,cls):return f'<div class="panel {cls}"><img src="assets/{asset}"></div>'

project('workshop',7,title('WORKSHOP · THE BIG ONE','The ultimate Homarr update.','Share, download and use community Custom Widgets and Custom CSS.')+image('ultimate/workshop.png','workshop-shot')+'<div class="workshop-copy"><h2>Our biggest feature update. Ever.</h2><span class="category">Custom Widgets</span><span class="category">Custom CSS</span><p>Publish your creations. Install what the community builds.</p></div>',"tl.fromTo('.workshop-copy',{x:90,opacity:0},{x:0,opacity:1,duration:.5},.35);tl.to('.workshop-shot',{x:12,duration:5,ease:'sine.inOut'},1);")

ideas='<div class="custom-ideas">'+title('CUSTOM WIDGETS V2 · IDEAS','Almost anything.','If it has an API, imagine the view you want to build.')+'<div class="ideas">'
ideas+='<div class="idea"><div class="tag">CONCEPT · HOME ASSISTANT API</div><h2>Energy dashboard</h2><div class="value">2.4 kW</div><div class="detail">Solar production · household usage</div><div class="bars">'+''.join(f'<i style="height:{h}px"></i>' for h in [25,38,30,53,68,82,72,97,89,108])+'</div></div>'
ideas+='<div class="idea"><div class="tag">CONCEPT · OCTOPRINT API</div><h2>Print queue</h2><div class="value">68%</div><div class="detail">Enclosure bracket · 42 min remaining</div><div class="meter"><i></i></div><div class="detail">Nozzle 210°C · Bed 60°C</div></div>'
ideas+='<div class="idea"><div class="tag">CONCEPT · GITHUB API</div><h2>Release radar</h2><div class="release"><span>homarr</span><b>v2</b></div><div class="release"><span>your-server</span><b>Update ready</b></div><div class="release"><span>your-cli</span><b>Up to date</b></div><div class="detail" style="margin-top:30px">Follow only the projects you run.</div></div></div><div class="idea-foot">Illustrative concepts · Build your own, share it, or ask the agent.</div></div>'
custom='<div class="custom-first">'+title('CUSTOM WIDGETS V2 · BETA','Missing a widget?','You can now find it on the Workshop, build it yourself or get the Homarr agent to make it for you, for free!')+image('local-captures/workbench.png','custom-editor')+image('dashboard-cut/custom-dashboard.png','custom-running')+'<div class="pill custom-chip">JSX + API requests + actions</div></div>'+ideas
project('custom',12,custom,"tl.set('.custom-ideas',{opacity:0},0);tl.to('.custom-first',{opacity:0,duration:.18},6.6);tl.to('.custom-ideas',{opacity:1,duration:.18},6.8);tl.fromTo('.idea',{y:45},{y:0,duration:.45,stagger:.08,ease:'back.out(1.15)'},6.8);tl.fromTo('.meter i',{scaleX:.3},{scaleX:1,duration:3,ease:'power2.out'},7.2);")
project('statistics',6,title('STATISTICS · PR #6863 PREVIEW','Your metrics. Your layout.','Select fields from multiple integrations. Rename, reorder and choose cards, rows or grouped tables.')+image('ultimate/stats-cards.png','stats-main')+image('ultimate/stats-rows-focus.png','stats-rows')+'<div class="note stats-note">One widget. Multiple services.</div><div class="pill preview-tag">New Statistics widget</div>',"tl.to('.stats-rows',{y:-25,duration:2.5,ease:'sine.inOut'},1);tl.to('.stats-main',{x:16,duration:3,ease:'sine.inOut'},1);")
xs=json.loads((O/'new-integrations.json').read_text());assert len(xs)==32
grid='<div class="integration-grid">'+''.join(f'<div class="integration-cell"><img src="{x["asset"]}"><span>{html.escape(x["name"])}</span></div>' for x in xs)+'</div>'
project('integrations',8,title('32 NEW INTEGRATIONS · PR #6863 PREVIEW','More services to build with.','Basic statistics for now. Use these services as building blocks for your Custom Widgets.')+grid+'<div class="note integration-foot">32 new adapters · Initial metric coverage, not complete service interfaces.</div>',"tl.fromTo('.integration-cell',{scale:.85,opacity:0},{scale:1,opacity:1,duration:.35,stagger:.018,ease:'power3.out'},.2);")
provider='<div class="provider"><h2>Some AI usage. On us.</h2><blockquote>“Because I’m nice.”<div style="font-size:26px;margin-top:8px">— ajnart</div></blockquote><p>The Homarr provider is free, funded by Ajnart through site ad revenue.</p><div class="allowance">50 request units per UTC day</div><small>Tool loops can use several units. A shared service limit also applies.</small><p>Zero-data-retention providers.<br style="display:none"> No prompt or response logging.</p></div>'
provider=provider.replace('<br style="display:none">','')
project('assistant',8,title('HOMARR ASSISTANT','Homarr Assistant, with free AI.','Read live Homarr data, use tools and create Custom Widgets with the free Homarr provider.')+image('dashboard-cut/assistant-board.png','agent-shot')+image('dashboard-cut/assistant-actions.png','agent-actions')+image('dashboard-cut/assistant-prompt.png','agent-prompt')+provider,"tl.fromTo('.provider',{x:120,opacity:0},{x:0,opacity:1,duration:.55,ease:'power3.out'},.25);")
groups='<div class="header-groups">'
for asset,h,p in [('header-board.png','Links to your boards','Pin a board for direct access.'),('header-features.png','Access to features','Keep board switching and search close.'),('header-tools.png','Your controls, your order','Place Docker, theme and settings where you want them.')]:groups+=f'<div class="header-group"><img src="assets/ultimate/{asset}"><h2>{h}</h2><p>{p}</p></div>'
groups+='</div>'
project('header',7,title('HEADER CUSTOMIZATION','Put your header to work.','Add links to boards and shortcuts to features. Arrange them on the left, center or right.')+image('ultimate/header-custom.png','header-full')+groups+'<div class="note header-note">Keep the boards and controls you use within reach.</div>',"tl.fromTo('.header-group',{y:60,opacity:0},{y:0,opacity:1,duration:.45,stagger:.12,ease:'power3.out'},.4);")
ending='<div class="halo" data-layout-allow-overflow></div><img class="ending-logo" src="assets/homarr-wordmark-light.svg"><div class="ending-title">Homarr v2</div><div class="ending-sub">The ultimate Homarr update.</div><canvas id="confetti" class="confetti" width="1920" height="1080"></canvas>'
particles='''
const canvas=document.getElementById('confetti'),ctx=canvas.getContext('2d');
const rand=n=>{const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x)};
const colors=['#ff779d','#ffdd77','#a1ffcc','#8feaff','#c3a5ff','#ffffff'];
function draw(t){ctx.clearRect(0,0,1920,1080);for(let i=0;i<640;i++){let x,y;const r=rand(i+1),q=rand(i+911);if(i<360){x=r*2100-90+Math.sin(t*2+i)*55;y=((q*2100+t*(190+rand(i+22)*180))%1800)-450;}else{const side=i%2;const a=t-(i%3)*.36;const u=Math.max(0,a);const origin=side*1920;const speed=450+rand(i+13)*520;x=origin+(1-side*2)*speed*u;y=1070-(780+q*340)*u+240*u*u;if(a<0)continue;}ctx.save();ctx.translate(x,y);ctx.rotate(i+t*(2+r*5));ctx.fillStyle=colors[i%colors.length];ctx.globalAlpha=.85;ctx.fillRect(-5,-8,7+q*8,10+r*14);ctx.restore();}}
const clock={t:0};draw(0);tl.to(clock,{t:4,duration:4,ease:'none',onUpdate:()=>draw(clock.t)},0);
tl.fromTo('.ending-logo',{scale:.92},{scale:1,duration:.65,ease:'back.out(1.4)'},0);
tl.fromTo('.ending-title',{y:30,opacity:0},{y:0,opacity:1,duration:.4},.15);
tl.fromTo('.halo',{scale:.8},{scale:1.4,duration:4,ease:'sine.out'},0);
'''
project('ending',4,ending,particles,False)
# Preserve the complete first frame and slow motion of the previous intro.
p=O/'intro';p.mkdir(exist_ok=True)
for f in ['package.json','hyperframes.json']:shutil.copy(O/'workshop'/f,p/f)
if not(p/'assets').exists():(p/'assets').symlink_to('../../composition/assets',target_is_directory=True)
s=(R/'impact-widgets/intro/index.html').read_text().replace('impact-widgets-intro','ultimate-intro').replace('src="assets/logo.svg"','src="assets/homarr-wordmark-light.svg"').replace('.brand img{width:42px;height:42px}', '.brand img{width:130px;height:95px}').replace('HOMARR / VERSION 2','THE ULTIMATE UPDATE').replace('A closer look at what changed.','Our biggest feature update. Ever.')
s=s.replace('.brand{position:absolute;left:72px;top:56px', '.brand{position:absolute;left:62px;top:22px')
(p/'index.html').write_text(s)
chapters=[(0,'Intro'),(7,'Workshop'),(14,'Custom Widgets v2'),(20.8,'Widget ideas'),(26,'New drag-and-drop'),(30.5,'Cmd-click multi-select'),(36,'Containers'),(42,'Sidebar settings'),(45,'Fixed sidebar'),(50,'Advanced widgets'),(55,'New widgets'),(63,'Statistics'),(69,'32 new integrations'),(77,'Assistant + free AI'),(85,'Onboarding'),(90,'Customized header'),(97,'Board switcher'),(103,'Ending')]
(O/'storyboard.json').write_text(json.dumps(chapters,indent=2))
page=(R/'impact-widgets/index.html').read_text().replace('new widgets','the ultimate update').replace('76 seconds','107 seconds').replace('?v=8','?v=9').replace('../impact-intro/','../impact-widgets/')
page=re.sub(r'<p style="padding:14px.*?</p>','',page)
page=page.replace('A fully visible opening frame, a slower integration marquee, and a new chapter showing Air Quality, Countdown and Timer.','Workshop first, Custom Widgets and ideas, real Statistics and header captures, 32 new integrations, and the free Homarr AI provider.')
page=re.sub(r'<div><button.*?</div>','<div>'+''.join(f'<button onclick="const v=document.getElementById(\'film\');v.currentTime={t};v.play()">{label}</button>' for t,label in chapters)+'</div>',page)
page=page.replace('<details><summary>Capture notes</summary><p>','<details><summary>Capture notes</summary><p>Statistics and its 32 integrations are previewed from open PR #6863 at commit 0d78bac75f8b7b888b0146d48fee719963fd5fe2. Header configuration and Statistics were captured from that real local instance; the original header settings were restored. Workshop uses the catalog screenshot shipped with the release blog because the public Workshop URL was not yet available. Energy, print queue and release radar cards are labeled illustrative concepts. The free provider allowance is 50 request units per UTC day; tools can use multiple units and shared limits apply. ')
page=page.replace('Header studio uses a cropped release screenshot because the available local image predates that feature. ','')
(O/'index.html').write_text(page)
print('Built 8 revised scenes including intro; final cut 107 seconds')
