from pathlib import Path
import shutil
r=Path(__file__).parent;p=r/'short';p.mkdir(exist_ok=True)
for n in ['package.json','hyperframes.json']:shutil.copy(r/'composition'/n,p/n)
if not (p/'assets').exists():(p/'assets').symlink_to('../composition/assets',target_is_directory=True)
scenes=[]
def scene(id,t,d,content):scenes.append(f'<section id="{id}" class="clip" data-start="{t}" data-duration="{d}" data-track-index="1"><div class="inner">{content}</div></section>')
def shot(name,cls='shot'):return f'<img class="{cls}" src="assets/product/{name}.webp">'
scene('hero',0,3,shot('homarr-v2-dashboard')+'<div class="title"><img src="assets/logo.svg"><h1>Homarr <em>2.0</em></h1><p>Your dashboard. Reimagined.</p></div>')
scene('drag',3,6,'<div class="label">Make it yours.</div>')
widgets=['weather','timer','airQuality','downloads','calendar','countdown']
scene('widgets',9,4,'<div class="label">Real widgets. Your world.</div><div class="row row-a">'+''.join(f'<img src="assets/real-widgets/{w}.png">' for w in widgets[:3])+'</div><div class="row row-b">'+''.join(f'<img src="assets/real-widgets/{w}.png">' for w in widgets[3:])+'</div>')
logos=sorted((r/'composition/assets/integrations').glob('*'))
scene('integrations',13,3,'<div class="logo-wall">'+''.join(f'<div><img src="assets/integrations/{x.name}"></div>' for x in logos if x.suffix in ['.svg','.png','.webp'])+'</div><div class="center-copy"><h1>Bring it all together.</h1><p>55 integrations</p></div>')
scene('assistant',16,3,shot('assistant-control-surface')+'<div class="label">Meet your Assistant.</div>')
scene('workbench',19,4,shot('custom-widget-workbench')+'<div class="side-copy"><span>Custom widgets</span><h1>Build it.<br>Preview it.<br>Make it yours.</h1></div>')
scene('workshop',23,4,shot('community-workshop')+'<div class="label">Made by the community.</div>')
scene('end',27,3,'<div class="closing"><img src="assets/logo.svg"><h1>Homarr 2.0</h1><p>Your dashboard. Your possibilities.</p><b>homarr.dev</b></div>')
css='''@font-face{font-family:Inter;src:url(assets/inter.woff2)}*{box-sizing:border-box}body{margin:0;font-family:Inter,sans-serif;color:#fff;background:#202020}#root{width:100%;height:100%;overflow:hidden;position:relative}.clip,.inner{position:absolute;inset:0;overflow:hidden}.inner{background:#202020}.shot{position:absolute;width:1920px;height:1200px;object-fit:cover;left:0;top:0}.title{width:850px;position:absolute;left:70px;bottom:65px;padding:28px 38px;background:#202020f5;border-left:7px solid #fa5252;border-radius:16px;box-shadow:0 20px 60px #0008}.title img{width:74px;float:left;margin:0 24px 0 0}h1{font-size:76px;line-height:1.08;letter-spacing:-3px;margin:0;font-weight:700}em{font-style:normal;color:#ff8787}p{font-size:30px;color:#ddd;margin:15px 0 0}.label{position:absolute;left:70px;top:45px;font-size:48px;font-weight:650;padding:17px 26px;background:#202020f5;border-radius:14px;z-index:3;letter-spacing:-1px}#drag .inner{background:transparent}#drag{z-index:3}.drag-video{position:absolute;left:0;top:140px;width:1920px;height:940px;object-fit:contain;background:#202020}.row{position:absolute;display:flex;gap:24px;left:-80px;width:max-content}.row img{width:640px;height:426px;object-fit:contain;border-radius:20px;box-shadow:0 18px 40px #0008}.row-a{top:162px}.row-b{top:620px;left:-240px}.logo-wall{display:grid;grid-template-columns:repeat(11,130px);gap:28px;position:absolute;left:100px;top:30px;transform:rotate(-7deg);opacity:.55}.logo-wall div{height:154px;background:#353535;border-radius:26px;display:flex;align-items:center;justify-content:center}.logo-wall img{width:80px;height:80px;object-fit:contain}.center-copy{position:absolute;inset:0;display:flex;flex-direction:column;justify-content:center;align-items:center;background:radial-gradient(ellipse,#202020f5 15%,#20202055 65%,transparent)}.center-copy h1{font-size:100px}.center-copy p{color:#ff8787;font-size:45px}#assistant .shot{width:1920px;height:auto;top:-65px}#assistant .label{top:auto;bottom:45px}#workbench .shot{width:1160px;height:auto;left:735px;top:15px}.side-copy{position:absolute;left:70px;top:340px;width:620px}.side-copy span{color:#ff8787;font-size:28px}.side-copy h1{margin-top:25px;font-size:82px}#workshop .shot{width:1920px;height:auto;top:-40px}#workshop .label{top:auto;bottom:45px}.closing{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;flex-direction:column}.closing img{width:160px;margin-bottom:30px}.closing h1{font-size:110px}.closing b{font-size:30px;color:#ff8787;margin-top:35px}.progress{position:absolute;bottom:0;left:0;width:100%;height:5px;background:#fa5252;z-index:8;transform-origin:left}'''
js='''const tl=gsap.timeline({paused:true});window.__timelines=window.__timelines||{};
tl.fromTo('#hero .shot',{scale:1.13,x:-45,y:-35},{scale:1,x:0,y:0,duration:3,ease:'power2.out'},0);
tl.fromTo('.title',{y:45},{y:0,duration:.6,ease:'power3.out'},0);
tl.fromTo('.row-a',{x:140},{x:-130,duration:4,ease:'none'},9);tl.fromTo('.row-b',{x:-110},{x:160,duration:4,ease:'none'},9);
tl.fromTo('.logo-wall',{scale:1.2,y:100},{scale:1,y:-70,duration:3,ease:'power2.out'},13);
tl.fromTo('.center-copy',{opacity:0,scale:.92},{opacity:1,scale:1,duration:.45},13.15);
tl.fromTo('#assistant .shot',{scale:1,x:0},{scale:1.18,x:-150,duration:3,ease:'power2.inOut'},16);
tl.fromTo('#workbench .shot',{y:70,scale:.93},{y:0,scale:1,duration:.6,ease:'power3.out'},19);
tl.to('#workbench .shot',{scale:1.14,x:-70,y:-65,duration:1.4,ease:'power2.inOut'},21);
tl.fromTo('#workshop .shot',{scale:1,x:0,y:0},{scale:1.18,x:-35,y:-90,duration:4,ease:'power2.inOut'},23);
tl.fromTo('.closing',{scale:.9,opacity:0},{scale:1,opacity:1,duration:.55,ease:'power3.out'},27);
tl.fromTo('.progress',{scaleX:0},{scaleX:1,duration:30,ease:'none'},0);window.__timelines['homarr-short']=tl;'''
(p/'index.html').write_text('<!DOCTYPE html><html><head><meta charset="utf-8"><title>Homarr 2.0 — 30 second product cut</title><script src="assets/gsap.min.js"></script><style>'+css+'</style></head><body><div id="root" data-composition-id="homarr-short" data-width="1920" data-height="1080" data-duration="30"><video id="drag-recording" class="clip drag-video" src="assets/drag.mp4" data-start="3" data-duration="6" data-track-index="0" muted playsinline></video>'+''.join(scenes)+'<audio id="music" src="assets/music-short.mp3" data-start="0" data-duration="30" data-track-index="4" data-volume="0.65"></audio><div class="progress"></div></div><script>'+js+'</script></body></html>')
