"""Workshop-first release cut, with real header/Statistics captures and labeled concepts."""
from pathlib import Path
import json,re,shutil,html
R=Path(__file__).parent;O=R/'impact-workshop'
css='''
@font-face{font-family:Inter;src:url(assets/inter.woff2)}*{box-sizing:border-box}body{margin:0;background:#141418;color:#fff;font-family:Inter,sans-serif}#root{width:100%;height:100%;position:relative;overflow:hidden;background:radial-gradient(ellipse at 68% 40%,#3d2433,#141418 75%)}
.clip{position:absolute;inset:0;overflow:hidden}.grid{position:absolute;inset:0;background-image:linear-gradient(#ffffff07 1px,transparent 1px),linear-gradient(90deg,#ffffff07 1px,transparent 1px);background-size:80px 80px}.brand{position:absolute;right:65px;top:20px;width:125px;height:92px;object-fit:contain;z-index:9}.kicker{position:absolute;left:70px;top:48px;color:#ff9eae;font-size:23px;letter-spacing:3px}.heading{position:absolute;left:70px;top:126px;font-size:79px;line-height:1.08;font-weight:780;letter-spacing:-3px;width:1760px}.sub{position:absolute;left:75px;top:235px;width:1760px;font-size:32px;line-height:1.4;color:#e4d7e1}.panel{position:absolute;background:#24242b;border:2px solid #8d6b84;border-radius:24px;overflow:hidden;box-shadow:0 25px 75px #0008}.panel img{width:100%;height:100%;object-fit:contain}.pill{color:#ff9eae;border:1px solid #7b586e;padding:12px 20px;border-radius:12px;background:#302330;font-size:24px}.note{position:absolute;font-size:26px;line-height:1.5;color:#e2d0dd}.progress{position:absolute;bottom:0;height:4px;width:100%;background:#ff779d;transform-origin:left}
.workshop-shot{left:70px;top:380px;width:1200px;height:666px}.workshop-copy{position:absolute;left:1330px;top:395px;width:490px}.workshop-copy h2{font-size:52px;line-height:1.2;margin:0 0 30px;letter-spacing:-1px}.workshop-copy p{font-size:29px;line-height:1.5;color:#e7d2df;margin:18px 0}.category{display:block;font-size:36px;padding:21px 0;border-bottom:1px solid #77576c}
.custom-quote{font-size:33px;max-width:1700px}.custom-editor{left:75px;top:390px;width:980px;height:590px}.custom-running{left:1020px;top:505px;width:825px;height:410px;border-color:#ff779d}.custom-chip{position:absolute;right:92px;top:944px}.custom-ideas{position:absolute;inset:0;background:radial-gradient(ellipse at 65% 45%,#402739,#141418 75%)}
.ideas{position:absolute;left:75px;top:390px;display:flex;gap:28px}.idea{width:570px;height:525px;background:#24242b;border:1px solid #8d6b84;border-radius:22px;padding:29px;box-shadow:0 25px 65px #0005}.idea .tag{color:#ff9eae;font-size:17px;letter-spacing:2px}.idea h2{font-size:34px;letter-spacing:-1px;margin:18px 0}.idea .value{font-size:75px;font-weight:750;color:#a1ffcc;margin-top:30px}.idea .detail{font-size:23px;color:#e3ccda;line-height:1.6}.bars{height:110px;display:flex;align-items:flex-end;gap:12px;margin-top:24px}.bars i{display:block;background:#ff779d;width:34px;border-radius:6px 6px 0 0}.meter{height:12px;background:#534050;border-radius:10px;overflow:hidden;margin:32px 0}.meter i{display:block;height:100%;width:68%;background:#8ce9ff}.release{font-size:23px;padding:15px 0;border-bottom:1px solid #534050;display:flex;justify-content:space-between}.release b{color:#a1ffcc}.idea-foot{position:absolute;left:80px;top:956px;font-size:26px;color:#d9c4d4}
.stats-main{left:75px;top:370px;width:1100px;height:520px}.stats-rows{left:1210px;top:465px;width:630px;height:315px;border-color:#ff779d}.stats-note{left:90px;top:935px}.preview-tag{position:absolute;right:90px;top:930px}
.integration-grid{position:absolute;left:75px;top:398px;display:grid;grid-template-columns:repeat(8,207px);gap:16px}.integration-cell{height:137px;background:#26232b;border:1px solid #695264;border-radius:16px;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:12px}.integration-cell img{width:56px;height:56px;object-fit:contain}.integration-cell:nth-child(5) img,.integration-cell:nth-child(8) img,.integration-cell:nth-child(25) img{filter:invert(1)}.integration-cell span{font-size:20px;text-align:center}.integration-foot{left:75px;top:1010px;font-size:21px}
.agent-shot{left:75px;top:368px;width:970px;height:590px;opacity:.65}.agent-actions{left:160px;top:416px;width:885px;height:212px}.agent-prompt{left:100px;top:724px;width:945px;height:154px;border-color:#ff779d}.provider{position:absolute;left:1120px;top:375px;width:700px;padding:32px;border:2px solid #a87a9c;border-radius:24px;background:#28222c}.provider h2{font-size:43px;margin:0 0 22px;letter-spacing:-1px}.provider blockquote{font-size:38px;color:#ff9eae;margin:0 0 24px;line-height:1.25}.provider p{font-size:25px;line-height:1.5;color:#e8d5e2}.allowance{font-size:25px;border-top:1px solid #77576c;padding-top:21px;margin-top:20px;color:#a1ffcc}.provider small{font-size:19px;line-height:1.4;display:block;color:#d6bbce;margin-top:12px}
.header-full{left:75px;top:405px;width:1770px;height:130px;border-color:#ff779d}.header-groups{position:absolute;left:75px;top:620px;display:flex;gap:35px}.header-group{width:566px;background:#26232b;border:1px solid #795d72;border-radius:22px;overflow:hidden;padding:25px}.header-group img{width:510px;height:104px;object-fit:contain;background:#242424;border-radius:12px}.header-group h2{font-size:34px;margin:29px 0 15px}.header-group p{font-size:25px;line-height:1.4;color:#e8d5e2}.header-note{left:80px;top:987px;font-size:25px}
.ending-logo{position:absolute;left:605px;top:90px;width:710px;height:510px;object-fit:contain;z-index:5;filter:drop-shadow(0 8px 40px #0008)}.ending-title{position:absolute;left:0;top:655px;width:100%;text-align:center;font-size:88px;font-weight:800;letter-spacing:-3px;z-index:8;text-shadow:0 3px 25px #141418}.ending-sub{position:absolute;left:0;top:782px;width:100%;text-align:center;font-size:37px;color:#e6cfdf;z-index:8}.halo{position:absolute;left:590px;top:95px;width:740px;height:740px;border:2px solid #ff779d;border-radius:50%;opacity:.2}.confetti{position:absolute;inset:0;width:1920px;height:1080px;z-index:7;pointer-events:none}
'''
css+='\n.integration-grid{top:350px;gap:14px 16px}.integration-cell{height:116px;gap:8px}.integration-cell img{width:48px;height:48px}.integration-foot{top:1022px}.data-flow{position:absolute;top:886px;left:75px;width:1767px;height:108px;display:flex;align-items:center;justify-content:center;gap:26px}.flow-node{font-size:29px;padding:20px 28px;background:#26232b;border:1px solid #95657f;border-radius:14px}.flow-wire{width:185px;height:3px;background:#483140}.flow-wire i{display:block;width:100%;height:3px;background:#ff779d;transform-origin:left}.flow-widget{color:#a1ffcc}.idea .value{font-size:64px}.inventory-rooms{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:24px 0}.inventory-rooms span{font-size:22px;background:#3c3040;border-radius:8px;padding:10px 16px;color:#8feaff}.bars i{transform-origin:bottom}.meter i{transform-origin:left}.provider{top:355px}.provider blockquote{font-size:32px;margin:25px 0;line-height:1.4}.provider h2{font-size:46px;margin:0}.provider p{margin:18px 0}.provider small{font-size:20px}.ending-logo{top:155px}.ending-title{top:715px}.ending-sub{top:842px}\n'
css+='\n.ending-logo{left:105px;top:300px;width:500px;height:380px}.ending-title{left:695px;top:210px;width:1130px;font-size:76px;line-height:1.12;text-align:left}.ending-prize{position:absolute;left:700px;top:440px;width:1080px;font-size:43px;line-height:1.4;color:#f1dce9;z-index:8}.ending-prize strong{color:#a1ffcc}.ending-thanks{position:absolute;left:700px;top:680px;width:1070px;font-size:34px;line-height:1.5;color:#e6cfdf;z-index:8}.ending-sub{left:700px;top:870px;width:1050px;text-align:left;font-size:35px;color:#ff9eae}.provider h2{font-size:40px}.statistics-shot{left:325px;top:315px;width:1270px;height:720px}.statistics-shot img{object-fit:cover;object-position:top;transform-origin:50% 20%}.widget-card{position:absolute;top:365px;width:560px;height:595px;border:1px solid #82677b;border-radius:24px;background:#24242b;padding:28px}.widget-card h2{margin:0;font-size:38px}.widget-card .widget-note{position:absolute;left:28px;right:28px;top:430px;font-size:27px;color:#e4d2df;line-height:1.4}.widget-card img{position:absolute;left:35px;top:142px;width:490px;height:258px;object-fit:contain}.wc-air{left:75px}.wc-count{left:680px}.wc-timer{left:1285px}.compact-timer{position:absolute;left:1320px;top:507px;width:490px;height:258px;object-fit:contain;border-radius:14px}.widget-card .widget-type{font-size:20px;color:#ff9eae;position:absolute;left:30px;top:89px}\n'
def project(name,duration,content,extra='',base=True):
 p=O/name;p.mkdir(parents=True,exist_ok=True)
 for f in ['package.json','hyperframes.json']:shutil.copy(R/'impact-intro/composition'/f,p/f)
 if not(p/'assets').exists():(p/'assets').symlink_to('../../composition/assets',target_is_directory=True)
 decorations='<div class="grid"></div><img class="brand" src="assets/homarr-wordmark-light.svg">'
 if not base:decorations='<div class="grid"></div>'
 js="const tl=gsap.timeline({paused:true});"
 if base:
  js+="tl.fromTo('.heading',{y:25,opacity:0},{y:0,opacity:1,duration:.4,ease:'power3.out'},0);tl.fromTo('.sub',{y:15,opacity:0},{y:0,opacity:1,duration:.3},.15);"
  if 'class="panel ' in content:js+="tl.fromTo('.panel',{y:35,opacity:0},{y:0,opacity:1,duration:.45,stagger:.07,ease:'power3.out'},.15);"
 js+=extra+f"tl.fromTo('.progress',{{scaleX:0}},{{scaleX:1,duration:{duration},ease:'none'}},0);window.__timelines['{name}']=tl;"
 doc=f'<!doctype html><html><head><meta charset="utf-8"><title>{name}</title><script src="assets/gsap.min.js"></script><style>{css}</style></head><body><div id="root" data-composition-id="{name}" data-width="1920" data-height="1080" data-duration="{duration}"><section id="{name}-scene" class="clip" data-start="0" data-duration="{duration}" data-track-index="0">{decorations}{content}<div class="progress"></div></section></div><script>{js}</script></body></html>'
 (p/'index.html').write_text(doc)
def title(k,t,sub):return f'<div class="kicker">{k}</div><div class="heading">{t}</div><div class="sub">{sub}</div>'
def image(asset,cls):return f'<div class="panel {cls}"><img src="assets/{asset}"></div>'

project('workshop',7,title('WORKSHOP · START HERE','Missing a widget?','Share, download and use community Custom Widgets and Custom CSS.')+image('ultimate/workshop.png','workshop-shot')+'<div class="workshop-copy"><h2>Find it on the Workshop.</h2><span class="category">Custom Widgets</span><span class="category">Custom CSS</span><p>Publish your creations. Install what the community builds.</p></div>',"tl.fromTo('.workshop-copy',{x:90,opacity:0},{x:0,opacity:1,duration:.5},.35);tl.to('.workshop-shot',{x:12,duration:5,ease:'sine.inOut'},1);")

ideas='<div class="custom-ideas">'+title('CUSTOM WIDGETS V2 · IDEAS','What would you build?','Turn service data into the view you want on your dashboard.')+'<div class="ideas">'
ideas+='<div class="idea"><div class="tag">CONCEPT · SPOOLMAN API</div><h2>Filament stock</h2><div class="value">1,000 g</div><div class="detail">Material, color and remaining filament</div><div class="bars">'+''.join(f'<i style="height:{h}px"></i>' for h in [25,38,30,53,68,82,72,97,89,108])+'</div></div>'
ideas+='<div class="idea"><div class="tag">CONCEPT · HOMEBOX API</div><h2>Home inventory</h2><div class="value">8 locations</div><div class="detail">Track items, labels and where you put them</div><div class="inventory-rooms"><span>Office</span><span>Garage</span><span>Kitchen</span><span>Workshop</span></div><div class="detail">Build the inventory view you need.</div></div>'
ideas+='<div class="idea"><div class="tag">CONCEPT · MEALIE API</div><h2>Meal planner</h2><div class="release"><span>Tonight</span><b>Ramen</b></div><div class="release"><span>Tomorrow</span><b>Curry</b></div><div class="release"><span>Shopping list</span><b>12 items</b></div><div class="detail" style="margin-top:30px">Recipes and plans, on your board.</div></div></div><div class="idea-foot">Illustrative concepts · Build your own, share it, or ask the agent.</div></div>'
custom='<div class="custom-first">'+title('CUSTOM WIDGETS V2 · BETA','Create it with Custom Widgets!','Use data from your services and their APIs. Build it yourself, or ask Homarr Assistant.')+image('local-captures/workbench.png','custom-editor')+image('dashboard-cut/custom-dashboard.png','custom-running')+'<div class="pill custom-chip">Service API → data → your widget</div></div>'+ideas
project('custom',12,custom,"tl.set('.custom-ideas',{opacity:0},0);tl.to('.custom-first',{opacity:0,duration:.18},6.6);tl.to('.custom-ideas',{opacity:1,duration:.18},6.8);tl.fromTo('.idea',{y:45},{y:0,duration:.45,stagger:.08,ease:'back.out(1.15)'},6.8);tl.fromTo('.bars i',{scaleY:.15},{scaleY:1,duration:1.2,stagger:.035,ease:'power2.out'},7.2);tl.fromTo('.inventory-rooms span',{y:12,opacity:0},{y:0,opacity:1,duration:.6,stagger:.1},7.2);")
xs=json.loads((R/'impact-ultimate/new-integrations.json').read_text());assert len(xs)==32
grid='<div class="integration-grid">'+''.join(f'<div class="integration-cell"><img src="{x["asset"]}"><span>{html.escape(x["name"])}</span></div>' for x in xs)+'</div>'
flow='<div class="data-flow"><div class="flow-node">Your service</div><div class="flow-wire"><i></i></div><div class="flow-node">Its data</div><div class="flow-wire"><i></i></div><div class="flow-node flow-widget">Your Custom Widget</div></div>'
project('integrations',10,title('32 NEW INTEGRATIONS · PR #6863 PREVIEW','32 new integrations.','More building blocks for your dashboard — and the Custom Widgets you create.')+grid+flow+'<div class="note integration-foot">Basic statistics for now. Build the views you are missing with Custom Widgets.</div>',"""
const cells=Array.from(document.querySelectorAll('.integration-cell'));
cells.forEach((cell,i)=>{const row=Math.floor(i/8),col=i%8;tl.fromTo(cell,{x:(3.5-col)*20,y:(1.5-row)*18,scale:.85,opacity:0},{x:0,y:0,scale:1,opacity:1,duration:1.15,ease:'power2.out'},.3+row*.22+col*.045);tl.fromTo(cell,{y:0},{y:-5,duration:2.2,repeat:2,yoyo:true,ease:'sine.inOut'},2.1+col*.07);});
tl.fromTo('.flow-node',{y:18,opacity:0},{y:0,opacity:1,duration:.7,stagger:.4},2.6);
tl.fromTo('.flow-wire i',{scaleX:0},{scaleX:1,duration:1.4,stagger:.75,ease:'power2.inOut'},3.1);
[23,10,11].forEach((i,n)=>{tl.to(cells[i],{backgroundColor:'#6c3857',scale:1.035,duration:.25},5.4+n*.75);tl.to(cells[i],{backgroundColor:'#26232b',scale:1,duration:.3},5.85+n*.75);});
tl.fromTo('.flow-widget',{backgroundColor:'#26232b'},{backgroundColor:'#503146',duration:1.1,repeat:3,yoyo:true,ease:'sine.inOut'},4.6);
""")
provider='<div class="provider"><h2>Create with Assistant.</h2><p>Bring your own API key, or let us cover your first requests.</p><div class="allowance">50 free requests per day. On us.</div><p>A social experiment, powered by the Homarr provider.</p><blockquote>“We’re not reviewing or reselling your slop, don’t worry.”</blockquote><small>50 request units per UTC day. Tool loops may use several; shared limits apply.</small><small>Homarr provider: no prompt or response logging. Your own provider has its own data policy.</small></div>'
project('assistant',10,title('HOMARR ASSISTANT','Your Custom Widget, fast. On us.','A super-fast, free way to create your Custom Widget: ask Homarr Assistant.')+image('dashboard-cut/assistant-board.png','agent-shot')+image('dashboard-cut/assistant-actions.png','agent-actions')+image('dashboard-cut/assistant-prompt.png','agent-prompt')+provider,"tl.fromTo('.provider',{x:120,opacity:0},{x:0,opacity:1,duration:.8,ease:'power3.out'},.25);tl.fromTo('.allowance',{y:15,opacity:0},{y:0,opacity:1,duration:.7},1.4);tl.fromTo('.provider blockquote',{y:15,opacity:0},{y:0,opacity:1,duration:.7},2.3);")
groups='<div class="header-groups">'
for asset,h,p in [('header-board.png','Links to your boards','Pin a board for direct access.'),('header-features.png','Access to features','Keep board switching and search close.'),('header-tools.png','Your controls, your order','Place Docker, theme and settings where you want them.')]:groups+=f'<div class="header-group"><img src="assets/ultimate/{asset}"><h2>{h}</h2><p>{p}</p></div>'
groups+='</div>'
project('header',7,title('HEADER CUSTOMIZATION','Put your header to work.','Add links to boards and shortcuts to features. Arrange them on the left, center or right.')+image('ultimate/header-custom.png','header-full')+groups+'<div class="note header-note">Keep the boards and controls you use within reach.</div>',"tl.fromTo('.header-group',{y:60,opacity:0},{y:0,opacity:1,duration:.45,stagger:.12,ease:'power3.out'},.4);")
ending='<img class="ending-logo" src="assets/homarr-wordmark-light.svg"><div class="ending-title">See you on the Workshop.</div><div class="ending-prize"><strong>Top 5 best submissions</strong> at the end of the year will get exclusive Homarr merch.</div><div class="ending-thanks">We’re giving back because you gave us so much money through donations.</div><div class="ending-sub">Stay tuned.</div><canvas id="confetti" class="confetti" width="1920" height="1080"></canvas>'
particles='''
const canvas=document.getElementById('confetti'),ctx=canvas.getContext('2d');
const rand=n=>{const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x)};
const colors=['#ff779d','#ffdd77','#a1ffcc','#8feaff','#c3a5ff','#ffffff'];
function draw(t){ctx.clearRect(0,0,1920,1080);for(let i=0;i<640;i++){let x,y;const r=rand(i+1),q=rand(i+911);if(i<360){x=r*2100-90+Math.sin(t*2+i)*55;y=((q*2100+t*(190+rand(i+22)*180))%1800)-450;}else{const side=i%2;const a=(t%4.8)-(i%3)*.36;const u=Math.max(0,a);const origin=side*1920;const speed=450+rand(i+13)*520;x=origin+(1-side*2)*speed*u;y=1070-(780+q*340)*u+240*u*u;if(a<0)continue;}ctx.save();ctx.translate(x,y);ctx.rotate(i+t*(2+r*5));ctx.fillStyle=colors[i%colors.length];ctx.globalAlpha=.85;ctx.fillRect(-5,-8,7+q*8,10+r*14);ctx.restore();}}
const clock={t:0};draw(0);tl.to(clock,{t:13,duration:13,ease:'none',onUpdate:()=>draw(clock.t)},0);
tl.fromTo('.ending-logo',{scale:.92},{scale:1,duration:.65,ease:'back.out(1.4)'},0);
tl.fromTo('.ending-title',{y:30,opacity:0},{y:0,opacity:1,duration:.6},.15);tl.fromTo('.ending-prize',{y:35,opacity:0},{y:0,opacity:1,duration:.7},1.0);tl.fromTo('.ending-thanks',{y:25,opacity:0},{y:0,opacity:1,duration:.6},2.4);tl.fromTo('.ending-sub',{y:15,opacity:0},{y:0,opacity:1,duration:.6},3.0);
'''
project('ending',13,ending,particles,False)
project('statistics',6,title('STATISTICS · EXPANDED VIEW · PR #6863 PREVIEW','Inspect your services at a glance.','Group metrics by integration, from health checks to inventory and downloads.')+image('ultimate/statistics-user.png','statistics-shot'),"tl.fromTo('.statistics-shot img',{scale:1},{scale:1.06,duration:4.8,ease:'sine.inOut'},.6);")
widgets=title('HOMARR 2.0 · NEW WIDGETS','Air Quality. Countdown. Timer.','Check local air quality, track events and run a focus session.')
widgets+='<div class="widget-card wc-air"><h2>Air Quality</h2><span class="widget-type">LOCAL CONDITIONS</span><img src="assets/new-widgets/air-quality.png"><div class="widget-note">AQI and local trends, with European and US scales.</div></div>'
widgets+='<div class="widget-card wc-count"><h2>Countdown</h2><span class="widget-type">UPCOMING EVENTS</span><img src="assets/new-widgets/countdown-focused.png"><div class="widget-note">Time remaining until the next event, with progress.</div></div>'
widgets+='<div class="widget-card wc-timer"><h2>Timer</h2><span class="widget-type">TIMER + POMODORO</span><div class="widget-note">Start, pause and reset. Focus and break sessions included.</div></div>'
project('widgets',8,widgets,"tl.fromTo('.widget-card',{y:30,opacity:0},{y:0,opacity:1,duration:.6,stagger:.12},.1);")
p=O/'widgets/index.html';w=p.read_text().replace('</section></div><script>', '</section><video id="timer-demo" class="clip compact-timer" src="assets/new-widgets/timer.mp4" data-start="0" data-duration="8" data-track-index="1" muted playsinline></video></div><script>');p.write_text(w)
# Preserve the complete first frame and slow motion of the previous intro.
p=O/'intro';p.mkdir(exist_ok=True)
for f in ['package.json','hyperframes.json']:shutil.copy(O/'workshop'/f,p/f)
if not(p/'assets').exists():(p/'assets').symlink_to('../../composition/assets',target_is_directory=True)
s=(R/'impact-widgets/intro/index.html').read_text().replace('impact-widgets-intro','workshop-intro').replace('src="assets/logo.svg"','src="assets/homarr-wordmark-light.svg"').replace('.brand img{width:42px;height:42px}', '.brand img{width:130px;height:95px}').replace('HOMARR / VERSION 2','HOMARR / VERSION 2').replace('A closer look at what changed.','Missing a widget? Make it yours.')
s=s.replace('.brand{position:absolute;left:72px;top:56px', '.brand{position:absolute;left:62px;top:22px')
(p/'index.html').write_text(s)


chapters=[(0,'Intro'),(7,'Missing a widget?'),(14,'32 new integrations'),(24,'Create a Custom Widget'),(30.8,'Widget ideas'),(36,'Assistant · Fast + free'),(46,'New drag-and-drop'),(50.5,'Cmd-click multi-select'),(56,'Containers'),(62,'Sidebar settings'),(65,'Fixed sidebar'),(70,'Advanced widgets'),(75,'New widgets'),(83,'Statistics'),(89,'Onboarding'),(94,'Customized header'),(101,'Board switcher'),(107,'Workshop · Merch')]
(O/'storyboard.json').write_text(json.dumps(chapters,indent=2))
page=(R/'impact-create/index.html').read_text()
page=re.sub(r'<p style="padding:14px.*?</p>','',page)
page=page.replace('107 seconds','120 seconds').replace('?v=10','?v=11').replace('../impact-ultimate/','../impact-create/')
page=page.replace('A slower animated reveal introduces 32 new integrations. BYOK and 50 free daily request units explained.','32 new integrations, compact widget previews, expanded Statistics and the Workshop merch announcement. Music: Go Funk by Infraction, mixed with TIKS effects.')
page=re.sub(r'<div><button.*?</div>','<div>'+''.join(f'<button onclick="const v=document.getElementById(\'film\');v.currentTime={t};v.play()">{label}</button>' for t,label in chapters)+'</div>',page)
page=page.replace('<details><summary>Capture notes</summary><p>','<p>Music: <a href="https://www.youtube.com/watch?v=-QBmUGvLwL0">Go Funk — Infraction</a> (user-supplied audio).</p><details><summary>Capture notes</summary><p>The expanded Statistics image was supplied by the user. Timer playback is shown at 490 × 258 pixels, alongside equally sized Air Quality and Countdown tiles. The merch announcement is the user’s supplied message. ')
(O/'index.html').write_text(page)
print('Built workshop cut: 120 seconds.')
