// Generated from trusted native contracts; unknown dictionary keys are anonymized.
// Regenerate with: bun run --cwd apps/nextjs snapshot:fields
export const snapshotPublicFields = new Set(
  `
$ $$typeof $count $get $option $param $ref $schema AUTH_PROVIDERS Aborted Accept AccessToken Accordion
ActionButton ActiveDownloads AdGuardHomeIntegration AddButton Album Anchor AnchorIntegration ApiKey Approved
ArchiveTeamWarriorIntegration Aria2Integration Array Audio AudioChannels AudioCodec AudioContext
AudiobookshelfIntegration Authorization Available Avatar BAD_GATEWAY BAD_REQUEST Bandwidth Battery
BazarrIntegration BeszelIntegration BinderyIntegration BitRate Bitrate Boolean CI CONNECTING CPU Cancelled Card
Category Certificate CertificateResult Chip Client Collapsible CommunityRating Completed Component Container
Controller Cookie CoolifyIntegration CopyButton DELETE DEMO_MODE DEMO_READ_ONLY DashDotIntegration DataList
Date DateCreated DatePickerInput DateTimeFormat DateTimePicker Declined DelugeIntegration DeviceId DeviceName
Directory Disk Download DownloadPaused DownloadRate DownloadTimeSec DownloadedSizeMB ENABLE_DOCKER
ENABLE_KUBERNETES ETA EmbyIntegration EmptyState Episode EpisodeCount EpisodeTitle Errored Event FILESIZE
Failed FileSizeHi FileSizeLo FileSizeMB Framerate FromIntegrationError GET GPU Genre Genres GlancesIntegration
GluetunIntegration GotifyIntegration Grid HOMARR_WEBSITE_URL HTMLAttributes HealthCheck Height HistoryTime
HomeAssistantIntegration ICalIntegration ID INTERNAL_SERVER_ERROR IP Icon IconActivity IconAlertCircle
IconAlertTriangle IconApi IconArrowDown IconArrowLeft IconArrowRight IconArrowUp IconBell IconBluetooth
IconBolt IconBookmark IconBrandDocker IconBug IconCalendar IconCamera IconChartBar IconChartLine IconChartPie
IconCheck IconChevronDown IconChevronLeft IconChevronRight IconChevronUp IconCircleCheck IconCircleX
IconClipboard IconClock IconCloud IconCloudOff IconCode IconCompass IconCopy IconCpu IconDatabase
IconDeviceDesktop IconDeviceMobile IconDownload IconDroplet IconEdit IconExternalLink IconEye IconEyeOff
IconFile IconFlag IconFlame IconFolder IconGauge IconGitBranch IconHeart IconHeartbeat IconHistory IconHome
IconInfoCircle IconKey IconLink IconLoader IconLock IconLockOpen IconMail IconMap IconMapPin IconMinus IconMoon
IconMusic IconNetwork IconPhoto IconPin IconPlayerPause IconPlayerPlay IconPlayerSkipBack IconPlayerSkipForward
IconPlayerStop IconPlus IconPokeball IconPower IconProgress IconRefresh IconReload IconSearch IconServer
IconSettings IconShield IconSpeedboat IconStar IconSun IconTerminal IconThermometer IconTrash IconTrendingDown
IconTrendingUp IconUpload IconUser IconUsers IconVideo IconVolume IconVolume2 IconVolumeOff IconWifi
IconWifiOff IconWorld IconX Id Image ImmichIntegration InProgress IndexNumber Initializing IsAudioDirect
IsPaused IsVideoDirect ItemComponent JSON JackettIntegration JellyfinIntegration
JellyseerrBlacklistedOrOverseerrDeleted JellyseerrDeleted JellyseerrIntegration KUBECONFIG
KUBERNETES_SERVICE_ACCOUNT_NAME Labels LidarrIntegration List LiveTvChannel LiveTvProgram LlamacppIntegration
LoadAvg1 LoadAvg15 LoadAvg5 Locale MAX_SAFE_INTEGER Math MaxPriority Media MediaContainer MediaSources
MediaStreams Memory Menu Metadata MiliCore MockIntegration MonthPickerInput Movie MusicVideo NEVER NODE_ENV
NOT_FOUND NO_EXTERNAL_CONNECTION NTFYIntegration NZBID NZBName NaN Name Names NavLink NavidromeIntegration
NextcloudIntegration Notebook Notification NowPlayingItem Number NumberFormat NzbGetIntegration OPEN
OPNsenseIntegration Object OpenMediaVaultIntegration Other OverseerrIntegration Overview PATCH PI PLATFORMS
POSITIVE_INFINITY POST PUT PaginatedList PaperlessNgxIntegration ParentIndexNumber Parse ParseResult Part
PartiallyAvailable PatchMonIntegration PeaNutIntegration Pending PendingApproval Ping PlayMethod PlayState
Player PlexIntegration Ports PositionTicks Pragma PremiereDate Preview PreviewWrapper PrivatePort Processing
Progress Provider ProwlarrIntegration ProxmoxIntegration PublicPort Pw QBitTorrentIntegration Queued ROMS
RadarrIntegration ReadarrIntegration RefreshButton Rejected RemainingSizeHi RemainingSizeLo RemoteEndPoint
Request RunTimeTicks SAVES SCREENSHOTS SECRET_ENCRYPTION_KEY STATES SabnzbdIntegration ScriptStatus SeasonName
SeerrIntegration Series SeriesName ServerId Session SlskdIntegration SonarrIntegration
SpeedtestTrackerIntegration StatBar StatsIntegration Status StatusResult Stream String Studios SubData SubFetch
Succeeded SynologyIntegration TOTAL_FILESIZE_BYTES TabPanel Table TablerIcon Tabs TabsContainer Taglines
TdarrIntegration Temperature ThousandCore TimedOut Timeline Timezone TimezoneService ToggleSwitch Tooltip
TracearrIntegration Track TraefikIntegration TranscodeDecisionMaker TranscodeSession TranscodingInfo
TransmissionIntegration TrueNasIntegration TvChannel TvProgram Type TypeBadge UTC UmamiIntegration
UnauthorizedResult UnifiControllerIntegration Unknown UnknownResult UnraidIntegration Upload
UptimeKumaIntegration User UserId UserName Username Version Video VideoCodec WORKSHOP_API_URL WORKSHOP_WEB_URL
WazuhIntegration WebkitLineClamp WebkitMaskImage Width Wrapper WudIntegration YearPickerInput ZodError
ZodObject ZodOptional ZodUndefined ZodVoid _count _id _index _source a a11y abort aborted above abs absolute
accent accept accessControl accessModes accessToken accessibility accessibilityRequirements accessibleMuted
accessor accordion accordionControl accordionItem accordionScope accordionValue account accountHostResult
acknowledged acquire acquireConcurrency acquireLocal acquireLocalConcurrency acquireLocalRate acquireStored
acquireTokenAsync action actionCompleted actionHref actionLabel actionSimulated actionWarningDescription
actionWarningTitle actions actionsDisabledEditMode actionsPending active activeCount activeNotes activeSessions
activeSizeBytes activeSlots activeStreams activeTargets activeTorrentThreshold activeWorkers actorId
adGuardHome adapter adaptiveColumns adaptiveOrientation add addAddress addButton addCertificate
addEventListener addIssue addItem addMember addSample addSubnet addToHistory added addedAt addedDate added_on
additionalProperties address addresses admin adsBlockedToday adsBlockedTodayPercentage ads_blocked_today
ads_percentage_today advanced advancedCard advancedColumns advancedContent advancedOptions advancedRoot
affectedAgents affected_items age agent agentId agentLimit agentName agentVersion agents aggregate aggregations
aggs airDate airDateUtc airQuality airQualityRouter alarms album albumCount albumId albumIds albumList2
albumName albums alder alert alertId alerts aliases align alignItems alignSelf all allOf allOfGivenCategory
allSettled allThatSupportSearch allocatable allocatableCpuPercentage allocatableRamPercentage allocated
allowAutoPlay allowAwaitOutsideFunction allowCamera allowDataOverflow allowFullScreen allowGeolocation
allowMicrophone allowModals allowMultiple allowOther allowPayment allowReadOnlyCheck allowReturnOutsideFunction
allowScrolling allowSourceChanges allowedIntegrationKinds allowed_cameras allowed_ips alreadyImported alt
alternate alwaysVisible ambiguous amount analytics analyticsEnabled analyticsRouter anchor anchorNote
anchorNotes anchorNotesRouter and animateIcon animateIcons animateOpacity animateWeatherIcon animated
annotation annotations announceList announcements anonymousId answer answerRequest anthropic any anyOf api
apiGetAsync apiKey apiKeyConfigured apiKeyHeader apiKeyId apiKeyQuery apiKeySettingsPath apiKeys apiKeysRouter
apiMap apiName apikey app appIcon appId appRouter appRow appText appTitle appWithUrl apparentTemperature
appearance append appendChild appendJournal appendMessage appid application applicationType application_id
applications appliesExceptBlockedProps apply applyBandwidthFrame applyBroadcastMessageFrame applyFilterToRatio
applyFrameToSnapshot applyItemStatusFrame applyPipelineStartItemFrame applyProjectRefreshFrame
applyProjectSelectedFrame applyRunnerStatusFrame applySample applyWarriorStatusFrame approve
approveRequestAsync approved approvedPushes apps aqi aqiStandard arch architecture archive archiveTeamWarrior
archiveTeamWarriorRouter archived areaChartProps argument arguments argv aria2 ariaLabel array arrayBuffer art
article artist artistCount artistName artists as asMilliseconds asOf asc aspectRatio assetCount assetId assets
assign assistant assistantConfigurations assistantMessages assistantRouter assistantThreads astDepth async
asyncIterator at atLocation atomCount attempt attemptSearchEngineCreation attemptedSources attentionStyle
attributeFilter attributes attrs audio audioChannelsDisplay audioCodec audioCodecs audioContainers
audioDecision audioStats audioStatsRouter audiobooks audiobookshelf audit auth authBranding authMethod authType
authTypes authenticateApiAsync authenticateAsync authenticateUserByName authentication author authorName
authorization authorizationHeaderValue autoStartBreaks autoStartFocus autobrr autobrrStatsProvider automationId
autoplay avail_real availability available availableBytes availableHeight availablePkgUpdates availableStatuses
availableUpdates avatar avatarUrl averageHumidity averageSpeed averageTemperature averageUptimePercent averages
avg avgDuration avgGenerationSpeedTps avgPromptSpeedTps avg_bits avg_processing_time awaitingManualStart
axiosInstance b backdrop backdropImageUrl backdropPath backend background backgroundColor backgroundImage
backgroundImageAttachment backgroundImageRepeat backgroundImageSize backgroundImageUrl backgroundPosition
backgroundRepeat backgroundSize badge badgeHeight badgeSize balanced bandwidth bangs bangsRouter bar barFill
barGap barSize base baseCpu baseDisk baseGroupIndex baseMem baseTimeMs baseTokens baseUrl baseUrlSource
basename basic bat battery batteryCharge batteryRuntime batteryVoltage bazarr bazarrRouter bazarr_version bb
bearer behavior belongsTo beszel beszelAlerts beszelRouter beszelStatsContainer beszelStatsControls
beszelStatsPeriodButton beszelStatsPeriodToggle beszelStatsRoot beszelStatsSystemToggle
beszelStatsTouchControls beszelSystemGrid beszelSystemStats beszelSystemTable billionthsCore binaryMultipliers
bind bindery bindingChanged bindingTypeConflict bindings birch bitfield bitrate bitrateKbps bittorrent black
blacklisted blockListZones blocked blockedCapabilities blockedProps blockedZones blocked_filtering blocking
blue bm board boardGroupPermissions boardId boardIds boardName boardPermissions boardRouter
boardSnapshotCaptured boardUserPermissions boards body bodyEncoding bodyLineClamp bodyTimeout bold book
bookmark bookmarks books bool boolean border borderBottom borderColor borderLeft borderRadius borderTop
botanicalInfoCount bottom bounceRate bounces boundaryKey boxShadow brand breakpoint broadcastMessage bruteForce
buckets budget budgets buffer bug buildDashboardData buildRequest byId byIds byServer byteLength byteUnitSystem
bytes bytesProxied bytesTotal bytes_recv_rate_per_sec bytes_sent_rate_per_sec c ca caData cacheDiscount
cacheKey cacheSeconds cacheTtlSeconds cacheVersion cache_discount cached cachedInputTokens caches caddy
caddyStatsProvider calculateEta calendar calendarHeader calendarHeaderControl calendarHeaderLevel
calendarRouter call callCollectionMethod callee cameras can canAccess canCreate canInteract
canInteractWithSelectedIntegrations canManageAll canParse canSelectMultiple canToggle canUse
canUserSeeAppsAsync cancel cancelSample canceled cancelled candidateKey candidates canonicalName capabilities
capacity capacityUnit caps carbonMonoxide card cardAction cardPadding cardinality carouselContainer
carouselControls carouselImage cat catalog catalogField catch catchall categories category categoryFilter cause
ceil cellContent cellPadding cellsClassName cellsStyle center cert certificate certificateRouter certificates
cgiPath chain change changeBoardVisibility changeByteUnitSystem changeCollapsed changeColorScheme
changeDdgBangs changeDefaultSearchEngine changeEnableRightClickOnWidgets changeFirstDayOfWeek
changeHeaderPreferences changeHomeBoards changePassword changePercentage changePingIconsEnabled
changeSearchPreferences changedetection changedetectionStatsProvider changes channel channelCount channelLayout
channels charAt charCodeAt characters charging chart chartHeight chartProps chartStyle chartSurface chartType
charts check checkServerIdentity checked checks checksDown checksGrace checksNew checksUp checksum chevron
children chip choices choicesFrom chooseBestImage chooseBestImageAsURL ciphers cities city classList className
cleanupTotals clear clearApiKey clearAsync clearCredentials clearCustomHeaders clearFieldError
clearSessionAsync clearTimeout clearable click clickable clickableCard client clientFilter clientId clientInfo
clientX clientY clients clipboard clipboardData clock close closeDropdown closeModal closeOnClickOutside closed
closest cluster clusterIP clusterIntegrationIds clusterMonitoring clusterRouter clusters cmd code codePointAt
codeberg codec codecs codes coerce coerceTypes collapse collapseProps collapseStates collapsed collapsible
collection collectionItems collectionSummary collections color colorByDayNight colorContext colorDepth
colorScheme colorSpace colorWeatherByDayNight colors cols column columnAccessor columnAccessors columnCount
columnGap columnItemHeight columnOrder columnWidths columns columnsOrder columnsWidth comboboxProps comfortable
commands comment compact compactColumns compactDisplay compactDuration compactFooter compactMetrics compactMode
compactOsBar compactOsBars compactOsLabel compactPrimary compactProgress compactRoot compactStatGrid
compactStatLabel compactStatTile compactStatValue compactStatus compactSurface compactTarget
compareAndSwapSession complete completeSetup completeTour completed completedAt completedBoardTour
completedFocusSessions completedLength completedManageTour completedSize completed_time completion
completionPrice completion_on completions complianceColor compliancePercent component componentCount
componentEmpty componentLoader componentSearch components compositeKey computeTimeRange computed concat
concurrency conditions confidence config configMaps configMapsRouter config_file_path configuration
configurationFingerprint configurationRequestUser configurationVersion configure configureSource configured
configuredCharts configuredSecretKinds configuredSecrets confirm confirmDelete confirmDisabled confirmLabel
confirmMessage confirmPassword confirmProps confirmUrl confirmation confirmed connect
connectAndAuthenticateAsync connectTimeout connected connection connectionConfigured connectionMap connections
consequent constructAvatarUrl contain container containerChanged containerCount containerDecision
containerFilter containerId containerName containerStats containerType containers containsAlternation
containsQuantifier content contentAttributes contentIsJsonDelta contentLength contentNormalized contentType
contentWidth context contextActions contextAlreadyLoaded contextId contextLength contextSize contextUsage
context_length contexts contextsRouter continueAfterPersistence control controlMode controlSize controls
convertToZone cooked cookie cookieHeader cookies coolify coolifyRouter coordinateGetter copied copy copyLabels
copyPath coreApi cores correspondents correspondentsCount cost count countGuests countIcons countUsers
countdown countries country countryCode country_code counts coverType cpu cpuBase cpuBrand cpuModel
cpuModelName cpuPeak cpuTemp cpuUsage cpuUsageOverTime cpuUtilization cpuWalk cpu_name cpub cpum cpus cputemp
create createApi createAssetsAsync createAuthHeaders createBasicAuthHeader createBindings createBoard
createCalendarClientAsync createCallback createCaller createCallerFactory createClient
createControllerClientAsync createDockerSourceId createElement createFromPreview createGain createGroup
createId createImageAsync createImagesAsync createIndexer createInitialExternalGroup createInvite createLxc
createMany createNode createNotification createObjectURL createOptions createOscillator
createPiHoleIntegrationAsync createProtocolSummary createRequest createRequestAsync createResourceDetails
createResourceUsage createResponseRequestAsync createSockJsWebSocketUrl createStatusFromSnapshot createStorage
createTechnitiumDnsIntegrationAsync createThread createUrl createUser createVm createWorker created createdAt
created_at creationDate creationTimestamp creator creatorId credentialFields credentials
credentialsClearedForDestinationChange credentialsMissing credentialsOptional critical criticalAt criticals
cron cronJobs cronJobsRouter csrfToken ct ctx culture currency current currentAccessor currentApp
currentContext currentId currentIndex currentPrice currentStep currentTarget currentTime currentToken
currentUser currentVersion current_page currentlyPlaying cursor custom customApi customApiRequest
customApiRouter customCss customCssClasses customError customHeaders customHeadersConfigured customTimeFormat
customTitle customTitleToggle customUrls customWidget customWidgetConfiguration customWidgetDefinitions
customWidgetRouter customWidgetSecrets customWidgetSelect customWidgetVersion custom_port cve cveLimit cveOrder
cves cycles d daily dailyCard dailyCardButton dailyCardFact dailyCardFacts dailyColumns dailyDetails
dailyDetailsDropdown dailyDetailsTemperature danger dark darkIconUrl dashDot dashboard dashboardUrl data
dataKey dataLines dataPoints dataRegion dataUpdatedAt data_region database databaseSizeBytes dataset date
dateFormat dateStyle dateTime dateTimeEventList date_histogram date_range dates datetime day dayColor
dayDifference dayOffset dayWeatherColor daylightDuration days db dbSize ddgBangs ddgBangsEnabled deadline debug
decimalMultipliers decision decline declineRequestAsync declined decode decodeURIComponent decodeWebSocketData
decodedTokens decoding decrement decrypt decryptedSecrets dedupeKey deepseek def default defaultAccountType
defaultChecked defaultColor defaultColorScheme defaultColumnProps defaultColumns defaultContextId
defaultIconSize defaultLocale defaultModelId defaultOpen defaultOptions defaultPort defaultSearchEngineId
defaultSort defaultTab defaultTitle defaultUrl defaultValue defaultView define defineProperty definition
definitionChanges definitionId definitionStateFingerprint dehydrate del del_files delay delayMs delete
deleteBoard deleteCount deleteGroup deleteInvite deleteItem deleteItemAsync deleteMedia deleteMessages
deleteNotification deleteNotificationAsync deleteSecret deleteSession deleteThread deleted deluge deniedReason
dense density deprecated depth desc descending descendingDefaultSort describe description
descriptionDisplayMode descriptionLineClamp descriptionLines descriptionMaxLength destination destination_id
destroy destructive detail detailLabel detailMetric detailed details detailsButton detailsControlLabel
detailsTarget detectRuntimeCapabilities detectVersionAsync detectedType device deviceId deviceInfo deviceName
deviceType device_class device_name device_status devicename devices dhcp dhcp_available diagnostic
diagnosticButton diagnosticMessage diagnostics diagnosticsTitle diaryEntryCount diff diffsDetected digest
digitalRelease dimension dimensions dio diom dir directPlay directPlays directStream directStreams direction
directories disable disableAsync disableDns disableJob disableStatus disableTemperatureDecimals disabled
disabledParams disconnect disconnected discoverDockerServices discoverModels discoverable
discoveryAuthentication discriminatedUnion disk diskIO disk_id diskread disks diskwrite dispatch dispatcher
display displayConfig displayMode displayName displayScale displayText displayType displayValue display_name
dispose distance distro dlspeed dnsHole dnsHoleControls dnsHoleRouter dnsHoleSummary dnsQueriesToday dnsStatus
dns_addresses dns_port dns_queries dns_queries_today doc docChanged doc_count docker dockerContainers dockerCpu
dockerHub dockerLabels dockerMemory dockerNetwork dockerRouter docsUrl documentTypes documentTypesCount
documentationSlug documentationUrl documents documentsInbox documentsTotal documents_inbox documents_total dom
domain domainsBeingBlocked domains_being_blocked done doneDate dot down downAlerts downCount downSpeed
down_command download downloadClient downloadSpeed downloadStatus download_bits download_payload_rate
download_rate download_time downloaded downloadedEver downloading downloads downloadsRouter dp dr draggable
dragon drm dropdown dropdownItems dropdownOpened dropdownType droppedTargets dstuser dt du dump duplicate
duplicateBoard duration durationMs durations dw dwm dynamicMultiSelect dynamicRange dynamicSelect e ecmaVersion
editCount editProfile editSample editability editable editor editorCreated editorId editqueue edits
effectiveColumns effective_user effects efs electric element elementProps elements ellipsis email emailVerified
embedUrl emby emittedEventCount emittedSnapshotCount emitterContext empty emptyLabel emptyState enable
enableAsync enableBlocking enableGeneral enableJob enableRightClickOnWidgets enableRowSorting enableRtl
enableStatusByDefault enableThresholdColors enabled enabledFeatures enabledParams enclosure encodeURIComponent
encrypt encryptedApiKey encryptedHeaders encryptedValue encrypted_key end endAt endDate endIndex endOf endpoint
endpointHost endpointId endpointIds endpointName endpoint_ip endpoint_port endpoints endsWith
ensureRootCertificate entities entityDetails entityId entityState entityUnit entity_id entries entry
entryPoints enum enumerable env environment environmentId environmentName environmentUuid environment_id
environments episode episodeCount episodeFileCount episodeName episodeNumber episodes episodesHandled error
errorBadgeLabel errorBody errorCode errorCount errorFormatter errorIndicator errorLabel errorMessage errorName
errorType errors escape estSize estimatedSize eta etag europeanAqi europeanAqiMax europeanSubIndices eval
evaluate evaluateArray evaluateBinary evaluateCall evaluateJsxElement evaluateJsxFragment evaluateLogical
evaluateMember evaluateObject evaluateTemplateLiteral evaluateUnary event eventCard eventCount eventName
eventNames eventType event_name events every evictConnection evidence evidenceComplete evidenceReset
exactAppUrl exactIntegrationUrl exactUrl example examples excellent exceptions exec executeAction
executeAutomation existing exists exited exp expanded expectOkAsync expected expectedRevision expectedSource
expectedStateFingerprint expirationDate expiresAt explicit explicitArray exponentialRampToValueAtTime export
exportLegacy expression expressions extend extended_bounds extensions externalUrl extra extraFilesystems
extraParams extractLatestReportingData extractLoginTokenFromCookies extractNetworkTrafficData
extractSessionIdFromCookies extras f fact fahrenheit fail failed failedBoth failedEndpoints failedFeedCount
failedHealthCheckCount failedIntegrations failedScrutiny failedSmart failedTranscodeCount fails failure
failureFingerprint failureType fairy fallback fallbackCount fallbackLatencyMs false family fanSpeed fan_speed
fatal faviconImageUrl favorites featuredOrder features feedIndex feedUrl feedUrls feedback feelsLike fetch
fetchAsync fetchAuthenticatedAsync fetchCalendarObjects fetchCalendars fetchCertificateAsync fetchCountAsync
fetchImpl fetchJsonAsync fetchOkAsync fetchOptions fetchPageAsync fetchQuery fetchSettingsAsync
fetchStatisticsAsync fetchStatsAsync fetchTool fetchUsersPublicAsync fetchWithAuthAsync field fieldPath fields
fighting file fileCreatedAt fileModifiedAt fileName fileNameWithExtension filePath fileSize fileSizeBytes
fileSystem file_size fileflows fileflowsStatsProvider filename files fill fillHeight filter filterFutureMonths
filterIsWhitelist filterPastMonths filters fim finally find findAll findAllEvents findComponents findFirst
findIcons findIndex findLast findLastIndex findMany fingerprint fingerprint256 finish finishReason
finish_reason finite fire firewall firewallCpu firewallInterfaces firewallMemory firewallRouter firewallVersion
firewallsVersionData firmware firmware_ver firstAirDate firstDayOfWeek firstType fit fixed_interval flags flash
flat flatMap flatten flex flexDirection flexGrow flexShrink flip float floor flying fmt focus focusMinutes
focused followUpDefinitionId followedBy following font fontFamily fontSize fontVariantNumeric fontWeight footer
for forEach force forceDisableStatus forceRemove forced forcedColors forecast forecastButton forecastDayCount
forecastDays forecast_days foreignAuthorId forksCount formData format formatByteRate formatBytes
formatBytesPair formatItemName formatToParts formatted formattedValue formatter fps fqdn frame frameRate
framerate free freeText free_only freeze frequency friendly_name frigate frigateStatsProvider from fromDisk
fromEntries fromFetchError fromNow fromResponse fromString fs fsFree fsSize fsUsed ftype full fullDetailsTool
fullPreview fullTab fullWidth fullWidthField function function_calling fw fz g gain galleries gallery_count
game gap gatus gatusStatsProvider generationAccessToken generationId generationSpeedTps generationTimeMs
generation_time generations generationtime_ms generator geometry get getAccessTokenAsync
getActiveSessionsCountAsync getActiveVisitors getAdminConfiguration getAgents getAgentsOverviewFromApiAsync
getAgentsOverviewFromIndexerAsync getAlbum getAlbumAndSongCountsAsync getAlbumPreview getAlbums
getAlertHistoryAsync getAlertPeriodsAsync getAlerts getAlertsAsync getAll getAllAppIdsOnPublicBoardsAsync
getAllAsync getAllBoards getAllStatsAsync getAllSubcomponents getApiAsync getApiDefinitionAsync
getApiTokenAsync getAppVersion getApplicationIconUrlAsync getApplicationImageUrl getApplicationsByIdAsync
getArtistCountAsync getAsync getAttribute getAttributes getAuthFailures getAuthHeaders getAuthHeadersAsync
getAuthParams getAuthoringPrompt getAuthorizationHeaderValue getAvailability getAvailableUpdates
getAverageOfCpu getAverageOfCpuFlat getBadges getBadgesAsync getBoardByName getBoardPermissions
getBoardSettings getBoardsForGroup getBooleanValueOverAllSites getBoundingClientRect getBranding getById
getByIdAsync getByIdsAsync getCalendarEventsAsync getCertificate getChannel getClient getClientAsync
getClientJobsAndStatusAsync getCluster getClusterHealthStatus getClusterInfoAsync getClusterResourceCounts
getCode getComponent getComponentCatalog getComponents getConfigMaps getConfiguredIndexersAsync
getConfiguredKinds getContainerStatsAsync getContainers getContents getContextEntities getContextObject
getContexts getContextsAsync getCpuTempAsync getCulture getCurrent getCurrentCluster getCurrentContext
getCurrentCpuLoadAsync getCurrentGpuLoadAsync getCurrentMemoryLoadAsync getCurrentNetworkLoadAsync
getCurrentSessionsAsync getCurrentStorageLoadAsync getCurrentStreams getCurrentlyPlayingType getDashboard
getDashboardDataAsync getData getDataAsync getDataStatus getDate getDay getDefaultClient getDefaultInstance
getDefaultSearchEngine getDimensions getDnsBlockingStatusAsync getDnsStatusAsync getDownloadState
getDownloadsAsync getEndpoints getEntityStateAsync getEntityStatsAsync getErrorBoundaryData getEventNames
getEvidence getExample getFeeds getFileSystemsAsync getFim getFirewallCpuAsync getFirewallCpuStatus
getFirewallInterfacesStatus getFirewallMemoryStatus getFirewallVersionStatus getFirstProperty
getFirstSubcomponent getFirstValue getFullYear getGenerationTelemetry getGlancesVersionAsync getGlobalStat
getHTML getHeaders getHealthCheckDataAsync getHeartbeatAsync getHistoryAsync getHomeBoard getHttpAuthentication
getHttpAuthenticationAsync getIndexersAsync getIndexersStatus getInfo getInfoAsync getIngresses getInputProps
getInstance getInstanceInfoAsync getInstancesInfo getIntegrationPermissions getInterfacesChannel getItem
getItemInformationAsync getJobs getJobsAndStatuses getJournal getJwtTokenAsync getKeys getKinds
getKubernetesVersionAsync getLabel getLatest getLatestMedia getLatestRequests getLatestResultAsync
getLibrariesAsync getLibraryStatsAsync getLinksForLidarrCalendarEvent getLinksForRadarrCalendarEvent
getLinksForReadarrCalendarEvent getLinksForSonarrCalendarEvent getListeningStatsAsync getMachineIdentifierAsync
getManageOverview getMediaQueueAsync getMediaReleases getMediaReleasesAsync getMediaReleasesWithDispatcherAsync
getMediaRequestOptions getMessagesUrl getMilliseconds getMissingAsync getModelCapabilities getMonth
getMultiEventTimeSeries getNamespaces getNetworkInterfacesAsync getNetworkSummaryAsync getNodeMetricsAsync
getNodes getNonTorrentState getNote getNoteAsync getNotifications getNotificationsAsync getNowPlayingAsync
getNumericValueOverAllSites getOccurrenceDetails getOwnPropertyDescriptor getOwnPropertyNames getPaginated
getPeerX509Certificate getPingSystem getPods getPoolsAsync getPos getPreferences getPriceHistory
getProjectByUuidAsync getPromoxApi getPropertyValue getPrototypeOf getPublicBoards getPublicIpAsync
getQueryCache getQueryData getQueueAsync getReader getRecentAsync getRecentResultsAsync
getRecentlyAddedEpisodesAsync getReference getRegistry getReportingAsync getReportingNetdataAsync
getRequestOptions getRequestsAsync getResourcesAsync getRuntimeOptions getSeconds getSecretValue getSecrets
getSelectable getSeriesInformationAsync getServerStats getServerStatsAsync getServerStatus getServiceHealth
getServices getSession getSessionAsync getSessions getSetCookie getSharedProps getShowSectionsAsync
getSitesStats getSkill getSliceAsync getSliceUntilTimeAsync getSlug getSmartAsync getSmartInfoAsync
getSocketAsync getState getStatisticsAsync getStats getStatsAsync getStatsSummaryAsync getStatus getStatusAsync
getStatusPageAsync getStatusValueOverAllSites getStorageLoadInfoAsync getStorageVolumesAsync getStreamsAsync
getSubsystem getSummaries getSummary getSummaryAsync getSystemDetailsAsync getSystemHealthStatus
getSystemInfoAsync getSystemInformationAsync getSystemStats getSystemStatsAsync getSystemStatusAsync getSystems
getSystemsAsync getText getThread getTime getTimeline getTimetable getTopList getTopPages getTopReferrers
getTopicURL getTorrentState getTourStatus getTranscodingQueueAsync getUTCDate getUTCDay getUTCFullYear
getUTCHours getUTCMinutes getUTCMonth getUTCSeconds getUpgradeCheckAsync getUpgradeStatusAsync
getUpsSummariesAsync getUsableSpaceByPoolAsync getUsenetHistoryState getUsenetQueueState getUsers getUsersAsync
getUtilizationAsync getValidator getVersion getVersionAsync getViolationsAsync getVisitorStats getVolumes
getVpnSettingAsync getVpnStatusAsync getVulnerabilities getWebsiteByIdAsync getWebsiteEventMetricsAsync
getWebsiteEventTimeSeriesAsync getWebsiteMetricsAsync getWebsitePageviewsAsync getWebsiteStatsAsync getWebsites
getWebsitesAsync getWidgetOptionSettings getWorkersAsync getYear ghost gi gid gitHubContainerRegistry
gitVersion github githubAppId githubInstallationId gitlab glances global globalProps globalRatio gluetun good
gotify gpu gpuId gpuMemory gpuNames gpuPower gpuUsage gpuUsageOverTime gpu_id grandparentArt grandparentKey
grandparentThumb grandparentTitle grape graphHeight graphValues grass gravity gray green grid gridAutoRows
gridAxis gridColumn gridColumns gridCompact gridShort gridTemplateColumns gridTemplateRows groq ground group
groupBy groupByDate groupId groupIds groupItems groupMembers groupMemberships groupPermissions groupRouter
groups grow gte guests gusts h haState handle handleAsync handleError handleParseError handleRef
handleRequestError handleResponseError handleSync handled handler handlers has hasAccess hasActions hasAutoPlay
hasChangeAccess hasChanged hasChildren hasControls hasDelegatedFullAccess hasError hasErrors hasFile
hasForecast hasFullAccess hasGpu hasIconColor hasInteractAccess hasMultipleClients hasMultipleTypes hasNetwork
hasOwn hasResult hasSecret hasSecretValue hasSelectedEvents hasShadow hasToken hasTorrents hasUseAccess
hasValue hasViewAccess hash hashString hastate head header headerLink headerLinkIcon headerName
headerPreferences headerRight headers headersTimeout heading health healthCheck healthCheckStatus healthInfo
healthMonitoring healthMonitoringRouter healthcheck healthchecks healthchecksStatsProvider healthy
heartbeatList heartbeatUrl height heightProperty here hero heroCounts heroExpanded heroInbox heroLabel
heroRingOnly heroText heroTextOnly heroTotal heroValue heroWithText hidden hide hideDescription hideHostname
hideIcon hideLogos hideLogsLink hideTitle high highlights hint history historyDepth historyWindowDays hits
homarr homarrWebsiteUrl home homeAssistant homeBoardId homeRouter homebox homeboxStatsProvider horizontal
horizontalScroll horizontalStats host hostPort hostname hostnames hosts hostsNeedingUpdates
hostsNeedingUpdatesCriticalAt hostsNeedingUpdatesThresholdMode hostsNeedingUpdatesWarningAt
hostsWithSecurityUpdates hostsWithSecurityUpdatesCriticalAt hostsWithSecurityUpdatesThresholdMode
hostsWithSecurityUpdatesWarningAt hosts_needing_updates hosts_with_security_updates hour hour12 hourCycle
hourly hourlyTickStep hours hover hovered href hset htmlFor http httpAgent httpAuth httpErrorHandler
httpResource httpResources httpSessionStore http_port httpsAgent humanize humidity hvals hwDecoding hwEncoding
hwRequested i18n ical ice icon iconColor iconColumns iconNames iconRepositories iconRepositoryId iconSize
iconUrl icons iconsRouter id id_task identifier identity idle ids iframe ignoredSourceIds image imageBytes
imageCount imageInput imageUrl imageUrls image_count images images_size imdb imdbId immediatelyRender immich
immichAlbum immichAlbums immichRouter immichStats implementation import imul in inCinemas inLibrary
includeArchivedHistory includeAuthor includeDocker includeEpisode includeEpisodeFile includeEpisodeImages
includeFromAllUsers includeHistory includeInfo includeMovie includeOutdated includeRegistry includeSeconds
includeSeries includeStopped includeroot includes incompatibleKinds increment incrementRate indent index
indexOf indexer indexerGetAsync indexerHealth indexerId indexerLink indexerManager indexerManagerRouter
indexerRequired indexerRow indexerSearchAsync indexerUrls indexers indicator indicatorColor indicatorMarginTop
indicatorSize indigo info infoAction infoActionCompact infoHash infoRouter ingressClassName ingresses
ingressesRouter inherited initUser initialExpandedState initialOptions initialProp initialSize initialValue
initialValues initialized inline inlineStats innerProps innerRef input inputModalities inputMode inputSchema
inputTokens inputTypes inputVoltage input_modalities inputs insert insertAllAsync insertContent insertKey
insertPath insertStarter insertText inset installCommand instance instanceInfo int integration integrationData
integrationEditForm integrationGroupPermissions integrationIcon integrationId integrationIds integrationItems
integrationKind integrationKindAvailable integrationKinds integrationMoved integrationMultiSelect
integrationName integrationRouter integrationSecrets integrationSelect integrationSupport integrationUrl
integrationUserPermissions integrations integrationsRequired integrationsWithInteractions interact interaction
interface interfaces interfacesError interfacesLabel interfacesLoaded internal intersection interval intervalMs
intervalSeconds invalid invalidAttemptCount invalidParams invalidResponse invalidSample invalidate
invalidateCache invalidateCacheAsync invalidateQueries invalidates invite inviteId inviteRouter invites io ip
is is24HourFormat isActive isAdmin isAdvanced isAfter isAnimationActive isArchived isArray isAudioDirect
isAxiosError isBedrockServer isBefore isBuffer isByok isDark isDate isDay isDefault isDemoMode isDemoReadOnly
isDense isDirty isDisposed isDragging isEditMode isEditable isEditing isEnabled isError isExpanded isFahrenheit
isFetching isFinite isFork isFormatFahrenheit isHome isInteger isLoading isMobileHome isMuted isNaN
isNewRelease isOpen isPassword isPending isPinned isPortFallbackError isPreRelease isPublic
isRecurrenceException isRecurring isRefreshing isRegistry isRoomy isRunning isSafeInteger isSame isSampleStale
isSaving isSearching isSelfSigned isSet isShared isStale isStaleRelease isTesting isTiny isTranscode isUp
isValid isVideoDirect isWeatherFormatFahrenheit is_build_server is_build_time is_byok is_preview is_processing
is_reachable is_upgraded is_usable iso isolation isps issue issueCount issuer issuerCertificate issues item
itemComponent itemCount itemGap itemHeight itemId itemKey itemLayouts itemOptions itemRadius itemSectionLayouts
itemType itemTypeName itemWidth item_id items itemsHandled itemsPath itemsWithWarranty iterator jackett
jellyfin jellyseerr jellystat jellystatStatsProvider job jobType join journal journalEmpty journals json
jsonRpc jsonSchema jsonrpc jsx justifyContent jwt k karakeep karakeepStatsProvider kbpersec keepMounted kernel
kernelVersion key key_passphrase keyed keys keywords ki kind kinds knownValues komga komgaStatsProvider
kubeConfig kubeletVersion kubernetes kubernetesEnabled kubernetesRouter kubernetesVersion la label
labelDisplayMode labelFormatter labelKey labelMiw labelPath labelledBy labels lan language languageJson
languageJsx last lastColumnResizable lastIndexOf lastKeepAlive lastPluginDetails lastSeen lastUpdated lastValue
last_changed last_online_at last_page last_updated latency latest latestEpisode latestRelease latestReleaseAt
latestResult latitude layer layers layout layoutId layoutPreset layouts lazy leeching left
leftGutterColumnCount leftJoin leftSidebar legacy legacyCustomWidgetDefinitions legacyId legacyMigrationOnly
legacyMigrationPrompt legacySurface legend length letterSpacing level levelBadge levels levelsGroup lg
libraries library libraryCount libraryId libraryName library_ids lidarr liftListItem light lightsOn lime limit
limitPerGroup limitPerIntegration limitations limits line lineAt lineClamp lineHeight lines link linked links
linksTargetNewTab linkwarden linkwardenStatsProvider linuxServerIO list listApplicationsAsync
listClusterCustomObject listConfigMapForAllNamespaces listDiscoveredContainersAsync listIngressForAllNamespaces
listNamespace listNode listNotes listNotesAsync listPersistentVolumeClaimForAllNamespaces
listPodForAllNamespaces listProjectsAsync listProjectsWithEnvironmentsAsync listSecretForAllNamespaces
listServersAsync listServiceForAllNamespaces listServicesAsync listStorageVolumes listStorageVolumesAsync
listStyle listSurface listThreads listTorrents listeners listeningTime listening_port listfiles listgroups
lists literal literalValues live liveActions llamacpp llamacppRouter load loadAverage loadAvg loadFromCluster
loadFromDefault loadFromOptions loadInBytes loadRequest loadSessionAsync loadedDefinition loadedHint loading
loadingLabel loc local localId localStorage locale localeCompare location locationName locationRouter
locationSummary locations log logError logRouter login loginAsync loginForHttpRequestsAsync loginToken logo
logoDisplay logoImageUrl logout logs longBreakMinutes longitude lookup low lowBattery lpush lrange lt lte ltrim
lxc lxcs m machineIdentifier main mainIndex maintainerr maintainerrStatsProvider maintenance makeApiClient
makeAuthenticatedRpcCallAsync makeRequestAsync makeRpcCallAsync makeRpcCallWithCustomFetchAsync manage
managementPath managerVersion mantineVersion manufacturer map mapAvailability mapDeviceToSummary
mapDisksFromLoadInfo mapDisksFromSmartInfo mapItem mapLegacyVolumes mapMediaReleaseType mapMonitor mapProject
mapRequestStatus mapStorageV2Volumes mapVolumeRecord margin marginBottom marginInlineEnd marginInlineStart
marginLeft marginRight marginTop markReleaseViewed maskImage match matchAll matchBefore matchResponse match_all
max maxApparentTemperature maxAstDepth maxAvailableMemoryBytes maxBottom maxCollectionItems maxHeight
maxHistoryItems maxIntegrations maxLength maxLevel maxMetrics maxOperations maxOutputLength maxOutputTokens
maxPages maxPerRequest maxProperties maxRecords maxRedirects maxRenderedNodes maxResponseSize maxRetries
maxScore maxSize maxStack maxSteps maxStringLength maxTemp maxTemperature maxUsedValue maxValue maxValues
maxVersion maxWidth maxWindGusts maxWindSpeed max_context_length max_input_tokens maxcpu maxdisk maximum
maximumAmountPosts maximumFractionDigits maximumSize maxmem mb mcp md mealie mealieStatsProvider mean media
mediaId mediaInfo mediaKey mediaMissing mediaOrganizer mediaOrganizerRouter mediaRelease mediaReleaseRouter
mediaReleases mediaRequest mediaRequestSearchTargets mediaRequests mediaRequestsRouter mediaRouter mediaServer
mediaServerRouter mediaTitle mediaTranscoding mediaTranscodingRouter mediaType medias medium mem memAvailable
memAvailableInBytes memFree memMiB memPeak memTotal memUsed memUsedInBytes memWalk memberProperty members
memory memoryAvailable memoryCapacityInBytes memoryTotal memoryUsage memoryUsageOverTime memoryUsed
memoryUtilization merge message messageFormat messageId messages meta metaTitle metadata metadataSearchDto
method methodColor methods metric metricCard metricColumns metricIcon metricLabel metricRow metricText
metricValue metrics metricsAvailable metricsProbeApi metricsStatus mi middleware middlewares midnightTs migrate
migrateItems migrateLegacy migrationRequired millionthsCore millisecond min minApparentTemperature minAxisSize
minHeight minLength minLevel minProperties minSeverity minSize minTemp minTemperature minTickGap minValue
minWidth min_doc_count minecraft minecraftRouter minecraftServerStatus miniflux minifluxStatsProvider minimal
minimalTab minimum minimumBoardPermission minimumWidth minimum_should_match minute minuteOfDay minutes missing
missingCount missingCredentials missingIntegrationCount missingSecrets missingSourceIds mistral mitre
mitreTactics mitreTechniques mm mobileHomeBoardId mock mode model modelDiscoveryPath modelId models
moderationLatencyMs moderation_latency modes modified modify module monitor monitorList monitored monitors mono
month monthCell months movie movies moviesHandled mp msg mssfix mt mtu mu mugwort multi
multiReleasesRepositories multiSelect multiText multi_hop_only multicolor multiline multiple music must_not
mutate mutateAsync mutation mutationDisabled mutationFn muted mz n n_ctx n_decoded n_params n_prompt_tokens
name nameMatch named namedRequestCount namedRequests names namespace namespaces namespacesRouter narrowShort
nativeEnum nativeFinishReason nativeId native_finish_reason native_tokens_cached native_tokens_completion
native_tokens_prompt native_tokens_reasoning navidrome navigation needsUrl nested net netBytes netKiB netWalk
netalertx netalertxStatsProvider netdata netdataStatsProvider netin netout network networkController
networkControllerRouter networkControllerStatus networkControllerSummary networkScope networkScopes
networkingApi neutralDividerBottom neutralDividerTop never neverConnected never_connected newDevices newOptions
newReleaseWithin newTab newValue newVersion next nextAccessor nextAction nextCursor nextIndex nextOccurrence
nextPage nextPhoto nextStep next_token nextcloud ni nightColor nightWeatherColor nitrogenDioxide noDataHint
noDataLabel noTemplate noWrap node nodeAt nodeCount nodeInfo nodeName nodePaused nodes nodesRouter nonempty
nonnegative normal normalize normalizeDisplayStatus normalizeItemStatus normalizeStatus normalizedCharacters
normalizedInputTokens normalizedOutputTokens normalizedUrl not notFound notRun notation noteId notebook
notebookRouter notes notesCount notificationId notificationPermission notification_id notifications
notificationsRouter notify now nowPlaying nowrap npm nr nrm ns nsm ntfy null nullable nullish numActive
numActiveSessions numArchived numBookmarks numConnections numFavorites numHighlights numLists numPieces
numSeeders numStopped numStoppedTotal numTags numWaiting num_blocked_filtering num_dns_queries num_guest
num_replaced_parental num_replaced_safebrowsing num_replaced_safesearch num_requests num_user number
numberOfSeasons numbers numeric nzbGet nzbGetApiCallAsync nzbGetApiCallWithCustomFetchAsync nzo_id o object
objectFit observe observedAt ocs of off officialSources offset offsetParent offsetWidth ok olive ollama omit on
onAction onAddToHomarr onBattery onBlur onCancel onChange onChangeOptions onClick onClose onConfirm onCopy
onCreate onCreateEditor onDelete onDestroyEditor onDropdownClose onDropdownOpen onError onFocus onFormat
onImageSelectionChanged onInsertDataPath onIntegrationSaved onLayoutChange onLocationSelect onMouseDownCapture
onNotificationsChange onOpenLogs onOpenNewIntegration onReadOnlyChecked onReadOnlyCheckedAtPosition onRedo
onReferenceToggle onRemove onRepositoryCancel onRepositorySave onReset onRetry onSampleDataChange onSave
onSelect onSettled onSort onSoundChange onStepClick onStoreError onSubmit onSuccess onSuccessfulEdit
onSwitchToHistorical onTest onToggleIp onToggleRunning onUndo onUpdate onboard onboardRouter onboarding
onboardingClaimToken once online opacity open openAssistant openConfirmModal openDropdown openInNewTab
openIndexerSiteInNewTab openIssues openModal openNewTab openOnClick openRaw openSearchInNewTab openSessions
openSocketAsync openSpotlight openSpotlightApps openSpotlightAssistant openSpotlightPreferences openai openapi
opened openingElement openmediavault openrouter openvpn operatingSystem operatingSystemVersion operation
operations operator opnsense opnsenseApiKey opnsenseApiSecret ops option optionDefinitions optionIds optionKey
optionRequest optionRequests optional optionalSecretKinds options optionsColumnSet optionsRouter opts or orange
order orderBy order_by order_direction ordered organization orientation origin originalSize originalTitle
originalfileSizeInGbytes originallyAvailableAt origins os osBar osBarGroup osCount osDisplayMode osDistribution
osDistributionLimit osDonut osDonutContent osDonutContentWithLegend osHeading osImage osLabel osLegend
osLegendItem osLegendLabel osLegendSwatch osLegendValue osName osPlatform osRow osScroll osSection
osSectionWithStats osSectionWrapper osType osVersion os_distribution os_name os_type os_version other
other_load others out outdated outline outlineOffset output outputFileSizeInGbytes outputSize outputTokens
outputVoltage output_modalities over overallStatus overall_status overallstatus overflow overflowWrap overflowX
overflowY override overseerr overview overview_data owned_only owner ownerId ownerReferences ozone p package
packages padEnd padStart padding paddingBlock paddingInline paddingInlineStart paddingTop page pageOffset
pageSize pageTitle pageviews paperlessNgx paperlessNgxRouter parameterCount parameterNames params parent
parentElement parentId parentIndex parentKey parentSectionId parentThumb parentTitle parse parseAsync
parseErrorHandler parseFloat parseFromString parseHTML parseInt parseJsonSafely parseSockJsMessage parseStatus
parseUmamiDate parseXmlAsync parsed partial partiallyAvailable parts pass passed passthrough passwd password
passwordKind patch patchmon patchmonApiKey patchmonApiSecret patchmonRouter path pathCopied pathInRouter
pathPrefix pathStart pathname paths pattern pause pauseAll pauseItem pauseItemAsync pauseQueue pauseQueueAsync
pauseTorrent paused pausedCount pausedownload payload peaNut pem pending pendingActions pendingActionsVisible
pendingAuthentication pendingDownloads pendingRead peopleHome perPage per_page percent percentComplete
percentDone percentTotal percent_blocked percentage percentageValue performer_count performers periods
permission permissionNotes permissions persistenceTool persistent persistent_keep_alive_interval
personalAccessToken pexpire phase phaseComplete photoCount photoInfo photos physicalRelease physmem pi piHole
pia_encryption_preset pick pieStats pieceLength pill ping pingEnabled pingIconsEnabled pingUrl pink
pinnedAddresses pipe placeItems placeholder plain plan plantCount plantit plantitStatsProvider plants platform
platforms play playback player playerName players playlists plex plural pm10 pm10Max pm2_5 pm2_5Max podcast
podcasts podman pods podsCount podsRouter pointerEvents points poison pokemon poll pollen pollutants pool poor
pop popoverProps population port port_forward_only port_forwarding ports pos position positionMs positions
positive post postAsync post_filter postal_code poster posterImagePath posterPath posterUrl postproc_time pow
power pp pre pre_shared_key precipitation precipitationProbability precipitationSummary precision predicate
preferComponentDiscovery preferDirectPreview preference preferences preferredExampleId preferredExampleIds
preferredPort preferredSettings prefetchQuery prefix premium_only preprocess preserveColumnWidths
preserveDataContract preservedSecretCount preservesPreviewEvidence presets preventDefault preview previewAction
previewCanvas previewComponent previewContent previewCreate previewDimensions previewDivider previewGet
previewJournal previewLiveActions previewPanel previewPath previewQuery previewRefresh previewResize
previewReviseTemplate previewRowLimit previewSectionId previewSession previewSessionId previewSizeControls
previewSizeInput previewUrl previewViewport previewWidget previewWrapper previous previousAlerts previousClose
previousOccurrence previousPassword previousPasswordRequired previousPhoto previousStep previousWidth price
priceHistory priceOrder pricing primary primaryColor primaryOffset primaryTime primaryTimeZone
primaryTimeZoneInvalid principalId priority privateKey private_key probability proc procedure procedures
processLine process_user processed processing processorUtilization producer product profile profilePath
profilePictureUrl progress progressMs progressSize project projectDescription projectName projectUrl
projectUuid project_html project_id prometheus prometheusStatsProvider promise prompt promptCacheHitRate
promptPrice promptSpeedTps propNames properties property propertyNames props protect protection_enabled
protocol protocolCard protocolGrid protocolLabel protocolRow protocolRows protocolTitle prototype provider
providerDetails providerLatencyMs providerMetadata providerOptions providerOutputTokensPerSecond providerUrl
provider_name provider_responses providers prowlarr proxmox proxyImageAsync psychic publicGroupList
publicIntegration publicIp publicLink public_ip public_key published publishedPort pulse purpose push pushAsync
push_approved_count push_rejected_count q qBittorrent qemu quantization quasis quay queries queriesDisabled
query queryCacheKey queryClient queryError queryFn queryGraphQLAsync queryKey queryKeys queryMatcher
queryOptions queryOrFragment queryParams queryRequest querySelector querySelectorAll queue queuePageSize
queuePosition queueStats queued queuedCount quicklook r race radarr radarrSignalr radarr_signalr radius ragweed
ram random randomAvailability randomSearchDto randomStatus randomizePhotos range ranges rank rate rateBuckets
rateDownload rateUpload rates rating ratio raw rawResponse rawTime rb rbm read readAuthenticatedBodyAsync
readFile readFileSync readNamespacedReplicaSet readNumber readOnly readSockJsSnapshotAsync readString
readTemplate readarr reads ready readyState real_usage realm reason reasoningTokens reasons rebootRequired
reboot_required receive received receiving recentActivity recentDays recentResults recentUpdates24h
recentViolations recent_updates_24h recipe_count recipes reclaimable recognized recommendedNextTool
reconcileServices reconfigure record recordIds recorded records recordsTotal recoverable recovery recurrence
recurrenceId red redactSecrets redactValues redacted redirect redis redo reduce reducedMotion ref reference
referenceOpened references referrerPolicy refetch refetchInterval refetchIntervalInBackground refetchOnMount
refetchOnReconnect refetchOnWindowFocus refine refresh refreshFailed refreshInterval refreshInventory regex
regexes region regions register registerInput registerSessionAsync registeredNames registry reject
rejectUnauthorized rejected rejectedPushes rejects rel relateException relation relativeHumidity relativeTime
release releaseConcurrency releaseDate releaseDateIsDateOnly releaseDescription releaseLocalConcurrency
releaseLock releaseType releaseUrl releases releasesDescription releasesRepository releasesRepositoryDetails
releasesRepositoryExpanded releasesRepositoryHeader releasesRouter remainingMs remainingTime remainingWeight
remaining_weight remoteUrl remoteValue remote_user_num_active remove removeAdditional removeAll removeAsync
removeCertificate removeDefault removeDownloadResult removeEventListener removeItem removeLabel removeMember
removeTorrent removeTrustedHostname renameBoard renameThread render renderCallback renderHTML
renderIntegrationSource renderToggleButton rendered renderedNodes renderer repeat repeatable
repeatedInvalidInput replace replaceAll replaced_parental replaced_safebrowsing replacementLines reportCount
repositories repository repositoryId representation represented request requestAsync requestBody
requestCapabilities requestCert requestCode requestCount requestDecodedTokens requestError requestFailed
requestId requestIdRequired requestIds requestMedia requestMediaAsync requestOptionalAsync requestParameters
requestPermission requestReason requestResponseAsync requestType requested requestedAt requestedBy
requestedIntegrationIds requestedSeasons requests requestsDeferred requestsFailed requestsProcessing required
requiredNextTool requiredProps requiredSecrets requiresApiKey requiresPermission requiresSessionHandshake
requiresStep requiresUrlConfirmation reset resetErrorBoundary resetInput resetKey resetKeys resetLayout
resetProp resetSelectedOption resetTours resizable resize resizeSource resolution resolutions resolve
resolveConnectionAsync resolveTokenAsync resolved resolvedIntegrationIds resolvedIntegrationKinds
resolvedOptions resolver resource resourceId resourceType resources resourcesStats respectReducedMotion
response responseError responseShape responseStatus rest restart restartAll restarting restoredStepCount result
resultCount result_count results resume resumeItem resumeItemAsync resumeQueue resumeQueueAsync resumeTorrent
resumedownload retry retryAfterMs retryAt retryAttempt retryLabel return revealKey revealText reverse review
reviseTemplate revision revokeObjectURL rich right rightGutterColumnCount rightSection rightSidebar ring
ringSize rm rock role romm rommStatsProvider roms root rootAttributes rootCompact rootHeight rootReadSeriesName
rootSeriesName rootShort rootWidth rootWriteSeriesName rotationInterval rotationIntervalSeconds round
routedProvider router routers row rowCount rowCursor rowGap rowHeight rowItemHeight rowItemWidth rowKey
rowMaxHeight rowStriped rows rs rscWidgetPrefetch rss rssFeed rssFeedRouter rule ruleId rules rulesAndPaths
rules_count run runCallback runnerStatus running runtime runtimeEnv runtimeQueries rv rx s sabNzbApiCallAsync
sabNzbApiCallWithCustomFetchAsync sabNzbd safeExtend safeParse safeParseAsync safety sampleDescription
sampleHint sampleLabel sampleRate save saveBoard saveEvidence saveGroupBoardPermissions
saveGroupIntegrationPermissions saveItemOptions saveLayouts saveNotebook savePartialBoardSettings
savePartialSettings savePermissions savePositions saveSession saveSettings saveUserBoardPermissions
saveUserIntegrationPermissions saves scale scaleX scaleY sceneBytes sceneDuration scene_count scenes
scenes_duration scenes_size schema schemaTab schemaVersion schemas scope scopeId scopes score screenshots
scrollAreaProps scrollIntoView scrollable scrutiny scrutinyStatsProvider search searchAlbumAssetsAsync
searchAsync searchButton searchCity searchDisplay searchEngine searchEngineRouter searchEngines
searchInIntegration searchMediaRequests searchParams searchRoot searchStations searchText search_value
searchable season seasonName seasonNumber seasons second secondType secondaryColor secondaryText seconds secret
secretClear secretKind secretKinds secretRows secretSet secrets secretsRouter section sectionCollapseStates
sectionId sectionIndicatorRequirement sectionLabel sectionLayouts sectionRouter sections secure_core_only
security securitySchemes securityUpdates securityUpdatesCriticalAt securityUpdatesThresholdMode
securityUpdatesWarningAt security_updates seeder seeding seerr segmentCount select selectInput selectable
selected selectedAppIds selectedContainers selectedDockerSourceIds selectedFirewall selectedIntegrationIds
selectedProject selectedWidgetKinds selection selectionSet send sendAnalytics sending sent separator serial
serialNumber series seriesName seriesTitle server serverId serverName serverResourceCounts serverSettings
serverSettingsRouter serverUrl server_id server_selection servername servers service serviceName serviceTier
service_tier services servicesRouter session sessionId sessionName sessionRevision sessionRow sessionStore
session_id sessionid sessions sessionsBeforeLongBreak set setAccordionValue setActivatorNodeRef setAsync
setAttribute setCellAttribute setClientFilter setColor setColumnsOrder setContent setCurrentIndex setData
setDate setEditable setFieldError setFieldValue setHighlight setHomeBoard setHours setInputValue setItem
setLiveActions setMobileHomeBoard setMonth setMultipleColumnWidths setNodeMarkup setNodeRef setOptions
setPaused setPreviewLiveActions setProfileImage setQueryData setQueryState setSecret setSecrets setSignal
setState setStatusFilter setTimeout setValueAtTime setValues settingKey settings settingsForm settingsGet
settingsKey settingsPanel settingsSet setups severity sha256 shape shared sharedProps shift short
shortBreakMinutes shortName shorthand should shouldDehydrateQuery shouldHide shouldRerenderOnTransaction
showActiveSessions showAgent showAgents showAlbums showAllStats showAppName showApplications showArtists
showAudiobooks showAverageUptime showBackgroundBar showBandwidth showBars showBattery showBitrate showBroadcast
showBroadcastMessage showCacheHitRate showChange showChartAxes showCity showCompletedHttp showCompletedTorrent
showCompletedUsenet showComplianceHero showCondition showContextUsage showCorrespondents showCpu
showCurrentWindSpeed showCustomAppNameOnLogin showCustomGreetingOnLogin showCustomLogoOnLogin showDate
showDescription showDescriptionTooltip showDetailedStats showDetails showDisk showDiskIO showDockerCpu
showDockerMemory showDockerNetwork showDocumentStats showDocumentTypes showDocumentsInbox showDocumentsTotal
showDownCount showEntryPoints showFooter showGpu showGpuMemory showGpuPower showGpuUsage showGreeting
showGroups showHealthIssues showHero showHighLow showHistory showHostname showHostsNeedingUpdates
showHostsWithSecurityUpdates showHumidity showIcon showImage showInboxRatio showInboxRing showIntegrationSource
showIp showLabel showLatestResult showLegend showLibraryCount showListeningTime showLoad showLoadAvg
showLocation showLogo showLogos showLogsLink showMemory showMissing showMissingEpisodes showMissingMovies
showMitre showModelInfo showName showNet showNetwork showOnlyHighlighted showOnlyIcon showOnlyPlaying
showOpenAll showOsDistribution showOsVersion showPageEdges showPageItems showPageRange
showParticulatesAndPollen showPausedCount showPhotoInfo showPhotos showPingGraph showPodcasts showPollen
showPollutants showPosterImage showProgress showProviderIssues showQueueDetails showQueued showRange
showRecentActivity showRecentResults showRecentUpdates24h showRemoveButton showRequests showRing showRuleId
showSecondary showSecondaryCounts showSecondaryStats showSecondaryText showSeconds showSecurityUpdates
showServers showServices showSongs showSource showSourceIp showSourceIps showSparkline showSpeculative
showSpeedColumns showSpeedStats showStateColumn showStats showStorage showStreams showTabLabels showTags
showTcp showTemp showTemperature showTemperatureIfAvailable showText showTicks showTimeColumn showTitle
showToggleAllButtons showTokenStats showToolbar showTotal showTotalHosts showTotalMonitors
showTotalOutdatedPackages showTotalRepos showTrend showType showUdp showUnmonitored showUpCount
showUpToDateHosts showUpdateList showUpdatedAt showUptime showUptimeRing showUsers showUv showVersion
showVideos showViolations showVoltage showWeather showWifi showWired showXAxis shows sid signDisplay signal
signals simulated sin sinkListItem site size sizeDiff sizeOnDisk sizeleft skillMd skillsShUrl skip
skipContextMenu skipYellow skippedWidgets slice slider slots slskd slug sm smart smartHome smartHomeRouter
smartItem smartStatus smart_status snapshot solarDetails some sonarr sonarrSignalr sonarr_signalr songCount
songs sort sortButton sortBy sortDirection sortKey sortable sortableItemList sorts sound source
sourceAudioChannels sourceAudioCodec sourceAudioCodecDisplay sourceAudioDetails sourceCacheVersion
sourceColumns sourceConfigurations sourceConfigure sourceContainer sourceExcerpt sourceId sourceIds sourceIp
sourceIps sourceName sourceSetup sourceType sourceUrl sourceVideoCodec sourceVideoCodecDisplay
sourceVideoDetails sourceVideoHeight sourceVideoWidth sources spacing spec specAcceptedTokens specDraftTokens
specDrafts species speculative speed speedUnit speedtestTracker speedtestTrackerRouter speedtest_ping splice
split spoolman spoolmanStatsProvider spools sql sqrt src srcip ssr stack stackAdvancedContent stackId
stagedHealthCheckCount stagedTranscodeCount staleDescription staleReleaseWithin staleTime staleTimeSeconds
staleTitle stalled starsCount start startAll startAsync startAt startDate startIndex startJob startLine startOf
startTime startUtc start_time startedAt starter starting startsWith stash stashStatsProvider stat statGrid
statIcon statItem statItemCompact statItemDense statKey statKeys statLabel statLabelShort statTile
statTileAdvanced statTileCompact statTileNarrowShort statTileShort statTileWarning statValue
statValueNarrowShort statValueWarning statValues state stateCounts states staticHeaders station stationId
statistics stats statsCount statsEntries statsRouter statsSection statsSectionCompact status statusCode
statusDot statusFilter statusPageUrl statusReason statusText status_file_path status_threshold statuses steel
step stepTimeoutMs steps stock stockPrice stockPriceRouter stop stopAll stopJob stopPropagation stopped
stoppedAt storage storageArea storageClassName storagePlugin storages store storeKey storeKeyPrefix stored
storedItems storedUnit stream streamAudioCodec streamAudioCodecDisplay streamAudioDetails streamContainer
streamType streamVideoCodec streamVideoCodecDisplay streamVideoDetails stream_only streamed
streamedBeszelSelection streams streamsActive streamsAll streamsXepg strict strictObject string stringLength
stringify stroke strokeDasharray strokeOpacity studio studio_count studios style styles su sub subTitle
subcomponents subdomain subject submission submissionId submit submitFeedback submitIfDirty submittedFeedback
submittedItems subscribe subscribeAsync subscribeLogs subscribeRealtimeMetrics subscribeSystemStats
subscribeToStatusUpdates subscription subscriptions subsonicRequestAsync substring subsystem subtitle
subtitleInfo subtitleKey subtract success successMessage suffix suggestedBaseUrl suggestedUrl sulphurDioxide
sumLoad sum_other_doc_count summaries summarizeResources summary sunrise sunriseAt sunset sunsetAt superRefine
supplementaryMessage support supportedIntegrations supportedProps supportedValuesOf supported_features
supported_parameters supportsAdvancedFocus surface sv switch switchEntity switchOption symbol sync
syncthingRelay syncthingRelayStatsProvider synology sys_temp syscheck system systemDisks systemId
systemIntegrationIds systemMonitoring systemName systemNameMap systemPanel systemResources systemStats
system_load system_need_repair systems t tCommon tabindex table tableColumnAfterControlLabel
tableColumnBeforeControlLabel tableColumnDeleteControlLabel tableDeleteControlLabel tableInsertControlLabel
tableInsertLabel tableLayout tableMergeCellsControlLabel tableRowAfterControlLabel tableRowBeforeControlLabel
tableRowDeleteControlLabel tableSplitCellControlLabel tableToggleHeaderColumnControlLabel
tableToggleHeaderRowControlLabel tableViewport tactic tactics tag tagId tagIds tag_count tagline tags tagsCount
tail take tandoor tandoorStatsProvider target targetBoardId targetBoardName targetPort targetPorts targetUrl
targetUserId targetUtc targets taskId taskListTypeName tcp tdarr technique techniques technitiumDns telemetry
tellActive tellStatus tellStopped tellWaiting temp temperature temperatureSummary temperatureUnit
temperature_unit template templateDigest templateLength templateLineCount templateLines templatePatch
templateSize templateWarnings temporaryDisable temporaryDisableBlockingTill term terms test testAction
testAllAsync testAllIndexers testAsync testConnection testConnectionAsync testError testIntegration
testingAsync text textAlign textContent textDecoration textFallback textLinesClamp textOverflow textSize
textTransform textWithIcon theme then thickness thin thread threadId threads threshold throttled throwIfAborted
throwOnAllFailures thumb thumbPath thumbUrl thumbhash thumbprint ti tick tickFormatter tickLine tickMargin
ticks tier tile tileButton tileValue time timeFrame timeInterval timeLeft timePeriod timeRange timeSplit
timeStyle timeZone timeZoneOptions time_added time_units timeleft timeline timeout timeoutMs timer timerMinutes
timestamp timetable timetableRouter timezone timezoneList tiny title titleBlock titleKey titleSize titleSlug
titleStyle tls tmdbId to toArray toDate toFixed toISOString toJSDate toJSONSchema toLocaleDateString
toLocaleLowerCase toLocaleString toLocaleTimeString toLowerCase toPrecision toResult toReversed toSeconds
toSorted toString toUpperCase together toggle toggleBoardEdit toggleColorScheme toggleDns toggleEnabled
toggleExpandedDisplay togglePolling toggleSlideshow toggleStats toggleTaskList token tokenID tokenId
tokenSecret tokensGenerated tokensProcessed tokens_completion tokens_prompt tolerateEmptyLibrary tool
toolCallId toolCalls toolInput toolName toolResults toolSupport toolTimeoutMs toolbar toolbarMaxHeight tools
tooltip tooltipAnimationDuration tooltipLabel tooltipProps top topAgents topCount topCves topDateTicks
topReleases topSourceIps top_blocked_domains top_clients top_queried_domains topic tor_only torrents torznabUrl
total totalAudiobooks totalBitrate totalBlocked totalBytes totalCapacityInBytes totalCategories totalContainers
totalCount totalDown totalDuration totalDurationMs totalDurationSeconds totalElements totalEpisodeCount
totalFileCount totalFileSize totalFiles totalHealthCheckCount totalHosts totalItemPrice totalItems totalLabels
totalLength totalLibraryUsageInBytes totalListeningTimeSeconds totalLocations totalMonitors totalObserved
totalOutdatedPackages totalOutdatedPackagesCriticalAt totalOutdatedPackagesThresholdMode
totalOutdatedPackagesWarningAt totalPages totalPageviews totalPodcasts totalQueries totalRecipes totalRecords
totalRepos totalSavedSpace totalSessions totalSize totalSizeBytes totalSpeed totalTags totalTime totalTimeoutMs
totalTranscodeCount totalUp totalUpSpeed totalUsers totalValue totalVisitors totalVisits totalWithWarranty
totalWorkers total_affected_items total_cost total_hosts total_outdated_packages total_real total_repos
total_results total_size total_uploaded total_wanted totals totaltime touch tour tr tracearr tracearrRouter
track_total_hits traefik traefikRouter transaction transactions transcode transcodeAudio transcodeInfo
transcodeStatus transcodeVideo transcodes transcoding transferOwnership transform transformOrigin transformer
transition transitionDuration transitionTimingFunction transmission transmit transparent transport trash
trigger triggerAriaLabel triggerAsync triggerAutomationAsync triggerContent triggerJob triggerToggleAsync
triggered trilium triliumStatsProvider trim trimEnd trimStart true truenas trunc trustHostnameMismatch ts ttlMs
ttlSeconds tubearchivist tubearchivistStatsProvider tuple tv tx type typeRef types typographyStylesProvider tz
tzid u udp uid umami umamiEventName umamiEventNames umamiEventSeries umamiRouter umamiTopPages
umamiTopReferrers umamiVisitorStats umamiWebsite umamiWebsites uname_after unauthorized unavailable unchanged
undefined undo unhealthy unicodeEmail unifiController union uniqueIdentifier unit unitDisplay
unit_of_measurement unix unknown unmanic unmanicStatsProvider unmonitored unpause unpauseAll unraid unreachable
unread unreads unsavedPreview unscored unsetColor unsetHighlight unshift unstable_concat unwrap up upCount
upSpeed upToDate upToDateHosts upToDateHostsCriticalAt upToDateHostsThresholdMode upToDateHostsWarningAt
up_command up_time up_to_date_hosts upcoming update updateAttributes updateAvailable updateBoardSettings
updateChecker updateCheckerRouter updateConfiguration updateConnection updateContent updateFromPreview
updateGroup updateIntervalAsync updateItemLayout updateItemStatus updateJobInterval updateKind updateListener
updateNote updateNoteAsync updatePreferences updateSelectedOptionIndex updateThreadModel update_count updated
updatedAt updated_at updates updatesAvailable upgrade_ready upload uploadLength uploadMedia uploadSpeed
upload_bits upload_payload_rate upload_rate uploaded uploadedEver uppercase uppercaseLabels ups upsRouter
upsSummary upspeed upstreamCost upstream_inference_cost upstreams uptime uptimeKuma uptimeKumaRouter uptimeList
uptimePercent24h uptime_seconds uri uris url urlCandidates urlConfirmed urlError urlTemplate urls urlset usAqi
usAqiMax usSubIndices usage usageOverTime use useCallback useCustomThresholds useCustomTimezone useData
useDefaults useImperialSpeed useMemo useMutation useOptions usePiHoleColors useQueries useQuery useState
useSubscription useSuspenseQuery useUtils used usedBytes usedTimeZones usedTokens usedValue used_size user
userAvatarUrl userCard userCount userId userName userOnly userPermissions userRouter userSelect userThumb
user_count user_load username usernameKind users utc utcOffset utcOffsetSeconds utcTimezone utc_deadline
utilization uuid uv uvIndex uvIndexMax v val valid validFrom validFromDate validTo validToDate validate
validateInputOnBlur validateInputOnChange validateSchema validateTemplate validationId validationIssues value
valueFormatter valueGap valueMiw valueName valueOf valuePath valueTooltip value_as_string value_name values
variable variant verbatim verbosity verified verifiedLength verifyIntegrityPending version versionApi
versionFilter versionFilterPrecisionOptions versionRegex version_string versions verticalAlign vgmdb video
videoCodec videoCodecs videoContainers videoCount videoDecision videoResolution videoResolutions
video_codec_name video_resolution videos view viewMode viewOffset viewed viewport violations violet visibility
visibilityState visible visibleCharts visibleClusterSections visibleCount visibleStatKeys visibleStorageVolumes
visit visitArrow visitorStats visitors visits vmId vmid vms void vol_info vol_path volume volumeMode volumeName
volume_id volumes volumesRouter vpn vpnProvider vpnRouter vpnStatus vulnerabilities w wanStatus warn warning
warningAt warnings watch watched water watts wazuh wazuhAgents wazuhAlerts wazuhAuthFailures wazuhDashboardUrl
wazuhFim wazuhIndexerPassword wazuhIndexerUrl wazuhIndexerUsername wazuhRouter wazuhSummary wazuhTimeline
wazuhTopList wazuhVulnerabilities wb wbm weather weatherCode weatherContent weatherLocation weatherOnly
weatherRouter weatherSurface webSearchEnabled webSocket webSocketUrl webkitAudioContext websiteId websiteName
websites weekday weekdaysRow wf when whenTargetIsKnown whenTargetIsUnknown when_failed where white whiteSpace
wide widget widgetDefinitionId widgetId widgetItemId widgetItemUnavailable widgetKey widgetKind widgetName
widgetRouter widgetRuntimeRef widgetSchema widgetSecrets widgetSecretsRouter widgetStateRef width wifi
windGusts windSpeed wireguard with withAsterisk withAuthAsync withAuthenticatedSessionAsync withBorder
withDescription withDropdown withDynamicImport withExif withField withIntegrations withLegend withOptions
withPermissions withPlaceholder withResolvers withScrollArea withTokenRetryAsync withXAxis withYAxis
withinPortal wm wordBreak words workerType workers workers_status workshop workshopApiUrl workshopGet
workshopInstall workshopSearch workshopWebUrl workspace worldClockCities wrapper wrapperStyle write writeFile
writeTemplate writeText wud wudRouter www x xAxisProps xOffset xTicks xai xl xs xteve xteveStatsProvider y
yAxisDomain yAxisFormatter yAxisId yAxisProps yOffset yScale year yellow yourSpotify yourSpotifyStatsProvider
zIndex zodError zodSchema zonedTime zones
`
    .trim()
    .split(/\s+/),
);
