const {chromium}=require('/tmp/bunx-1000-@playwright/mcp@0.0.79/node_modules/playwright');const fs=require('fs');
(async()=>{
const b=await chromium.launch({headless:true,executablePath:'/home/habs/.cache/ms-playwright/chromium-1228/chrome-linux64/chrome',args:['--no-sandbox']});
const p=await b.newPage({viewport:{width:1920,height:1080}});p.setDefaultTimeout(15000);await p.addInitScript(()=>{window.__timelines={}});const errors=[];p.on('pageerror',e=>errors.push(e.message));const base='http://100.111.30.70:3019/impact-stream/';
await p.goto(base+'intro/');await p.waitForFunction(()=>document.fonts.status==='loaded');
const intro=await p.evaluate(()=>{document.getElementById('root').style.cssText='width:1920px;height:1080px';const tl=window.__timelines['workshop-intro'];const columns=[...document.querySelectorAll('.integration-column')];const tiles=[...document.querySelectorAll('.all-item')];const backdrop=document.querySelector('.integration-backdrop');const seen=new Set();const counts=[];const opacities=[];for(let t=0;t<=6.8;t+=.1){tl.seek(t);let count=0;for(const e of tiles){const r=e.getBoundingClientRect();if(r.x>=0&&r.right<=1920&&r.y>=0&&r.bottom<=1080)seen.add(e.innerText);if(r.bottom>0&&r.y<1080)count++;}counts.push(count);opacities.push(...columns.map(e=>Number(getComputedStyle(e).opacity)),Number(getComputedStyle(document.querySelector('.integration-field')).opacity));}const backdropOpacity={};for(const t of [0,2.9,3,3.5,4,5]){tl.seek(t);backdropOpacity[t]=Number(getComputedStyle(backdrop).opacity);}tl.seek(0);const starts=columns.map(e=>e.getBoundingClientRect().y);const phases=starts.map(y=>((Math.round(y)%136)+136)%136);tl.seek(3);const directions=columns.map((e,i)=>e.getBoundingClientRect().y-starts[i]);tl.seek(6.7);return{columns:columns.length,tiles:tiles.length,seen:[...seen].sort(),phases,directions,allOpaque:opacities.every(x=>x===1),backdropOpacity,cleared:columns.every(e=>{const r=e.getBoundingClientRect();return r.bottom<=0||r.top>=1080}),counts,title:document.querySelector('.headline').innerText,background:getComputedStyle(document.querySelector('.integration-field')).backgroundColor,missing:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)};});
const expected=JSON.parse(fs.readFileSync(__dirname+'/opening-integrations.json')).map(i=>i.name).sort();
if(intro.columns!==8||intro.tiles!==95||new Set(intro.phases).size!==8||JSON.stringify(intro.seen)!==JSON.stringify(expected)||intro.directions.some((d,i)=>i%2?d<=0:d>=0)||!intro.allOpaque||intro.backdropOpacity['0']!==1||intro.backdropOpacity['2.9']!==1||intro.backdropOpacity['3']!==1||Math.abs(intro.backdropOpacity['3.5']-.5)>.01||intro.backdropOpacity['4']!==0||intro.backdropOpacity['5']!==0||!intro.cleared||!intro.title.includes('Announcing')||intro.title.includes('about')||intro.background!=='rgba(0, 0, 0, 0)'||intro.missing.length)throw Error(JSON.stringify(intro));
for(const t of [0,2.9,3.5,4.1,6.7,8]){await p.evaluate(t=>{window.__timelines['workshop-intro'].seek(t)},t);await p.screenshot({path:__dirname+'/intro-'+t+'.png'});}
await p.goto(base+'workshop/');await p.evaluate(()=>{document.getElementById('root').style.cssText='width:1920px;height:1080px';window.__timelines.workshop.seek(2)});const workshop=await p.locator('.sub').innerText();if(workshop!=='Finally a way to share your custom CSS with the community.')throw Error(workshop);await p.screenshot({path:__dirname+'/workshop-source.png'});
const out={intro,workshop,errors};if(!process.argv.includes('--sources-only')){
 await p.setViewportSize({width:1600,height:1050});await p.goto(base);const results=[];
 for(const [name,minTime,wait] of [['Intro',7.5,8000],['Community Workshop',11,2500],['New widgets',77,4000],['Workshop · Merch',109,4500]]){await p.getByRole('button',{name,exact:true}).click();await p.waitForTimeout(wait);const r=await p.locator('video').evaluate(v=>{v.pause();return{time:v.currentTime,duration:v.duration,width:v.videoWidth,height:v.videoHeight,dropped:v.getVideoPlaybackQuality().droppedVideoFrames,frames:v.getVideoPlaybackQuality().totalVideoFrames,muted:v.muted}});if(r.time<minTime||Math.abs(r.duration-6760/60)>.05||r.width!==1920||r.height!==1080||r.muted)throw Error(JSON.stringify(r));results.push({name,...r});}out.results=results;
}
fs.writeFileSync(__dirname+'/verification.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out));await b.close();if(errors.length)process.exit(1);
})().catch(e=>{console.error(e);process.exit(1)});
