import {
  IconActivityHeartbeat,
  IconAd,
  IconApi,
  IconApps,
  IconArchive,
  IconBadgeCc,
  IconBatteryCharging,
  IconBell,
  IconBinaryTree,
  IconBookmark,
  IconBrandDocker,
  IconBrandMinecraft,
  IconBrowser,
  IconBuildingBank,
  IconBusStop,
  IconCalendar,
  IconChartAreaLine,
  IconChartBar,
  IconClock,
  IconClockPlay,
  IconCloud,
  IconDeviceCctv,
  IconDeviceGamepad,
  IconDownload,
  IconFileText,
  IconGraphFilled,
  IconHourglass,
  IconHeadphones,
  IconHeartRateMonitor,
  IconHeartbeat,
  IconLayoutGrid,
  IconMessage,
  IconMovie,
  IconNotes,
  IconPhoto,
  IconReportSearch,
  IconRocket,
  IconRobot,
  IconRoute,
  IconRss,
  IconServer2,
  IconShieldCheck,
  IconShieldLock,
  IconSpeedboat,
  IconTable,
  IconTicket,
  IconTopologyFull,
  IconTransform,
  IconVideo,
  IconWall,
  IconWind,
  IconZoomQuestion,
} from "@tabler/icons-react";

import type { WidgetKind } from "@homarr/definitions";
import type { TablerIcon } from "@homarr/ui";

export const widgetCatalogIcons: Record<WidgetKind, TablerIcon> = {
  clock: IconClock,
  weather: IconCloud,
  airQuality: IconWind,
  countdown: IconHourglass,
  timer: IconClockPlay,
  app: IconApps,
  assistant: IconRobot,
  iframe: IconBrowser,
  video: IconDeviceCctv,
  notebook: IconNotes,
  anchorNote: IconNotes,
  dnsHoleSummary: IconAd,
  dnsHoleControls: IconDeviceGamepad,
  "smartHome-entityState": IconBinaryTree,
  "smartHome-executeAutomation": IconBinaryTree,
  stockPrice: IconBuildingBank,
  mediaServer: IconVideo,
  calendar: IconCalendar,
  downloads: IconDownload,
  "mediaRequests-requestList": IconZoomQuestion,
  "mediaRequests-requestStats": IconChartBar,
  mediaTranscoding: IconTransform,
  mediaMissing: IconMovie,
  minecraftServerStatus: IconBrandMinecraft,
  networkControllerSummary: IconTopologyFull,
  networkControllerStatus: IconTopologyFull,
  rssFeed: IconRss,
  bookmarks: IconBookmark,
  indexerManager: IconReportSearch,
  healthMonitoring: IconHeartRateMonitor,
  releases: IconRocket,
  mediaReleases: IconTicket,
  dockerContainers: IconBrandDocker,
  firewall: IconWall,
  notifications: IconMessage,
  systemResources: IconGraphFilled,
  coolify: IconCloud,
  systemDisks: IconServer2,
  timetable: IconBusStop,
  "immich-serverStats": IconGraphFilled,
  "immich-albumCarousel": IconPhoto,
  paperlessNgx: IconFileText,
  patchmon: IconShieldCheck,
  bazarr: IconBadgeCc,
  tracearr: IconActivityHeartbeat,
  speedtestTracker: IconSpeedboat,
  uptimeKuma: IconHeartbeat,
  audioStats: IconHeadphones,
  umami: IconChartBar,
  vpn: IconShieldLock,
  archiveTeamWarrior: IconArchive,
  ups: IconBatteryCharging,
  beszelSystemTable: IconTable,
  beszelSystemGrid: IconLayoutGrid,
  beszelAlerts: IconBell,
  beszelSystemStats: IconChartAreaLine,
  traefik: IconRoute,
  customApi: IconApi,
  wud: IconBrandDocker,
};
