export const supportedIntegrations = [
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/homarr.svg', name: 'Homarr' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/sabnzbd.svg', name: 'SABnzbd' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/deluge.svg', name: 'Deluge' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/radarr.svg', name: 'Radarr' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/sonarr.svg', name: 'Sonarr' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/lidarr.svg', name: 'Lidarr' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/loganmarchione/homelab-svg-assets/assets/pihole.svg', name: 'PiHole' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/dashdot.png', name: 'Dashdot' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/overseerr.svg', name: 'Overseerr' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/plex.svg', name: 'Plex' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/jellyfin.svg', name: 'Jellyfin' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/loganmarchione/homelab-svg-assets/assets/homeassistant.svg', name: 'Homeassistant' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/loganmarchione/homelab-svg-assets/assets/freshrss.svg', name: 'FreshRSS' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/readarr.svg', name: 'Readarr' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/transmission.svg', name: 'Transmission' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/qbittorrent.svg', name: 'qBittorrent' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nzbget.png', name: 'NZBGet' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/openmediavault.svg', name: 'Openmediavault' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/loganmarchione/homelab-svg-assets/assets/docker.svg', name: 'docker' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/jellyseerr.svg', name: 'Jellyseerr' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/loganmarchione/homelab-svg-assets/assets/adguardhome.svg', name: 'AdguardHome' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/tdarr.png', name: 'Tdarr' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/prowlarr.svg', name: 'Prowlarr' },
  { iconUrl: 'https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/ical.svg', name: 'iCal' },
];
