const {chromium}=require('/tmp/bunx-1000-@playwright/mcp@0.0.79/node_modules/playwright');const fs=require('fs');
(async()=>{
const b=await chromium.launch({headless:true,executablePath:'/home/habs/.cache/ms-playwright/chromium-1228/chrome-linux64/chrome',args:['--no-sandbox']});
const p=await b.newPage({viewport:{width:1920,height:1080}});p.setDefaultTimeout(15000);await p.addInitScript(()=>{window.__timelines={}});const errors=[];p.on('pageerror',e=>errors.push(e.message));const base='http://100.111.30.70:3019/impact-fade/';
await p.goto(base+'intro/');await p.waitForFunction(()=>document.fonts.status==='loaded');
const intro=await p.evaluate(()=>{document.getElementById('root').style.cssText='width:1920px;height:1080px';const tl=window.__timelines['workshop-intro'];const columns=[...document.querySelectorAll('.integration-column')];const tiles=[...document.querySelectorAll('.all-item')];const seen=new Set();for(let t=0;t<=4.4;t+=.1){tl.seek(t);for(const e of tiles){const r=e.getBoundingClientRect();if(r.x>=0&&r.right<=1920&&r.y>=0&&r.bottom<=1080)seen.add(e.innerText);}}tl.seek(0);const starts=columns.map(e=>e.getBoundingClientRect().y);const phases=starts.map(y=>((Math.round(y)%136)+136)%136);tl.seek(3);const directions=columns.map((e,i)=>e.getBoundingClientRect().y-starts[i]);tl.seek(5.4);const halfway=Number(getComputedStyle(document.querySelector('.integration-field')).opacity);tl.seek(6.5);return{columns:columns.length,seen:[...seen].sort(),phases,directions,halfway,finalOpacity:Number(getComputedStyle(document.querySelector('.integration-field')).opacity),hasCurtains:!!document.querySelector('.integration-curtain'),missing:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)};});
const expected=JSON.parse(fs.readFileSync(__dirname+'/opening-integrations.json')).map(i=>i.name).sort();
if(intro.columns!==8||new Set(intro.phases).size!==8||JSON.stringify(intro.seen)!==JSON.stringify(expected)||intro.directions.some((d,i)=>i%2?d<=0:d>=0)||Math.abs(intro.halfway-.5)>.01||intro.finalOpacity!==0||intro.hasCurtains||intro.missing.length)throw Error(JSON.stringify(intro));console.log('87 integrations; eight distinct offsets; alternating directions; complete fade.');
await p.goto(base+'widgets/');const widgets=await p.evaluate(()=>{document.getElementById('root').style.cssText='width:1920px;height:1080px';const tl=window.__timelines.widgets,v=document.getElementById('timer-demo'),card=document.querySelector('.wc-timer');const frames=[];for(const t of [0,.2,.5,1]){tl.seek(t);let opacity=1;for(let e=v;e;e=e.parentElement)opacity*=Number(getComputedStyle(e).opacity);const r=v.getBoundingClientRect(),c=card.getBoundingClientRect();frames.push({t,opacity,cardOpacity:Number(getComputedStyle(card).opacity),relativeY:r.y-c.y});}return{nested:v.closest('.widget-card')===card,frames}});
if(!widgets.nested||widgets.frames[0].opacity!==0||widgets.frames[1].opacity!==0||widgets.frames[2].opacity<=0||widgets.frames[3].opacity!==1||widgets.frames.some(f=>Math.abs(f.opacity-f.cardOpacity)>.001)||Math.max(...widgets.frames.map(f=>f.relativeY))-Math.min(...widgets.frames.map(f=>f.relativeY))>.01)throw Error(JSON.stringify(widgets));console.log('Timer is hidden initially and enters with its card.');
await p.goto(base+'ending/');const ending=await p.evaluate(()=>({text:document.body.innerText,duration:Number(document.getElementById('root').dataset.duration)}));for(const s of ['Workshop merch giveaway.','favorite Workshop submissions','exclusive Homarr merch','Better get cooking if you want to wear some dope lobster merch.'])if(!ending.text.includes(s))throw Error('Missing outro copy: '+s);if(ending.duration!==7)throw Error('Outro duration changed');
fs.writeFileSync(__dirname+'/source-verification.json',JSON.stringify({intro,widgets,ending,errors},null,2));
if(process.argv.includes('--sources-only')){console.log({intro,widgets});await b.close();return;}
await p.setViewportSize({width:1600,height:1050});await p.goto(base);const results=[];
for(const [name,minTime,wait] of [['Intro',7.5,8000],['Custom Widgets v2',28,2500],['New drag-and-drop',50,2600],['New widgets',77,4000],['Workshop · Merch',110,5000]]){
 await p.getByRole('button',{name,exact:true}).click();await p.waitForTimeout(wait);const r=await p.locator('video').evaluate(v=>{v.pause();return{time:v.currentTime,duration:v.duration,width:v.videoWidth,height:v.videoHeight,dropped:v.getVideoPlaybackQuality().droppedVideoFrames,frames:v.getVideoPlaybackQuality().totalVideoFrames,muted:v.muted}});if(r.time<minTime||Math.abs(r.duration-6760/60)>.05||r.width!==1920||r.height!==1080||r.muted)throw Error(JSON.stringify(r));results.push({name,...r});
}
fs.writeFileSync(__dirname+'/verification.json',JSON.stringify({intro,widgets,ending,results,errors},null,2));console.log({results,errors});await b.close();if(errors.length)process.exit(1);
})().catch(e=>{console.error(e);process.exit(1)});
