import type { IntegrationKind } from "@homarr/definitions";

// Type-only imports — fully erased at build, zero runtime modules loaded.
import type { AdGuardHomeIntegration } from "../adguard-home/adguard-home-integration";
import type { AnchorIntegration } from "../anchor/anchor-integration";
import type { ArchiveTeamWarriorIntegration } from "../archive-team-warrior/archive-team-warrior-integration";
import type { AudiobookshelfIntegration } from "../audiobookshelf/audiobookshelf-integration";
import type { BazarrIntegration } from "../bazarr/bazarr-integration";
import type { BeszelIntegration } from "../beszel/beszel-integration";
import type { CoolifyIntegration } from "../coolify/coolify-integration";
import type { DashDotIntegration } from "../dashdot/dashdot-integration";
import type { Aria2Integration } from "../download-client/aria2/aria2-integration";
import type { DelugeIntegration } from "../download-client/deluge/deluge-integration";
import type { NzbGetIntegration } from "../download-client/nzbget/nzbget-integration";
import type { QBitTorrentIntegration } from "../download-client/qbittorrent/qbittorrent-integration";
import type { SabnzbdIntegration } from "../download-client/sabnzbd/sabnzbd-integration";
import type { SlskdIntegration } from "../download-client/slskd/slskd-integration";
import type { TransmissionIntegration } from "../download-client/transmission/transmission-integration";
import type { EmbyIntegration } from "../emby/emby-integration";
import type { GlancesIntegration } from "../glances/glances-integration";
import type { GluetunIntegration } from "../gluetun/gluetun-integration";
import type { GotifyIntegration } from "../gotify/gotify-integration";
import type { HomeAssistantIntegration } from "../homeassistant/homeassistant-integration";
import type { ICalIntegration } from "../ical/ical-integration";
import type { ImmichIntegration } from "../immich/immich-integration";
import type { JellyfinIntegration } from "../jellyfin/jellyfin-integration";
import type { JellyseerrIntegration } from "../jellyseerr/jellyseerr-integration";
import type { LidarrIntegration } from "../media-organizer/lidarr/lidarr-integration";
import type { RadarrIntegration } from "../media-organizer/radarr/radarr-integration";
import type { ReadarrIntegration } from "../media-organizer/readarr/readarr-integration";
import type { SonarrIntegration } from "../media-organizer/sonarr/sonarr-integration";
import type { TdarrIntegration } from "../media-transcoding/tdarr-integration";
import type { MockIntegration } from "../mock/mock-integration";
import type { NavidromeIntegration } from "../navidrome/navidrome-integration";
import type { NextcloudIntegration } from "../nextcloud/nextcloud.integration";
import type { NTFYIntegration } from "../ntfy/ntfy-integration";
import type { OpenMediaVaultIntegration } from "../openmediavault/openmediavault-integration";
import type { OPNsenseIntegration } from "../opnsense/opnsense-integration";
import type { OverseerrIntegration } from "../overseerr/overseerr-integration";
import type { PaperlessNgxIntegration } from "../paperless-ngx/paperless-ngx-integration";
import type { PatchMonIntegration } from "../patchmon/patchmon-integration";
import type { PeaNutIntegration } from "../peanut/peanut-integration";
import type { PiHoleIntegrationV5 } from "../pi-hole/v5/pi-hole-integration-v5";
import type { PiHoleIntegrationV6 } from "../pi-hole/v6/pi-hole-integration-v6";
import type { PlexIntegration } from "../plex/plex-integration";
import type { ProwlarrIntegration } from "../prowlarr/prowlarr-integration";
import type { ProxmoxIntegration } from "../proxmox/proxmox-integration";
import type { SeerrIntegration } from "../seerr/seerr-integration";
import type { SpeedtestTrackerIntegration } from "../speedtest-tracker/speedtest-tracker-integration";
import type { SynologyIntegration } from "../synology/synology-integration";
import type { TechnitiumDnsIntegration } from "../technitium/technitium-integration";
import type { TracearrIntegration } from "../tracearr/tracearr-integration";
import type { TraefikIntegration } from "../traefik/traefik-integration";
import type { TrueNasIntegration } from "../truenas/truenas-integration";
import type { UmamiIntegration } from "../umami/umami-integration";
import type { UnifiControllerIntegration } from "../unifi-controller/unifi-controller-integration";
import type { UnraidIntegration } from "../unraid/unraid-integration";
import type { UptimeKumaIntegration } from "../uptime-kuma/uptime-kuma-integration";

export interface IntegrationInstanceMap {
  anchor: AnchorIntegration;
  adGuardHome: AdGuardHomeIntegration;
  archiveTeamWarrior: ArchiveTeamWarriorIntegration;
  aria2: Aria2Integration;
  audiobookshelf: AudiobookshelfIntegration;
  bazarr: BazarrIntegration;
  beszel: BeszelIntegration;
  coolify: CoolifyIntegration;
  dashDot: DashDotIntegration;
  deluge: DelugeIntegration;
  emby: EmbyIntegration;
  glances: GlancesIntegration;
  gluetun: GluetunIntegration;
  gotify: GotifyIntegration;
  homeAssistant: HomeAssistantIntegration;
  ical: ICalIntegration;
  immich: ImmichIntegration;
  jellyfin: JellyfinIntegration;
  jellyseerr: JellyseerrIntegration;
  lidarr: LidarrIntegration;
  mock: MockIntegration;
  navidrome: NavidromeIntegration;
  nextcloud: NextcloudIntegration;
  ntfy: NTFYIntegration;
  nzbGet: NzbGetIntegration;
  openmediavault: OpenMediaVaultIntegration;
  opnsense: OPNsenseIntegration;
  overseerr: OverseerrIntegration;
  paperlessNgx: PaperlessNgxIntegration;
  patchmon: PatchMonIntegration;
  peaNut: PeaNutIntegration;
  piHole: PiHoleIntegrationV5 | PiHoleIntegrationV6;
  plex: PlexIntegration;
  prowlarr: ProwlarrIntegration;
  proxmox: ProxmoxIntegration;
  qBittorrent: QBitTorrentIntegration;
  radarr: RadarrIntegration;
  readarr: ReadarrIntegration;
  sabNzbd: SabnzbdIntegration;
  seerr: SeerrIntegration;
  slskd: SlskdIntegration;
  sonarr: SonarrIntegration;
  speedtestTracker: SpeedtestTrackerIntegration;
  synology: SynologyIntegration;
  tdarr: TdarrIntegration;
  technitiumDns: TechnitiumDnsIntegration;
  tracearr: TracearrIntegration;
  traefik: TraefikIntegration;
  transmission: TransmissionIntegration;
  truenas: TrueNasIntegration;
  umami: UmamiIntegration;
  unifiController: UnifiControllerIntegration;
  unraid: UnraidIntegration;
  uptimeKuma: UptimeKumaIntegration;
}

export type IntegrationInstanceOfKind<TKind extends IntegrationKind> = TKind extends keyof IntegrationInstanceMap
  ? IntegrationInstanceMap[TKind]
  : never;
