name: "[Dependency Updates] Auto Approve"
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  approve-automatic-prs:
    runs-on: ubuntu-latest
    if: github.actor_id == 158783068 || github.actor_id == 190541745 || github.actor_id == 210161987 # Id of renovate bot and crowdin bot see https://api.github.com/users/homarr-renovate%5Bbot%5D and https://api.github.com/users/homarr-crowdin%5Bbot%5D and https://api.github.com/users/homarr-update-contributors%5Bbot%5D
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Obtain token
        id: obtainToken
        uses: tibdex/github-app-token@v2
        with:
          private_key: ${{ secrets.RENOVATE_APPROVE_PRIVATE_KEY }}
          app_id: ${{ secrets.RENOVATE_APPROVE_APP_ID }}
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
      - name: Approve automatic PRs
        env:
          GITHUB_TOKEN: ${{ steps.obtainToken.outputs.token }}
        run: |
          gh pr review ${{github.event.pull_request.number}} --approve --body "Automatically approved by GitHub Action"
