name: Automatic Release

on:
  schedule:
    - cron: 0 20 * * 5 # At 20:00 on Friday. - https://crontab.guru/#0_20_*_*_5
  workflow_dispatch:

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_AUTOMATIC_RELEASE }}

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Preparing the automatic release...'
      - uses: actions/checkout@v4
      - uses: peter-evans/create-pull-request@v5
        id: create-pull-request
        with:
          base: main
          branch: dev
          delete-branch: false
          title: "(chore): version update"
          reviewers: manuel-rw, meierschlumpf
      - name: Check outputs
        if: ${{ steps.create-pull-request.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.create-pull-request.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pull-request.outputs.pull-request-url }}"
      - name: Discord notification
        if: ${{ steps.create-pull-request.outputs.pull-request-number }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Deployment pull request has been created at [${{ steps.create-pull-request.outputs.pull-request-number }}](${{ steps.create-pull-request.outputs.pull-request-url }})'