name: Run E2E Tests on Label e2e-ready

on:
  pull_request:
    types:
      - labeled
jobs:
  e2e:
    runs-on: ubuntu-latest

    # This condition ensures the job only runs when the specified label is added
    if: contains(github.event.pull_request.labels.*.name, 'e2e-ready') || contains(github.event.pull_request.labels.*.name, 'e2e-skip')
    env:
      SKIP_LABEL: e2e-skip

    steps:
      - name: Emergency Skip
        if: contains(github.event.pull_request.labels.*.name, env.SKIP_LABEL)
        run: |
          echo "E2E tests skipped due to e2e-skip label"
      - name: Run E2E Tests
        if: contains(github.event.pull_request.labels.*.name, env.SKIP_LABEL) == false
        uses: homarr-labs/homarr/.github/actions/e2e-execution@e2e
