name: "[Dependency Updates] Auto Approve"
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - "renovate/**"

jobs:
  approve-renovate-prs:
    runs-on: ubuntu-latest
    if: github.actor == 'homarr-renovate[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Obtain token
        id: obtainToken
        uses: tibdex/github-app-token@v2
        with:
          private_key: ${{ secrets.RENOVATE_APPROVE_PRIVATE_KEY }}
          app_id: ${{ secrets.RENOVATE_APPROVE_APP_ID }}
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
      - name: Approve Renovate PRs
        env:
          GITHUB_TOKEN: ${{ steps.obtainToken.outputs.token }}
        run: |
          gh pr review ${{github.event.pull_request.number}} --approve --body "Automatically approved by GitHub Action"
